### ISSUE TITLE
mup.cmd setup fails

### ISSUE THREAD

**Issue by martineboh** [zodern/meteor-up#1000]
with message: 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.244.81.198:22
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by martineboh** [comment]
It seems creating another EC2 instance with the same inbound rules in Security Group fixed the issue. Closing issue
