### ISSUE TITLE
Deploying Meteor App-Mlab  failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by lastpeony** [zodern/meteor-up#1008]
I am trying to deploy my meteor app to digital ocean droplet using meteor up.After mup deploy i get this error:

```
MongoError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongodb mongodb:27017]
            at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:505:11)
            at emitOne (events.js:115:13)
            at Pool.emit (events.js:210:7)
            at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:329:12)
            at Object.onceWrapper (events.js:318:30)
            at emitTwo (events.js:125:13)
            at Connection.emit (events.js:213:7)
            at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:245:50)
            at Object.onceWrapper (events.js:316:30)
            at emitOne (events.js:115:13)
            at Socket.emit (events.js:210:7)
            at emitErrorNT (internal/streams/destroy.js:64:8)
            at _combinedTickCallback (internal/process/next_tick.js:138:11)
            at process._tickDomainCallback (internal/process/next_tick.js:218:9)
        => Starting meteor app on port:80
```
Mup.js file:
```
module.exports = {
  servers: {
    one: {
      host: '178.62.222.147',
      username: 'root',
       password: 'password'
    }
  },

  app: {
    name: 'mytestapp',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {

      ROOT_URL: 'http://178.62.222.147',
      MONGO_URL: 'mongodb://username:password@ds123012.mlab.com:23012/mytestapp',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
      PORT: 3000

    },

    docker: {
      image: 'abernix/meteord:node-8.4.0-base',
    },

    enableUploadProgressBar: true
  },

};
```
By the way in error it says Starting meteor app on port:80 isnt it should start at port 3000 ?

**Comment by lastpeony** [comment]
looks like removing        MONGO_OPLOG_URL: 'mongodb://mongodb/local',
 solved my problem
