### ISSUE TITLE
503 Service Temporary Unavailable

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#1017]
Mup version (`mup --version`): mup@1.4.5

Mup config

```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true,
      "executable": "meteor"
    },
    "env": {
      "ROOT_URL": "https://host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local",
      "VIRTUAL_HOST": "manecadincanepa.ro",
      "HTTPS_METHOD": "redirect",
      "HTTP_FORWARDED_COUNT": 1
    },
    "docker": {
      "image": "zodern/meteor:root",
      "stopAppDuringPrepareBundle": true,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.6.4",
    "servers": {
      "one": {}
    }
  },
  "proxy": {
    "domains": "manecadincanepa.ro",
    "ssl": {
      "forceSSL": true
    }
  }
}
```
After deploying Vulcan app on an AWS EC2 instance, the message ends with succes. But when verifying the IP it throws me 503 error.

I've run `docker logs <my-app>` on the server and this is what I get
```
=> Setting node version
NODE_VERSION=8.11.3
v8.11.3 is already installed.
Now using node v8.11.3 (npm v5.6.0)
Now using node v8.11.3 (npm v5.6.0)
=> Starting meteor app on port 80
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
// inserting dummy users…
// creating dummy pics…
// creating dummy comments
url:  /
{ Error: Network error: Network request failed with status 500 - "Internal Server Error"
    at new ApolloError (/built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:1981:28)
    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3091:41
    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3583:25
    at Array.forEach (<anonymous>)
    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3580:27
    at Array.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3577:42)
    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3047:31
    at /built_app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/built_app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
    at Object.preRender (packages/vulcan:routing/lib/server/routing.jsx:58:14)
    at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:53:15)
    at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)
    at match (packages/vulcan:routing/lib/server/router.jsx:150:11)
    at /built_app/programs/server/npm/node_modules/react-router/lib/match.js:67:5
    at /built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:108:11
    at done (/built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:79:19)
    at /built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:85:7
    at getComponentsForRoute (/built_app/programs/server/npm/node_modules/react-router/lib/getComponents.js:11:5)
    at /built_app/programs/server/npm/node_modules/react-router/lib/getComponents.js:35:5
    at /built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:84:5
    at Array.forEach (<anonymous>)
    at mapAsync (/built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:83:9)
    at getComponents (/built_app/programs/server/npm/node_modules/react-router/lib/getComponents.js:34:28)
    at finishEnterHooks (/built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:102:35)
    at runTransitionHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:79:7)
    at runEnterHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:112:12)
    at /built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:95:7
    at runTransitionHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:79:7)
    at runChangeHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:136:12)
    at finishMatch (/built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:92:5)
  graphQLErrors: [],
  networkError: 
   { Error: Network request failed with status 500 - "Internal Server Error"
    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:730:45
    at /built_app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
     response: 
      Body {
        url: 'https://manecadincanepa.ro/graphql',
        status: 500,
        statusText: 'Internal Server Error',
        headers: [Object],
        ok: false,
        body: [Object],
        bodyUsed: false,
        size: 0,
        timeout: 0,
        _raw: [],
        _abort: false } },
  message: 'Network error: Network request failed with status 500 - "Internal Server Error"',
  extraInfo: undefined,
  queryErrors: [ [Circular] ] }
2018-10-02T18:58:33.261Z 'error while server-rendering' 'Error: Network error: Network request failed with status 500 - "Internal Server Error"\n    at new ApolloError (/built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:1981:28)\n    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3091:41\n    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3583:25\n    at Array.forEach (<anonymous>)\n    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3580:27\n    at Array.forEach (<anonymous>)\n    at QueryManager.broadcastQueries (/built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3577:42)\n    at /built_app/programs/server/npm/node_modules/apollo-client/apollo.umd.js:3047:31\n    at /built_app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/built_app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at Object.preRender (packages/vulcan:routing/lib/server/routing.jsx:58:14)\n    at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:53:15)\n    at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)\n    at match (packages/vulcan:routing/lib/server/router.jsx:150:11)\n    at /built_app/programs/server/npm/node_modules/react-router/lib/match.js:67:5\n    at /built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:108:11\n    at done (/built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:79:19)\n    at /built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:85:7\n    at getComponentsForRoute (/built_app/programs/server/npm/node_modules/react-router/lib/getComponents.js:11:5)\n    at /built_app/programs/server/npm/node_modules/react-router/lib/getComponents.js:35:5\n    at /built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:84:5\n    at Array.forEach (<anonymous>)\n    at mapAsync (/built_app/programs/server/npm/node_modules/react-router/lib/AsyncUtils.js:83:9)\n    at getComponents (/built_app/programs/server/npm/node_modules/react-router/lib/getComponents.js:34:28)\n    at finishEnterHooks (/built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:102:35)\n    at runTransitionHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:79:7)\n    at runEnterHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:112:12)\n    at /built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:95:7\n    at runTransitionHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:79:7)\n    at runChangeHooks (/built_app/programs/server/npm/node_modules/react-router/lib/TransitionUtils.js:136:12)\n    at finishMatch (/built_app/programs/server/npm/node_modules/react-router/lib/createTransitionManager.js:92:5)'
```

**Comment by ghost** [comment]
@zodern I also tried with a plain meteor app, same mup.js file and I have the same error.
this is what I get after running `mup deploy --verbose`
```
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[<ip>] - Pushing Meteor App Bundle to the Server
[<ip>] - Pushing Meteor App Bundle to the Server: SUCCESS
[<ip>] - Prepare Bundle
root: Pulling from zodern/meteor
Digest: sha256:94388cd430fcad65bdeaeee831e409aee5ed62456cb8364c764d867a07564f77
Status: Image is up to date for zodern/meteor:root
Finished Extracting
Creating Dockerfile
Finished creating Dockerfile
Building image
Sending build context to Docker daemon  43.45MB
Step 1/10 : FROM zodern/meteor:root
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> c6ccb7e7f444
Step 2/10 : RUN mkdir /built_app || true
 ---> Using cache
 ---> 4711056a1023
Step 3/10 : ENV ROOT_URL=https://manecadincanepa.ro
 ---> Using cache
 ---> 49e999f5d801
Step 4/10 : ENV MONGO_URL=mongodb://mongodb:27017/<my-app>
 ---> Using cache
 ---> c1f2debd1b78
Step 5/10 : ENV MONGO_OPLOG_URL=mongodb://mongodb/local
 ---> Using cache
 ---> c8a041f80a29
Step 6/10 : ENV VIRTUAL_HOST=manecadincanepa.ro
 ---> Using cache
 ---> 369811ce07b1
Step 7/10 : ENV HTTPS_METHOD=redirect
 ---> Using cache
 ---> 945222f49f6b
Step 8/10 : ENV HTTP_FORWARDED_COUNT=1
 ---> Using cache
 ---> 5ebb5e39a141
Step 9/10 : COPY ./ /built_app
 ---> Using cache
 ---> 6b9929052a7d
Step 10/10 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Using cache
 ---> 6fc44093b6ff
Successfully built 6fc44093b6ff
Successfully tagged mup-<my-app>:build
Deleted Images:
deleted: sha256:1c6d469e17cd412cfd41ef4b9ac6742782eb712b293b290340e86956b1b9cf37
deleted: sha256:2b265b9ab26c751ff85ea2f62dc5ddd76510df9210566b95310030e44d3ecca3
deleted: sha256:1b06ad6211ed0577473607ebc21da0d5af9fa4dda4819746cc712c59cec2b2d5
deleted: sha256:f6e63e6da6ba2a2af0bcf74a2db9a6d7001e03169230c661753a0c0c91c1f8dc

Total reclaimed space: 243.9MB
[18.196.4.125] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[18.196.4.125] - Pushing the Startup Script
[18.196.4.125] - Pushing the Startup Script: SUCCESS
[18.196.4.125] - Sending Environment Variables
[18.196.4.125] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[18.196.4.125] - Start Meteor
using image
removing last
Image mup-<my-app>:latest
Volume
Removing docker containers. Errors about nonexistent endpoints and containers are normal.
<my-app>
Error response from daemon: endpoint <my-app> not found
Error: No such container: <my-app>-frontend
Error response from daemon: endpoint <my-app>-frontend not found
Error: No such container: <my-app>-nginx-letsencrypt
Error response from daemon: endpoint <my-app>-nginx-letsencrypt not found
Error: No such container: <my-app>-nginx-proxy
Error response from daemon: endpoint <my-app>-nginx-proxy not found
Finished removing docker containers
dffa5af915893880016589ea00743d8b24c4692047aa50d69bb582efcef042be
Ran zodern/meteor:root
[18.196.4.125] - Start Meteor: SUCCESS
[18.196.4.125] - Verifying Deployment
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html>
<html>
<head>

  <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/f39c9c7aefc88db83c522e8d1ba1e243250c905b.css?meteor_css_resource=true">
<title>test-app</title>
</head>
<body>
  <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.7.0.5%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADATA%22%3A%22%7B%7D%22%7D%2C%22PUBLIC_SETTINGS%22%3A%7B%22title%22%3A%22Your%20site%20title%22%2C%22tagline%22%3A%22Your%20site%20tagline%22%2C%22logoUrl%22%3A%22http%3A%2F%2Fplacekitten.com%2F250%2F80%22%2C%22logoHeight%22%3A%2280%22%2C%22logoWidth%22%3A%22250%22%2C%22faviconUrl%22%3A%22%2Ffavicon.ico%22%2C%22language%22%3A%22en%22%2C%22locale%22%3A%22en%22%2C%22twitterAccount%22%3A%22foo%22%2C%22facebookPage%22%3A%22http%3A%2F%2Ffacebook.com%2Ffoo%22%2C%22googleAnalytics%22%3A%7B%22apiKey%22%3A%22foo123%22%7D%7D%2C%22ROOT_URL%22%3A%22https%3A%2F%2Fmanecadincanepa.ro%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22appId%22%3A%22l7zr715ypn5y.gbqo0gj90zv%22%2C%22autoupdateVersion%22%3A%22fafb50ec3e75c9340c5025be64a70f4ac07bfe03%22%2C%22autoupdateVersionRefreshable%22%3A%2230cf50f4bb9c2e4fa8153a9fae9855847dbbb3aa%22%2C%22autoupdateVersionCordova%22%3A%22none%22%2C%22isModern%22%3Afalse%7D"))</script>

  <script type="text/javascript" src="/f5e2dc12ab3775273a0579d7f20fdf2e74d718a4.js?meteor_js_resource=true"></script>


</body>
100  1470    0  1470    0     0  48550      0 --:--:-- --:--:-- --:--:-- 52500
[18.196.4.125] - Verifying Deployment: SUCCESS
```
