### ISSUE TITLE
npm install sharp error: File already exists.

### ISSUE THREAD

**Issue by dc165015** [zodern/meteor-up#1021]
Mup version (`mup --version`):
1.4.5

Mup config

```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "admin",
      "password": "password"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "https://subdomain.host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local"
    },
    "docker": {
      "image": "abernix/meteord:node-8.4.0-base",
      "stopAppDuringPrepareBundle": true,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    }
  }
}
```

Output of command

```bash
> sharp@0.20.5 install /built_app/programs/server/npm/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.6.1/libvips-8.6.1-linux-x64.tar.gz
fs.js:891
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EEXIST: file already exists, mkdir '/built_app/programs/server/npm/node_modules/sharp/vendor'
    at Object.fs.mkdirSync (fs.js:891:18)
    at WriteStream.<anonymous> (/built_app/programs/server/npm/node_modules/sharp/install/libvips.js:61:10)
    at emitNone (events.js:105:13)
    at WriteStream.emit (events.js:207:7)
    at fs.close (fs.js:2034:12)
    at FSReqWrap.oncomplete (fs.js:135:15)
make: Entering directory '/built_app/programs/server/npm/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
g++: error: ../vendor/lib/libvips-cpp.so: No such file or directory
g++: error: ../vendor/lib/libvips.so: No such file or directory
g++: error: ../vendor/lib/libglib-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgobject-2.0.so: No such file or directory
g++: error: ../vendor/lib/libcairo.so: No such file or directory
g++: error: ../vendor/lib/libcroco-0.6.so: No such file or directory
g++: error: ../vendor/lib/libexif.so: No such file or directory
g++: error: ../vendor/lib/libffi.so: No such file or directory
g++: error: ../vendor/lib/libfontconfig.so: No such file or directory
g++: error: ../vendor/lib/libfreetype.so: No such file or directory
g++: error: ../vendor/lib/libgdk_pixbuf-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgif.so: No such file or directory
g++: error: ../vendor/lib/libgio-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgmodule-2.0.so: No such file or directory
g++: error: ../vendor/lib/libgsf-1.so: No such file or directory
g++: error: ../vendor/lib/libgthread-2.0.so: No such file or directory
g++: error: ../vendor/lib/libharfbuzz.so: No such file or directory
g++: error: ../vendor/lib/libjpeg.so: No such file or directory
g++: error: ../vendor/lib/liblcms2.so: No such file or directory
g++: error: ../vendor/lib/liborc-0.4.so: No such file or directory
g++: error: ../vendor/lib/libpango-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpangocairo-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpangoft2-1.0.so: No such file or directory
g++: error: ../vendor/lib/libpixman-1.so: No such file or directory
g++: error: ../vendor/lib/libpng.so: No such file or directory
g++: error: ../vendor/lib/librsvg-2.so: No such file or directory
g++: error: ../vendor/lib/libtiff.so: No such file or directory
g++: error: ../vendor/lib/libwebp.so: No such file or directory
g++: error: ../vendor/lib/libxml2.so: No such file or directory
g++: error: ../vendor/lib/libz.so: No such file or directory
sharp.target.mk:179: recipe for target 'Release/obj.target/sharp.node' failed
make: *** [Release/obj.target/sharp.node] Error 1
make: Leaving directory '/built_app/programs/server/npm/node_modules/sharp/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-93-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /built_app/programs/server/npm/node_modules/sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.20.5 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.20.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-10T06_12_12_856Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-10T06_12_12_916Z-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
[47.100.35.149] x Prepare Bundle: FAILED

              ------------------------------------STDERR------------------------------------
              The command '/bin/sh -c cd  /built_app/programs/server &&     npminstall --unsafe-perm' returned a non-zero code: 1

              ------------------------------------STDOUT------------------------------------
              ch file or directory
        g++: error: ../vendor/lib/libjpeg.so: No such file or directory
        g++: error: ../vendor/lib/liblcms2.so: No such file or directory
        g++: error: ../vendor/lib/liborc-0.4.so: No such file or directory
        g++: error: ../vendor/lib/libpango-1.0.so: No such file or directory
        g++: error: ../vendor/lib/libpangocairo-1.0.so: No such file or directory
        g++: error: ../vendor/lib/libpangoft2-1.0.so: No such file or directory
        g++: error: ../vendor/lib/libpixman-1.so: No such file or directory
        g++: error: ../vendor/lib/libpng.so: No such file or directory
        g++: error: ../vendor/lib/librsvg-2.so: No such file or directory
        g++: error: ../vendor/lib/libtiff.so: No such file or directory
        g++: error: ../vendor/lib/libwebp.so: No such file or directory
        g++: error: ../vendor/lib/libxml2.so: No such file or directory
        g++: error: ../vendor/lib/libz.so: No such file or directory
        sharp.target.mk:179: recipe for target 'Release/obj.target/sharp.node' failed
        make: *** [Release/obj.target/sharp.node] Error 1
        make: Leaving directory '/built_app/programs/server/npm/node_modules/sharp/build'
        gyp ERR! build error
        gyp ERR! stack Error: `make` failed with exit code: 2
        gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
        gyp ERR! stack     at emitTwo (events.js:125:13)
        gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
        gyp ERR! System Linux 4.4.0-93-generic
        gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
        gyp ERR! cwd /built_app/programs/server/npm/node_modules/sharp
        gyp ERR! node -v v8.4.0
        gyp ERR! node-gyp -v v3.6.2
        gyp ERR! not ok
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! sharp@0.20.5 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the sharp@0.20.5 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2018-10-10T06_12_12_856Z-debug.log
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the meteor-dev-bundle@ install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2018-10-10T06_12_12_916Z-debug.log
```

**Comment by dc165015** [comment]
it only appears while installing npm pkg sharp. Any other pkgs work fine.

**Comment by tanutapi** [comment]
Hi, I ran into the same situation. The base docker has no `libvips` which is required by Sharp installed. So I have a look into http://sharp.pixelplumbing.com/en/stable/install/#docker and copy their docker commands and add in the `buildInstructions` of `mup.js` config file.

```
module.exports = {
    ...
    docker: {
      image: 'abernix/meteord:node-8.15.1-base',
      buildInstructions: [
        'RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y automake build-essential curl cdbs debhelper dh-autoreconf flex bison libjpeg-dev libtiff-dev libpng-dev libgif-dev librsvg2-dev libpoppler-glib-dev zlib1g-dev fftw3-dev liblcms2-dev liblcms2-dev libmagickwand-dev libfreetype6-dev libpango1.0-dev libfontconfig1-dev libglib2.0-dev libice-dev gettext pkg-config libxml-parser-perl libexif-gtk-dev liborc-0.4-dev libopenexr-dev libmatio-dev libxml2-dev libcfitsio-dev libopenslide-dev libwebp-dev libgsf-1-dev libgirepository1.0-dev gtk-doc-tools',
        'RUN cd /tmp && curl -L -O https://github.com/libvips/libvips/releases/download/v8.7.4/vips-8.7.4.tar.gz && tar zxvf vips-8.7.4.tar.gz',
        'RUN cd /tmp/vips-8.7.4 && ./configure --enable-debug=no --without-python $1 && make && make install && ldconfig',
        'RUN apt-get remove -y automake curl build-essential && apt-get autoremove -y && apt-get autoclean && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*',
      ]
    },
    ...
}
```

With this you can run `mup deploy --verbose` and will successfully get your app up and running.

**Comment by dc165015** [comment]
Thanks, dude!
