### ISSUE TITLE
Verifying Deployment: FAILED

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#1037]
Mup version (`mup --1.4.5`) and Meteor 1.7.0.5

Mup config
```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '1.2.3.4',
      username: 'root',
      pem: '~/.ssh/id_rsa',
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    },
  },

  app: {
    // TODO: change app name and path
    name: 'restaurant',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://1.2.3.4,
      MONGO_URL: 'mongodb://mongodb/restaurant',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
      PORT: 9090,
    },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:node-8.4.0-base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true,
  },

  mongo: {
    version: '3.6.4',
    servers: {
      one: {},
    },
  },

  // (Optional)
  // Use the proxy to setup ssl or to route requests to the correct
  // app when there are several apps

  // proxy: {
  //   domains: 'mywebsite.com,www.mywebsite.com',

  //   ssl: {
  //     // Enable Let's Encrypt
  //     letsEncryptEmail: 'email@domain.com'
  //   }
  // }
}
```

Output of command
```bash
------------------------------------STDERR------------------------------------
                                            Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
          % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
        Container spent too much time restarting.
        => Starting meteor app on port:80
        node: symbol lookup error: /built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
        => Starting meteor app on port:80
        The service-configuration package persists configuration in the meteor_accounts_loginServiceConfiguration collection in MongoDB. As each service should have exactly one configuration, Meteor automatically creates a MongoDB index with a unique constraint on the  meteor_accounts_loginServiceConfiguration collection.The _ensureIndex command which creates that index is failing.

        Meteor versions before 1.0.4 did not create this index. If you recently upgraded and are seeing this error message for the first time, please check your meteor_accounts_loginServiceConfiguration collection for multiple configuration entries for the same service and delete configuration entries until there is no more than one configuration entry per service.

        If the meteor_accounts_loginServiceConfiguration collection looks fine, the _ensureIndex command isfailing for some other reason.

        For more information on this history of this issue, please see https://github.com/meteor/meteor/pull/3514.


        /built_app/programs/server/node_modules/fibers/future.js:313
                                                        throw(ex);
                                                        ^
        Error: write EPIPE
            at _errnoException (util.js:1041:11)
            at WriteWrap.afterWrite (net.js:858:14)
        => Starting meteor app on port:80

        /built_app/programs/server/node_modules/fibers/future.js:313
                                                        throw(ex);
                                                        ^
        MongoError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.17.0.3:27017]
            at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:505:11)
            at emitOne (events.js:115:13)
            at Pool.emit (events.js:210:7)
            at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:329:12)
            at Object.onceWrapper (events.js:318:30)
            at emitTwo (events.js:125:13)
            at Connection.emit (events.js:213:7)
            at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:245:50)
            at Object.onceWrapper (events.js:316:30)
            at emitOne (events.js:115:13)
            at Socket.emit (events.js:210:7)
            at emitErrorNT (internal/streams/destroy.js:64:8)
            at _combinedTickCallback (internal/process/next_tick.js:138:11)
            at process._tickDomainCallback (internal/process/next_tick.js:218:9)
        => Starting meteor app on port:80
        node: symbol lookup error: /built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
        => Starting meteor app on port:80
        node: symbol lookup error: /built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
        => Starting meteor app on port:80
        node: symbol lookup error: /built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
        => Starting meteor app on port:80
        node: symbol lookup error: /built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
        => Starting meteor app on port:80
        node: symbol lookup error: /built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE

              ------------------------------------STDOUT------------------------------------
              Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        Container has no IP Address, likely from the app crashing.
        => Container status:
        restarted: 8 times {"Bridge":"","SandboxID":"cae30a5c2cab1c68d99a7a8f481d34c2bd240707d64b9deb6232201a7f3e3e47","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/cae30a5c2cab","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"929791175c7dd506a8a7338742e261166c585c00d2ff46f11e90891ba3850a69","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":127,"Error":"","StartedAt":"2018-11-27T02:48:02.48671051Z","FinishedAt":"2018-11-27T02:48:09.273514843Z"}
        => Logs:

        To see more logs type 'mup logs --tail=200'


              ------------------------------------------------------------------------------
```

**Comment by keifuji** [comment]
`node: symbol lookup error: /built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE`

This seems to be the same problem as [symbol lookup error undefined symbol: ... #656](https://github.com/kelektiv/node.bcrypt.js/issues/656)

I got one and fixed it, though temporarily, by downgrading bcrypt from 3.0.2 to 3.0.0.

**Comment by thearabbit** [comment]
Very thanks, I will try soon

**Comment by thearabbit** [comment]
Work fine with use `bcrypt@3.0.0`

**Comment by mskauer** [comment]
How did you downgrade to bcrypt 3.0.0?

If I run meteor npm install bcrypt@3.0.0 I get this error

```
> bcrypt@3.0.0 install /home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.0 and node@8.15.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
make: Entering directory '/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
../src/bcrypt.cc: In function ‘void encode_salt(char*, u_int8_t*, char, u_int16_t, u_int8_t)’:
../src/bcrypt.cc:114:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 encode_salt(char *salt, u_int8_t *csalt, char minor, u_int16_t clen, u_int8_t logr)
 ^~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
../src/bcrypt.cc: In function ‘void bcrypt(const char*, const char*, char*)’:
../src/bcrypt.cc:147:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 bcrypt(const char *key, const char *salt, char *encrypted)
 ^~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.0 and node@8.15.1 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error bad download 
make: Entering directory '/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
../src/bcrypt.cc: In function ‘void encode_salt(char*, u_int8_t*, char, u_int16_t, u_int8_t)’:
../src/bcrypt.cc:114:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 encode_salt(char *salt, u_int8_t *csalt, char minor, u_int16_t clen, u_int8_t logr)
 ^~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
../src/bcrypt.cc: In function ‘void bcrypt(const char*, const char*, char*)’:
../src/bcrypt.cc:147:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 bcrypt(const char *key, const char *salt, char *encrypted)
 ^~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
../src/bcrypt_node.cc:375:30: fatal error: opening dependency file ./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt_node.o.d.raw: No such file or directory
 NODE_MODULE(bcrypt_lib, init);
                              ^
compilation terminated.
bcrypt_lib.target.mk:103: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.0.0-29-generic
gyp ERR! command "/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 5.0.0-29-generic
node-pre-gyp ERR! command "/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.2
node-pre-gyp ERR! not ok 
Failed to execute '/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node /home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
In file included from ../src/bcrypt_node.cc:1:0:
../node_modules/nan/nan.h:153:10: fatal error: nan_callbacks.h: No such file or directory
compilation terminated.
bcrypt_lib.target.mk:103: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.0.0-29-generic
gyp ERR! command "/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/maximiliano/.meteor/packages/meteor-tool/.1.8.1.ani1yi.p0f9s++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/maximiliano/Proyectos/Shippter/shippter/node_modules/bcrypt
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN moment-business-days@1.1.3 requires a peer of moment@2.x.x but none is installed. You must install peer dependencies yourself.
npm WARN shippter@ No description
npm WARN shippter@ No repository field.
npm WARN shippter@ No license field.
npm WARN The package eslint is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maximiliano/.npm/_logs/2019-10-04T15_03_20_543Z-debug.log
```

I'm using meteor 1.8.1 and mup 1.4.6

**Comment by NathanJeanDevs** [comment]
We noticed that only 3.0.0 seems to work with mup deployments. 

I suspect that it has to do with the node version used in docker image 
abernix/meteord:node-8.4.0-base

On our local machines, we cannot get bcrypt to compile with node V12.14.0 (current latest stable). 

So every time we go to deploy, we have to downgrade the bcrypt package from latest to 3.0.0

I suspect that once we are able to use a docker image for mup, that uses node V12 and above, the bcrypt version can be over 3.0.0 for future deployments.

**Comment by NathanJeanDevs** [comment]
**Update -** 
Looks like you can use bcrypt 3.0.6 with abernix/meteord:node-8.16.0-base in you mup config file.

The mup docs do not state that you can use  abernix/meteord:node-8.16.0-base, but it worked just fine for us. 

Looking into the abernix repo, it states latest version is 8.16 for meteor 1.8

[https://github.com/abernix/meteord](https://github.com/abernix/meteord)

The documentation for mup should probably be updated to include this.
