### ISSUE TITLE
mup deploy error connect etimedout

### ISSUE THREAD

**Issue by spoonfair** [zodern/meteor-up#1038]
Mup version (`mup --version`): 1.4.5

Mup config

```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem",
      "opts": {
        "port": 22
      }
    }
  },
  "app": {
    "name": "my-app",
    "path": "../../overload",
    "deployCheckWaitTime": 3600,
    "enableUploadProgressBar": true,
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://subdomain.subdomain.subdomain.host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local"
    },
    "docker": {
      "image": "abernix/meteord:node-8.4.0-base",
      "stopAppDuringPrepareBundle": true,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    }
  }
}
```

Output of command

```bash
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 18.222.236.202:22
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Emitted 'error' event at:
    at Socket.<anonymous> (C:\Users\rober\AppData\Roaming\npm\node_modules\mup\node_modules\nodemiral\node_modules\ssh2\
lib\client.js:218:10)
    at Socket.emit (events.js:187:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by spoonfair** [comment]
Meteor 1.8..0.1
Node 10.13.0

**Comment by ziedmahdi** [comment]
1. make sure when u install your node modules to use `meteor npm i` and not just `npm i`, you can delete the nod_modules folder and then run `meteor npm i`.

2. For docker image use `abernix/meteord:node-8.11.2-base` as u r using Meteor 1.8
3. I m not sure about this, but I think you don't need the `docker.args` part as the mongo container will be automatically linked by mup, so remove it.

Hope this helps.

**Comment by spoonfair** [comment]
`Building App Bundle Locally

Started TaskList: Pushing Meteor App
[18.222.XXX.XXX] - Pushing Meteor App Bundle to the Server
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 18.222.XXX.XXX:22
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
Emitted 'error' event at:
    at Socket.<anonymous> (C:\Users\rober\AppData\Roaming\npm\node_modules\mup\node_modules\nodemiral\node_modules\ssh2\
lib\client.js:218:10)
    at Socket.emit (events.js:187:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

I did all of the above, but I'm still getting the same error :/

**Comment by spoonfair** [comment]
For anyone who runs into the same problem, be sure to check your server's security group settings. I feel kinda silly for not noticing this. I recently moved and couldn't upload to server because the inbound setting was for a different IP.
