### ISSUE TITLE
"Cannot convert undefined or null to object" with any remoteCommand on Hooks

### ISSUE THREAD

**Issue by one-pereyra** [zodern/meteor-up#1063]
I have to install puppeteer dependencies but I can't run commands on the server, always returns `TypeError: Cannot convert undefined or null to object`
The hook is;
```js
  hooks: {
    "pre.meteor.build": {
      "remoteCommand": "yum install cups-libs dbus-glib libXrandr libXcursor libXinerama cairo cairo-gobject pango && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-1.el7.x86_64.rpm && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/GConf2-3.2.6-7.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libXScrnSaver-1.2.2-6.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libxkbcommon-0.3.1-1.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-client-1.2.0-3.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-cursor-1.2.0-3.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/gtk3-3.10.4-1.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/16/Fedora/x86_64/os/Packages/gdk-pixbuf2-2.24.0-1.fc16.x86_64.rpm"
    },
  },
```
Any help is much appreciated.

Meteor version : 1.8.0.2

Mup version : 1.4.5

Mup config

```js
{
  "hooks": {
    "pre.meteor.build": {
      "remoteCommand": "yum install cups-libs dbus-glib libXrandr libXcursor libXinerama cairo cairo-gobject pango && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-1.el7.x86_64.rpm && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/GConf2-3.2.6-7.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libXScrnSaver-1.2.2-6.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libxkbcommon-0.3.1-1.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-client-1.2.0-3.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-cursor-1.2.0-3.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/gtk3-3.10.4-1.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/16/Fedora/x86_64/os/Packages/gdk-pixbuf2-2.24.0-1.fc16.x86_64.rpm"
    }
  },
  "app": {
    "type": "aws-beanstalk",
    "name": "my-app",
    "path": "~/repos/pnyx18",
    "buildOptions": {
      "serverOnly": true,
      "debug": true
    },
    "auth": {
      "id": "XXXXXXXXXXXX",
      "secret": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    },
    "minInstances": 1,
    "maxInstances": 5,
    "gracefulShutdown": true,
    "instanceType": "t2.micro",
    "sslDomains": [
      "sandpit.xxxx.xxx.xx"
    ],
    "forceSSL": true,
    "region": "ap-southeast-2",
    "customBeanstalkConfig": [
      {
        "namespace": "aws:ec2:vpc",
        "option": "VPCId",
        "value": "vpc-XXXXXXXXXXXX"
      },
      {
        "namespace": "aws:ec2:vpc",
        "option": "Subnets",
        "value": "subnet-XXXXXXXXXXXX"
      },
      {
        "namespace": "aws:ec2:vpc",
        "option": "ELBSubnets",
        "value": "subnet-XXXXXXXXXXXX, subnet-XXXXXXXXXXXX, subnet-XXXXXXXXXXXX"
      }
    ],
    "env": {
      "ROOT_URL": "https://subdomain.host.com",
      "MONGO_URL": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "MONGO_OPLOG_URL": "XXXXXXXXXXXXXXXXXXXXXXXX",
      "MAIL_URL": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      "PORT": 8081,
      "METEOR_SIGTERM_GRACE_PERIOD_SECONDS": 30
    },
    "oldVersions": 3
  },
  "plugins": [
    "mup-aws-beanstalk"
  ]
}

```

Output of command
```bash
mup deploy --verbose
=> Setting up
=> Ensuring IAM Roles and Instance Profiles are setup
=> Ensuring Graceful Shutdown is setup
> Running hook meteor.build remote command "yum install cups-libs dbus-glib libXrandr libXcursor libXinerama cairo cairo-gobject pango && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/atk-2.28.1-1.el7.x86_64.rpm && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm && rpm -ivh --nodeps http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-core-2.28.0-1.el7.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/GConf2-3.2.6-7.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libXScrnSaver-1.2.2-6.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libxkbcommon-0.3.1-1.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-client-1.2.0-3.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/l/libwayland-cursor-1.2.0-3.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/20/Fedora/x86_64/os/Packages/g/gtk3-3.10.4-1.fc20.x86_64.rpm && rpm -ivh --nodeps http://dl.fedoraproject.org/pub/archive/fedora/linux/releases/16/Fedora/x86_64/os/Packages/gdk-pixbuf2-2.24.0-1.fc16.x86_64.rpm"
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at _callee$ (/usr/local/lib/node_modules/mup/lib/hooks.js:14:65)
    at tryCatch (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/mup/lib/hooks.js:43:191)
    at /usr/local/lib/node_modules/mup/lib/hooks.js:43:437
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/mup/lib/hooks.js:43:99
    at runRemoteHooks (/usr/local/lib/node_modules/mup/lib/hooks.js:35:17)
    at PluginAPI._callee$ (/usr/local/lib/node_modules/mup/lib/plugin-api.js:141:50)
    at tryCatch (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/mup/lib/plugin-api.js:73:191)
    at /usr/local/lib/node_modules/mup/lib/plugin-api.js:73:437

```

**Comment by zodern** [comment]
This should be fixed in mup 1.5.
