### ISSUE TITLE
Can't make use of localhost mongodb

### ISSUE THREAD

**Issue by ChenLi0830** [zodern/meteor-up#107]
Hi there, my app can be deployed with an external MongoDB with not problem, but I can't seem to make it work using the local MongoDB. 

I tried two Ubuntu 14.0.4 servers and got the same error from them. Here is my error message:

```
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/bundle/bundle/programs/server/node_modules/fibers/future.js:300
                        throw(ex);
                              ^
Error: failed to connect to [localhost:27017]
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:420:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[101.201.77.89]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:102:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:158:9)
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)
```

And here is my mup.js file:

```
module.exports = {
  servers: {
    one: {
      host: '101.201.77.***',
      username: '******',
      password: '******',
    },
  },

  meteor: {
    name: 'Octokey',
    path: './',
    servers: {
      one: {},
    },
    env: {
      ROOT_URL: 'http://101.201.77.***',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    deployCheckWaitTime: 300,
    enableUploadProgressBar: true    
  },
};
```

However, the deployment will work If I change the MONGO_URL to  `mongodb://username:password@dds-2ze12732d9cbd8442.mongodb.rds.aliyuncs.com:3717/dbName`

**Comment by kayrules** [comment]
if you don't specify the port, it will use 27017 as default. try check if the server is listening to the port.

```
$ netstat -na |grep 27017
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN
```

**Comment by madushan1000** [comment]
You should implement `meteor.mongo` section in `mup.js` for mongo to install.

**Comment by ChenLi0830** [comment]
@madushan1000 Thanks, after including the mongo part, it seems the app can connect to mongo now. However, I got another issue. Here is the error log

```
[101.200.130.199]Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
[101.200.130.199]    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
[101.200.130.199]    at Module._compile (module.js:456:26)
[101.200.130.199]    at Object.Module._extensions..js (module.js:474:10)
[101.200.130.199]    at Module.load (module.js:356:32)
[101.200.130.199]    at Function.Module._load (module.js:312:12)
[101.200.130.199]    at Module.require (module.js:364:17)
[101.200.130.199]    at require (module.js:380:17)
[101.200.130.199]    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[101.200.130.199]    at Module._compile (module.js:456:26)
[101.200.130.199]    at Object.Module._extensions..js (module.js:474:10)
[101.200.130.199]npm WARN deprecated This version of npm lacks support for important features,
[101.200.130.199]npm WARN deprecated such as scoped packages, offered by the primary npm
[101.200.130.199]npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[101.200.130.199]npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[101.200.130.199]npm WARN deprecated 
[101.200.130.199]npm WARN deprecated   npm -g install npm@latest-2
[101.200.130.199]npm WARN deprecated 
[101.200.130.199]npm WARN deprecated To upgrade to the latest stable version, run:
[101.200.130.199]npm WARN deprecated 
[101.200.130.199]npm WARN deprecated   npm -g install npm@latest
[101.200.130.199]npm WARN deprecated 
[101.200.130.199]npm WARN deprecated (Depending on how Node.js was installed on your system, you
[101.200.130.199]npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[101.200.130.199]npm WARN deprecated on Windows, run them from an Administrator prompt.)
[101.200.130.199]npm WARN deprecated 
[101.200.130.199]npm WARN deprecated If you're running the version of npm bundled with
[101.200.130.199]npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[101.200.130.199]npm WARN deprecated will be bundled with a version of npm@2, which has some small
[101.200.130.199]npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[101.200.130.199]npm WARN deprecated semver behavior.
[101.200.130.199]npm WARN package.json meteor-dev-bundle@0.0.0 No description
[101.200.130.199]npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[101.200.130.199]npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[101.200.130.199]=> Starting meteor app on port:80
[101.200.130.199]
[101.200.130.199]/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
[101.200.130.199]   throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
[101.200.130.199]         ^
[101.200.130.199]Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
[101.200.130.199]    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
[101.200.130.199]    at Module._compile (module.js:456:26)
[101.200.130.199]    at Object.Module._extensions..js (module.js:474:10)
[101.200.130.199]    at Module.load (module.js:356:32)
[101.200.130.199]    at Function.Module._load (module.js:312:12)
[101.200.130.199]    at Module.require (module.js:364:17)
[101.200.130.199]    at require (module.js:380:17)
[101.200.130.199]    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[101.200.130.199]    at Module._compile (module.js:456:26)
[101.200.130.199]    at Object.Module._extensions..js (module.js:474:10)

```

Here is my current mup.js file

```
module.exports = {
  servers: {
    one: {
      host: '101.200.130.199',
      username: '******',
      password: '******',
      // pem: './mykey',
    },
  },

  meteor: {
    name: 'Octokey',
    path: './',
    servers: {
      one: {},
    },
    env: {
      ROOT_URL: 'http://101.200.130.199',
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    deployCheckWaitTime: 300,
    enableUploadProgressBar: true    
  },

  mongo: { //optional
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by ChenLi0830** [comment]
Thanks @kayrules, after setting the mongo config in the mup.js file, the server is listening to the port now.

**Comment by madushan1000** [comment]
This is a known issue with meteor 1.3.x. Take a look at meteorhacks/meteord issues section.

**Comment by ChenLi0830** [comment]
@madushan1000 Thanks for the reply. I tried to search for "fibers.node` is missing" but can't seem to find the same issue in meteord's issues...

**Comment by MasterJames** [comment]
Does not meteor 1.3.2.2 an official update make this go away now?

**Comment by ChenLi0830** [comment]
@MasterJames is it? Trying it now.

**Comment by ChenLi0830** [comment]
@MasterJames Man you saved my life!
It's pretty confusing to me where this is mentioned though. I couldn't find it anywhere even in meteor's [History file](https://github.com/meteor/meteor/blob/devel/History.md). 
Anyway, I am so glad this is solved. It bothered me for days. 💃

**Comment by MasterJames** [comment]
Others waited longer I'm sure, and so that just dropped in the week I believe. Your post will help others now too., to spread the word and the love for meteor 1.3.2.2 ! I think the deal is it rebuilds all npm packages etc. It's been part of a bigger problem for sometime and one of the major changes to 1.3 it just took a while to sort out the fiber errors once and for all, I think, hopefully.
