### ISSUE TITLE
Deploying Meteor App-Mlab failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by MahmoudMousaHamad** [zodern/meteor-up#1071]
Mup version (`1.4.5`):

Mup config

```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "mahmoud",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../gym",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://subdomain.host.com",
      "MONGO_URL": "mongodb://user:pass@subdomain.host.com/test?retryWrites=true",
      "PORT": 3000
    },
    "docker": {
      "image": "abernix/meteord:node-8.4.0-base",
      "stopAppDuringPrepareBundle": true
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  }
}
```

Output of command

```bash
Error: failed to connect to server [cluster0-rohl6.mongodb.net:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND cluster0-rohl6.mongodb.net cluster0-rohl6.mongodb.net:27017]
            at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
            at emitOne (events.js:115:13)
            at Pool.emit (events.js:210:7)
            at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
            at Object.onceWrapper (events.js:318:30)
            at emitTwo (events.js:125:13)
            at Connection.emit (events.js:213:7)
            at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
            at Object.onceWrapper (events.js:316:30)
            at emitOne (events.js:115:13)
            at Socket.emit (events.js:210:7)
            at emitErrorNT (internal/streams/destroy.js:64:8)
            at _combinedTickCallback (internal/process/next_tick.js:138:11)
            at process._tickDomainCallback (internal/process/next_tick.js:218:9)
a```

**Comment by MahmoudMousaHamad** [comment]
Solved. The issue was with MONGO_URL. I had to do it in the following format: 

`"MONGO_URL": "mongodb://user:pass@cluster0-shard-00-00-AAAA.mongodb.net:27017,cluster0-shard-00-01-AAAA.mongodb.net:27017,cluster0-shard-00-02-AAAA.mongodb.net/database?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin",`
