### ISSUE TITLE
help me please ！！！

### ISSUE THREAD

**Issue by nikonikoCW** [zodern/meteor-up#1076]
D:\meteor_demo\cww\.deploy>mup.cmd setup --verbose

Started TaskList: Setup Docker
[my_IP] - Setup Docker
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED （my_IP）:22
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
Emitted 'error' event at:
    at Socket.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\mup\node_modules\nodemiral\node_modules\ssh2\lib\client.js:218:10)
    at Socket.emit (events.js:194:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by zodern** [comment]
Are you able to ssh into the server? Tr running `ssh -i <path to pem file> username@ipAddress`. For example `ssh -i ./private_key root@12.3.4`. If you are using a password, it would be `ssh user@ipAddress`.

**Comment by nikonikoCW** [comment]
> 你能进入服务器吗？Tr跑`ssh -i <path to pem file> username@ipAddress`。例如`ssh -i ./private_key root@12.3.4`。如果您使用的是密码，那就是`ssh user@ipAddress`。

Thank you for your reply, I have solved it.
