### ISSUE TITLE
beta.2. MongoError: database names cannot contain the character '.'

### ISSUE THREAD

**Issue by jamesgibson14** [zodern/meteor-up#1084]
When I revert to Beta1 the deploy and start up work fine.

**Comment by jamesgibson14** [comment]
I have found that using this image: `abernix/meteord:node-8-base` work with the latest mup version without errors.

**Comment by zodern** [comment]
@jamesgibson14 does your app name have a `.`? What Meteor version are you using?

**Comment by jamesgibson14** [comment]
No it doesn't, I thought the abernix image solved the problem but when I tested with beta-2 again the same problem was there. I am using a MongoDB Atlas URL as the mongo_url. And it has all kinds of dots, dashes, etc.

**Comment by zodern** [comment]
Could you please run `mup validate --show` and `mup meteor status` and check that the MONGO_URL looks correct?

**Comment by jamesgibson14** [comment]
I just verified again: Beta1 worked. Beta.2: 
`Error: slash in host identifier
            at parseConnectionString (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:201:15)
            at parseHandler (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:112:14)
            at module.exports (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/url_parser.js:97:5)
            at connect (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:485:3)
            at Function.MongoClient.connect (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:250:3)
            at new MongoConnection (packages/mongo/mongo_driver.js:168:11)
            at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
            at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
            at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
            at new Mongo.Collection (packages/mongo/collection.js:99:40)
        => Starting meteor app on port:3000
        /built_app/programs/server/node_modules/fibers/future.js:280
                                                        throw(ex);
                                                      `

`{
  "servers": {
    "a": {
      "host": "111.111.111.111",
      "username": "root",
      "pem": "~/.ssh/id_rsa"
    }
  },
  "app": {
    "name": "concord",
    "path": "../../",
    "servers": {
      "a": {
        "env": {
          "SERVER_NAME": "concord-stage"
        }
      }
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "https://sub.domain.com",
      "MONGO_URL": "mongodb://user.password@name-shard-00-00-name.mongodb.net:27017/:27017,name-shard-00-01-name.mongodb.net:27017,name-shard-00-02-code.mongodb.net/bsbstage?ssl=true&replicaSet=name-shard-0&authSource=admin",
      "MONGO_OPLOG_URL": "mongodb://user:password@name-shard-00-00-code.mongodb.net:27017,name-shard-00-01-code.mongodb.net:27017,name-shard-00-02-code.mongodb.net:27017/local?ssl=true&replicaSet=name-shard-0&authSource=admin"
    },
    "docker": {
      "image": "abernix/meteord:node-8-base",
      "stopAppDuringPrepareBundle": true,
      "imagePort": 3000
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  }
}`
 
The status says restarting and the mongo_url looks good. although it obviously has many different special characters, I don't know it needs to be wrapped in quotes.

**Comment by jamesgibson14** [comment]
I reverted back to Beta1 again and it deployed just fine

**Comment by jamesgibson14** [comment]
I am using beta.4 and have not had this issue any more

**Comment by jamesgibson14** [comment]
I was wrong, I don't have many deploys using proxy, but when I do then I still get this error and I have to deploy,reconfig with mup 1.4.6 instead of the beta.4

**Comment by zodern** [comment]
This is fixed in Mup 1.5.
