### ISSUE TITLE
Verifying Deployment Failed

### ISSUE THREAD

**Issue by godadada** [zodern/meteor-up#1087]
Hey,

  I have rust/ffi inside my meteor project. It chocked during mup/'Verifying Deployment' phase.
I know I had to use nodejs v12 in my meteor project to accommodate ffi. The latest node version for meteord is nodejs v8. I wonder if the nodejs version is the root of the failure.
Please shade light.

Mup version (`mup --version`): 1.4.6

Mup config
module.exports = {
  plugins: [ "mup-mariadb" ],
  mariadb: {
    version: 'latest',
    databaseName: "app",
    port: 3307,
    databaseUser: "root",
    userPassword: "secretpw",
    customConfig: "~/.my.cnf",
    sqlDumpFile: "~/proj/doc/sql/app.sql",
    servers: {
        one: {}
    }
  },
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '192.168.1.200',
      username: 'user',
      //pem: '.ssh/id_rsa.pem'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'App',
    path: '../',

    type: 'meteor',
    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'https://www.app.com',
      //MONGO_URL: 'mongodb://mongodb/meteor',
      //MONGO_OPLOG_URL: 'mongodb://mongodb/local',
    },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:node-8.4.0-base',
      prepareBundle: false
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true,

  },

  // (Optional)
  // Use the proxy to setup ssl or to route requests to the correct
  // app when there are several apps

  proxy: {
     domains: 'app.com,www.app.com',

     ssl: {
       // Enable Let's Encrypt
     letsEncryptEmail: 'user@host.com'
    }
  }
};

```js
paste config here...
```

Output of command

```bash
paste output here...
```
[192.168.1.200] - Verifying Deployment
[192.168.1.200] x Verifying Deployment: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      l to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
	gyp ERR! configure error 
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
	gyp ERR! stack     at emitTwo (events.js:125:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 4.18.0-20-generic
	gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /bundle/bundle/programs/server/npm/node_modules/pg-native/node_modules/libpq
	gyp ERR! node -v v8.4.0
	gyp ERR! node-gyp -v v3.6.2
	gyp ERR! not ok 
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! libpq@1.8.7 install: `node-gyp rebuild`

**Comment by godadada** [comment]
Got new error after adding dockerImage: "guillim/meteord" to mup.js

[192.168.1.200] x Verifying Deployment: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      ontDelete));
	        ^
	../src/ffi.cc:125:175: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../../nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
	   Nan::ForceSet(target,Nan::New<String>("FFI_TYPE_SIZE").ToLocalChecked(), Nan::New<Uint32>((uint32_t)sizeof(ffi_type)), static_cast<PropertyAttribute>(ReadOnly | DontDelete));
	                                                                                                                                                                               ^
	../src/ffi.cc:126:8: warning: 'Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)' is deprecated (declared at ../../nan/nan_maybe_43_inl.h:130) [-Wdeprecated-declarations]
......
