### ISSUE TITLE
Verifying Deployment: FAILED, port 80: Connection refused

### ISSUE THREAD

**Issue by nwabdou85** [zodern/meteor-up#1119]
I want to deploy meteor react app for the first time on EC2 instance but I got an issue in the deployment process if any one can help, please; 

here bellow all the information may you need; 

Mup version (`mup --version`): 6.9.0
Meteor version (`meteor --version`): 1.8.1

Mup config

```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '*.*.*.*',
      username: 'ubuntu',
      pem: '../../Downloads/****.pem',
      opts: {
        port: 22
      }
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {  
    // TODO: change app name and path
    name: 'elqoufa',
    path: '../elqoufaoff',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://15.188.23.216',
      MONGO_URL:'mongodb://*****:****@127.0.0.1:27017/?authSource=*****=mongodb',
    },
    deployCheckWaitTime: 800,
    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'zodern/meteor:root',
      prepareBundle:true,
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  // mongo: {
  //   version: '3.4.1',
  //   servers: {
  //     one: {}
  //   }
  // },

  // (Optional)
  // Use the proxy to setup ssl or to route requests to the correct
  // app when there are several apps

  // proxy: {
  //   domains: 'mywebsite.com,www.mywebsite.com',

  //   ssl: {
  //     // Enable Let's Encrypt
  //     letsEncryptEmail: 'email@domain.com'
  //   }
  // }
};

```

Output of command

```bash
- Start Meteor
using image
Error: No such image: mup-elqoufa:previous
Image mup-elqoufa:latest
Volume
Removing docker containers. Errors about nonexistent endpoints and containers are normal.
Error: No such container: elqoufa
Error response from daemon: endpoint elqoufa not found
Error: No such container: elqoufa-frontend
Error response from daemon: endpoint elqoufa-frontend not found
Error: No such container: elqoufa-nginx-letsencrypt
Error response from daemon: endpoint elqoufa-nginx-letsencrypt not found
Error: No such container: elqoufa-nginx-proxy
Error response from daemon: endpoint elqoufa-nginx-proxy not found
Finished removing docker containers
0f830065e78d65ac269f3744eec97abc227d71be5366c062130540a9fbd21125
Ran zodern/meteor:root
 - Start Meteor: SUCCESS
 - Verifying Deployment
Container has no IP Address, likely from the app crashing.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
Container has no IP Address, likely from the app crashing.
Container has no IP Address, likely from the app crashing.
Container has no IP Address, likely from the app crashing.
Container has no IP Address, likely from the app crashing.
Container has no IP Address, likely from the app crashing.
Container has no IP Address, likely from the app crashing.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
Container has no IP Address, likely from the app crashing.
Container has no IP Address, likely from the app crashing.
Container has no IP Address, likely from the app crashing.
Container spent too much time restarting.
=> Container status:
restarted: 8 times {"Bridge":"","SandboxID":"6d703f81a280fc577fc66e1432cc58c5186bb71b6a61d0","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/6d703f81a2d6","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"430f3de10f9e77bf14ef290beab3efc843b84ffb4320e30a088fee0b612cc786","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":1,"Error":"","StartedAt":"2020-01-09T12:44:59.527539038Z","FinishedAt":"2020-01-09T12:45:02.029282627Z"}
=> Logs:
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
=> Setting node version
NODE_VERSION=8.11.3
v8.11.3 is already installed.
Now using node v8.11.3 (npm v5.6.0)
Now using node v8.11.3 (npm v5.6.0)
=> Starting meteor app on port 80
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
/built_app/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
=> Setting node version
NODE_VERSION=8.11.3
v8.11.3 is already installed.
Now using node v8.11.3 (npm v5.6.0)
Now using node v8.11.3 (npm v5.6.0)
=> Starting meteor app on port 80
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
/built_app/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
=> Setting node version
NODE_VERSION=8.11.3
v8.11.3 is already installed.
Now using node v8.11.3 (npm v5.6.0)
Now using node v8.11.3 (npm v5.6.0)
=> Starting meteor app on port 80
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
/built_app/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

To see more logs type 'mup logs --tail=200'

x Verifying Deployment: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      core/lib/topologies/server.js:564:11)
	    at emitOne (events.js:116:13)
	    at Pool.emit (events.js:211:7)
	    at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
	    at Object.onceWrapper (events.js:317:30)
	    at emitTwo (events.js:126:13)
	    at Connection.emit (events.js:214:7)
	    at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
	    at Object.onceWrapper (events.js:315:30)
	    at emitOne (events.js:116:13)
	    at Socket.emit (events.js:211:7)
	    at emitErrorNT (internal/streams/destroy.js:64:8)
	    at _combinedTickCallback (internal/process/next_tick.js:138:11)
	    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
	=> Setting node version
	NODE_VERSION=8.11.3
	v8.11.3 is already installed.
	Now using node v8.11.3 (npm v5.6.0)
	Now using node v8.11.3 (npm v5.6.0)
	=> Starting meteor app on port 80
	Note: you are using a pure-JavaScript implementation of bcrypt.
	While this implementation will work correctly, it is known to be
	approximately three times slower than the native implementation.
	In order to use the native implementation instead, run
	
	  meteor npm install --save bcrypt
	
	in the root directory of your application.
	/built_app/programs/server/node_modules/fibers/future.js:313
							throw(ex);
							^
	
	MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
	    at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
	    at emitOne (events.js:116:13)
	    at Pool.emit (events.js:211:7)
	    at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
	    at Object.onceWrapper (events.js:317:30)
	    at emitTwo (events.js:126:13)
	    at Connection.emit (events.js:214:7)
	    at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
	    at Object.onceWrapper (events.js:315:30)
	    at emitOne (events.js:116:13)
	    at Socket.emit (events.js:211:7)
	    at emitErrorNT (internal/streams/destroy.js:64:8)
	    at _combinedTickCallback (internal/process/next_tick.js:138:11)
	    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
	=> Setting node version
	NODE_VERSION=8.11.3
	v8.11.3 is already installed.
	Now using node v8.11.3 (npm v5.6.0)
	Now using node v8.11.3 (npm v5.6.0)
	=> Starting meteor app on port 80
	Note: you are using a pure-JavaScript implementation of bcrypt.
	While this implementation will work correctly, it is known to be
	approximately three times slower than the native implementation.
	In order to use the native implementation instead, run
	
	  meteor npm install --save bcrypt
	
	in the root directory of your application.
	/built_app/programs/server/node_modules/fibers/future.js:313
							throw(ex);
							^
	
	MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
	    at Pool.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
	    at emitOne (events.js:116:13)
	    at Pool.emit (events.js:211:7)
	    at Connection.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
	    at Object.onceWrapper (events.js:317:30)
	    at emitTwo (events.js:126:13)
	    at Connection.emit (events.js:214:7)
	    at Socket.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
	    at Object.onceWrapper (events.js:315:30)
	    at emitOne (events.js:116:13)
	    at Socket.emit (events.js:211:7)
	    at emitErrorNT (internal/streams/destroy.js:64:8)
	    at _combinedTickCallback (internal/process/next_tick.js:138:11)
	    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
	
	      ------------------------------------STDOUT------------------------------------
	      Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	=> Container status:
	restarted: 8 times {"Bridge":"","SandboxID":"6d703f81a2d62628a7f39d5e2f5180fc577fc66e1432cc58c5186bb71b6a61d0","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/6d703f81a2d6","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"430f3de10f9e77bf14ef290beab3efc843b84ffb4320e30a088fee0b612cc786","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":1,"Error":"","StartedAt":"2020-01-09T12:44:59.527539038Z","FinishedAt":"2020-01-09T12:45:02.029282627Z"}
	=> Logs:
	
	To see more logs type 'mup logs --tail=200'
	
	

```

**Comment by zodern** [comment]
Your app isn't able to connect to MongoDB. Are you running MongoDB on the same server?

**Comment by nwabdou85** [comment]
@zodern , yes the are on the same server; 
Do you think the problem come from this ?

**Comment by nwabdou85** [comment]
@zodern I'm still waiting

**Comment by nexthazard** [comment]
Having same problem with local Mongo... i keep getting the error that i need to update npm to version 12 or later using default docker container. not sure how to access the ymal ro change this.
