### ISSUE TITLE
How to deploy on my windows local machine?

### ISSUE THREAD

**Issue by Frustrated-Programmer** [zodern/meteor-up#1141]
Attempting to host a meteor app on my local machine, so I can kinda do: `localhost:3000` and connect to it. I was recommended using `mup` for deploying the meteor app.
Running `mup setup` gives me the following error:
```
Started TaskList: Setup Docker
[192.168.0.128] - Setup Docker
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.0.128:22
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
Emitted 'error' event on Client instance at:
    at Socket.<anonymous> (C:\Users\Elijah\AppData\Roaming\npm\node_modules\mup\node_modules\nodemiral\node_modules\ssh2\lib\client.js:218:10)
    at Socket.emit (events.js:323:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.0.128',
  port: 22,
  level: 'client-socket'
}
```

My `mup.js` file is:

```
module.exports = {
  servers: {
    one: {
      host: '192.168.0.128',
      username: 'elijah',
      password: 'test'
    }
  },
  app: {
    name: 'RandoName',
    path: '../',
    docker: {
      image: 'abernix/meteord:base'
    },
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true
    },
    env: {
      ROOT_URL: 'http://192.168.0.128',
      MONGO_URL: 'mongodb://localhost/meteor'
    }
  },
  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```

I could supply my settings.json, but from what I saw on #841 (which is doing exactly what I want todo just mine is for Windows and his is for Mac) Its not needed. 

Also based on the #841 I assume I need to get a password for my machine's ssh root account, but how do I get that?  I've tried my user account's password.(which is admin) And google wasn't much help. 

I'm not even sure I'm headed down the right path even. Maybe I'm just stupid and forgot a step. Either way can you help?

**Comment by Frustrated-Programmer** [comment]
I was able to deploy my app without using mup. So this isn't as important anymore. But the issue still remains as I couldn't figure out how to deploy while using mup.

**Comment by lepathie** [comment]
Having same issue but on WSL.

**Comment by lepathie** [comment]
Is there no way to just generate a local Dockerfile/Container?

**Comment by Frustrated-Programmer** [comment]
2 years later... tried to use mup again, am having this EXACT issue. Same logs exactly... does mup not work on local machines? I am so confused why I wouldn't...
