### ISSUE TITLE
`meteor build` failed on `mup deploy`

### ISSUE THREAD

**Issue by iNextAB** [zodern/meteor-up#1259]
I am running the `Github Action` to build and deploy a meteor Application to the `AWS EC2 instance`.

I am using the following code in the `.yaml` file to do the ` mup deploy`

```
- name: mup deploy
  run: cd meteor-api/.deploy/staging && mup deploy
```

But I am receiving this **error message** below -

```
cd meteor-api/.deploy/staging && mup deploy
  shell: /usr/bin/bash -e {0}
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[13.xx.xxx.xxx] - Pushing Meteor App Bundle to the Server
[13.xx.xxx.xxx] - Pushing Meteor App Bundle to the Server: SUCCESS
[13.xx.xxx.xxx] - Prepare Bundle
[13.xx.xxx.xxx] x Prepare Bundle: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      The command '/bin/sh -c cd /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	
	real	0m50.418s
	user	0m2.073s
	sys	0m1.441s
	
	      ------------------------------------STDOUT------------------------------------
	      -regexp-constructors@0.4.3 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-transform-regexp-constructors
	babel-plugin-transform-remove-console@6.9.4 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-transform-remove-console
	babel-plugin-transform-remove-debugger@6.9.4 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-transform-remove-debugger
	babel-plugin-transform-remove-undefined@0.5.0 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-transform-remove-undefined
	babel-plugin-transform-simplify-comparison-operators@6.9.4 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-transform-simplify-comparison-operators
	babel-plugin-transform-undefined-to-void@6.9.4 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/babel-plugin-transform-undefined-to-void
	meteor-babel-helpers@0.0.3 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel-helpers
	reify@0.20.12 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify
	acorn@6.4.2 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/acorn
	acorn-dynamic-import@4.0.0 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/acorn-dynamic-import
	magic-string@0.25.7 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/magic-string
	sourcemap-codec@1.4.8 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/sourcemap-codec
	semver@5.7.1 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node_modules/semver
	typescript@4.3.2 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/typescript
	json5@2.1.1 /built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/json5
	
	> core-js@3.14.0 postinstall /built_app/programs/server/npm/node_modules/meteor/url/node_modules/core-js
	> node -e "try{require('./postinstall')}catch(e){}"
	
	core-js@3.14.0 /built_app/programs/server/npm/node_modules/meteor/url/node_modules/core-js
	
	> bcrypt@5.0.1 install /built_app/programs/server/npm/node_modules/meteor/accounts-password/node_modules/bcrypt
	> node-pre-gyp install --fallback-to-build
	
	/built_app/programs/server/npm/node_modules/meteor/accounts-password/node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:78
	function Run({ package_json_path = './package.json', argv }) {
	             ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/accounts-password/node_modules/@mapbox/node-pre-gyp/lib/main.js:9:22)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! bcrypt@5.0.1 install: `node-pre-gyp install --fallback-to-build`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the bcrypt@5.0.1 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2021-08-15T18_57_00_612Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the meteor-dev-bundle@ install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2021-08-15T18_57_00_649Z-debug.log
	
	      ------------------------------------------------------------------------------
	      
Error: Process completed with exit code 1.
```

Does anyone know any solution to this challenge, I am not a developer and trying to solve this problem for the past 15 days?

**Comment by iNextAB** [comment]
Anyone, please try to look at the issue, please?

**Comment by ivanhoe89** [comment]
I have the same problem when I am running 'mup setup' then 'mup deploy' under linux.
Is there anyone who maybe who could help here?
