### ISSUE TITLE
TypeError path must be a string

### ISSUE THREAD

**Issue by mbabauer** [zodern/meteor-up#126]
I am using the following setup:

```
module.exports = {
  servers: {
    one: {
      host: 'sc1.32past8.com',
      username: 'xxx',
      password: 'xxx',
      // pem: './mykey',
    },
  },

  meteor: {
    name: 'strata_app',
    path: '../../',
    servers: {
      one: {},
    },
    env: {
      ROOT_URL: 'https://sc1.32past8.com',
      MAIL_URL: "smtp://postmaster@app.strataconsulting.us:f3cb14d9e0fd3a2d73dd6be808fe52fc@smtp.mailgun.org",
      MONGO_URL: 'mongodb://localhost/meteor'
    },
    ssl: {
      certificate: "./fullchain1.pem",
      key: "./privkey1.key",
      port: 443
    }
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

```

Which I placed in `.deploy/dev`, but I am getting an error when I run `mup setup`:

```
Started TaskList: Setup Docker
[sc1.32past8.com] - setup docker
[sc1.32past8.com] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[sc1.32past8.com] - Setup Environment

Started TaskList: Setup Mongo
[sc1.32past8.com] - setup environment
[sc1.32past8.com] - setup environment: SUCCESS
[sc1.32past8.com] - copying mongodb.conf
[sc1.32past8.com] - Setup Environment: SUCCESS
[sc1.32past8.com] - Copying SSL Certificate Bundle
TypeError path must be a string
```

Also, is there any way to turn on debug logging?

**Comment by MasterJames** [comment]
That's weird. Make sure it's all single quotes and try a full path to see if that's the problem and then look at the file itself but the error says the path is wrong.

**Comment by mbabauer** [comment]
Ok, I made sure everything was using single quotes, and even tried full path, but same issue.  I added a log to dump the stack on error, but that seemed less than helpful:

```
Started TaskList: Setup Docker
[sc1.32past8.com] - setup docker
[sc1.32past8.com] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[sc1.32past8.com] - Setup Environment

Started TaskList: Setup Mongo
[sc1.32past8.com] - setup environment
[sc1.32past8.com] - setup environment: SUCCESS
[sc1.32past8.com] - copying mongodb.conf
[sc1.32past8.com] - Setup Environment: SUCCESS
[sc1.32past8.com] - Copying SSL Certificate Bundle
TypeError path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.open (fs.js:575:11)
    at fastXfer (/Users/mbauer/Documents/development/oss_projects/meteor-up/node_modules/ssh2-streams/lib/sftp.js:1008:7)
    at SFTPStream.fastPut (/Users/mbauer/Documents/development/oss_projects/meteor-up/node_modules/ssh2-streams/lib/sftp.js:1111:3)
    at SFTPWrapper.fastPut (/Users/mbauer/Documents/development/oss_projects/meteor-up/node_modules/ssh2/lib/SFTPWrapper.js:52:23)
    at onSftp (/Users/mbauer/Documents/development/oss_projects/meteor-up/node_modules/nodemiral/lib/ssh.js:43:12)
    at SFTPStream.onReady (/Users/mbauer/Documents/development/oss_projects/meteor-up/node_modules/ssh2/lib/client.js:741:9)
    at SFTPStream.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at SFTPStream.emit (events.js:179:7)
    at SFTPStream._transform (/Users/mbauer/Documents/development/oss_projects/meteor-up/node_modules/ssh2-streams/lib/sftp.js:340:14)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/mbauer/Documents/development/oss_projects/meteor-up/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
```

One thing I find strange is that the SSL log output is printing after the line "Started TaskList: Setup Mongo", but the code seems to add the step as part of the Meteor module setup (lines 45-62 of src/modules/meteor/index.js).  Not sure why, perhaps threading?

**Comment by mbabauer** [comment]
Ok, I found it.  The config variable is called `crt` now, not `certificate`.  However, I am not getting the same issue as #109.
