### ISSUE TITLE
Mup Deploy error on Apple Silicon (M1) 

### ISSUE THREAD

**Issue by appigram** [zodern/meteor-up#1284]
Mup version (`mup --version`): 1.5.5

I am running the **mup deploy** as usual on Macbook M1 chip (Meteor 2.5.1 or 2.5.2-betas with Apple M1 chip support)

But I am receiving this error message below

```bash
Cleaning Up Previous Builds
Building App Bundle Locally
/Users/appigram/.meteor/packages/meteor-tool/.2.5.1.1t0zdzb.asmeh++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: missing tool for os.osx.x86_64 in meteor-tool@2.5.2-beta.8
    at springboard (/tools/cli/main.js:504:11)
    at /tools/cli/main.js:1165:7

=> Build Error. Check the logs printed above.
```

It works in Rosetta terminal, but it will be very helpful to specify architecture to build release in the next versions like mup deploy arch=x86_64 or something else

**Comment by dmitri-vlasov** [comment]
@appigram hey! Evgeny, was you able to resolve this issue? I have pretty much same when compiling meteor-dev for Rocket.Chat in `/.meteor/packages/meteor-tool/.2.10.0.dsqtfm.q3sdq++os.osx.arm64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.arm64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js`

<img width="1085" alt="Снимок экрана 2023-02-13 в 20 54 54" src="https://user-images.githubusercontent.com/8647677/218521822-937dc29c-8db3-4aa2-a6bd-2b899e4c02a1.png">
