### ISSUE TITLE
mup setup error: timed out while waiting for handshake

### ISSUE THREAD

**Issue by willemx** [zodern/meteor-up#1287]
I am trying to use mup on my mac (MacOS 10.15.7) to setup my meteor app on a ubuntu 16.04 server, but mup throws an error:

Mup version (`1.5.5`):

Mup config
```js
module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'xxxxx',
      password: 'xxxxx'
    }
  },
  app: {
    name: 'appname',
    path: '../',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://appname.nl',
      MONGO_URL: 'mongodb://xxx@xxx:27017/xxx?appName=appname',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
    },
    docker: {
      image: 'zodern/meteor:root',
    },
    enableUploadProgressBar: true
  },
  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  },
};
```

Output of command
```bash
Started TaskList: Setup Docker
[1.2.3.4] - Setup Docker
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/usr/local/lib/node_modules/mup/node_modules/ssh2/lib/client.js:695:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on Client instance at:
    at Timeout._onTimeout (/usr/local/lib/node_modules/mup/node_modules/ssh2/lib/client.js:697:14)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  level: 'client-timeout'
}
```
The username and password are correct; I can ssh into the server manually using these...

**Comment by willemx** [comment]
I decided to stop trying to get mup working.
