### ISSUE TITLE
[Error]: Startup cancelled. Please run the app using the [run.sh] script from the project folder

### ISSUE THREAD

**Issue by jankapunkt** [zodern/meteor-up#1290]
Meteor release: 2.5

Mup version (`mup --version`): 1.5.5

Mup config

```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "root"
    }
  },
  "hooks": {},
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true,
      "buildLocation": "/tmp/mup-meteor-e04aa66b-8f97-465f-8bd5-99446c60d532",
      "cleanBuildLocation": true
    },
    "env": {
      "ROOT_URL": "https://subdomain.host.com",
      "MONGO_URL": "mongodb://mongodb:port/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local",
      "MAIL_URL": "smtp://user:pw@host:port",
      "HTTP_FORWARDED_COUNT": 1,
      "port": 3000,
      "VIRTUAL_HOST": "subdomain.host.com",
      "HTTPS_METHOD": "redirect",
      "LETSENCRYPT_HOST": "subdomain.host.com",
      "LETSENCRYPT_EMAIL": "email@domain.com",
      "VIRTUAL_PORT": 3000
    },
    "docker": {
      "image": "zodern/meteor:latest",
      "prepareBundle": true,
      "useBuildKit": true,
      "stopAppDuringPrepareBundle": true,
      "imagePort": 3000,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    },
    "dbName": "my-app"
  },
  "proxy": {
    "domains": "subdomain.host.com",
    "ssl": {
      "forceSSL": true,
      "letsEncryptEmail": "email@domain.com"
    },
    "clientUploadLimit": "50M"
  }
}

```

Output of command

```bash
[1.2.3.4]=> Setting node version
[1.2.3.4]NODE_VERSION=14.18.1
[1.2.3.4]v14.18.1 is already installed.
[1.2.3.4]Now using node v14.18.1 (npm v6.14.15)
[1.2.3.4]default -> 14.18.1 (-> v14.18.1 *)
[1.2.3.4]=> Starting meteor app on port 3000
[1.2.3.4]-------------------------------------------------------------------------------------------------
[1.2.3.4]
[1.2.3.4][FATAL]: startup cancelled. Please run the app using the [run.sh] script from the project folder.
[1.2.3.4]
[1.2.3.4]-------------------------------------------------------------------------------------------------
[1.2.3.4]/built_app/programs/server/node_modules/fibers/future.js:280
[1.2.3.4]                                                throw(ex);
[1.2.3.4]                                                ^
[1.2.3.4]
[1.2.3.4]Error
[1.2.3.4]    at module (imports/startup/server/environment.js:9:9)
[1.2.3.4]    at fileEvaluate (packages/modules-runtime.js:336:7)
[1.2.3.4]    at Module.require (packages/modules-runtime.js:238:14)
[1.2.3.4]    at Module.moduleLink [as link] (/built_app/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime/index.js:52:22)
[1.2.3.4]    at module (server/main.js:1:66)
[1.2.3.4]    at fileEvaluate (packages/modules-runtime.js:336:7)
[1.2.3.4]    at Module.require (packages/modules-runtime.js:238:14)
[1.2.3.4]    at require (packages/modules-runtime.js:258:21)
[1.2.3.4]    at /built_app/programs/server/app/app.js:3300:15
[1.2.3.4]    at /built_app/programs/server/boot.js:401:38
[1.2.3.4]    at Array.forEach (<anonymous>)
[1.2.3.4]    at /built_app/programs/server/boot.js:226:21
[1.2.3.4]    at /built_app/programs/server/boot.js:464:7
[1.2.3.4]    at Function.run (/built_app/programs/server/profile.js:280:14)
[1.2.3.4]    at /built_app/programs/server/boot.js:463:13
```

This happens after Meteor has started, at verification deployment stage.

**Comment by jankapunkt** [comment]
Nevermind, it was an error during my application startup which I simply did not see at a first glance.
