### ISSUE TITLE
Error: Couldn't find preset "es2015"

### ISSUE THREAD

**Issue by g41n** [zodern/meteor-up#140]
Hello to all, I'm following the readme and after cloning when I run npm install I have the error:

```
✔ ~/meteor/meteor-up [master|✔] 
17:44 $ npm install

> mup@1.0.0 prepublish /home/user/meteor/meteor-up
> nofat make

/home/user/meteor/meteor-up/node_modules/nofat/tasks/make/index.js:45
        throw err;
        ^

Error: Couldn't find preset "stage-3" relative to directory "/home/user/meteor/meteor-up/src"
    at /home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:387:20)
    at OptionManager.mergePresets (/home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:10)
    at OptionManager.mergeOptions (/home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:14)
    at OptionManager.init (/home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
    at File.initOptions (/home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at /home/user/meteor/meteor-up/node_modules/nofat/node_modules/babel-core/lib/api/node.js:126:18

npm ERR! Linux 3.16.0-71-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! mup@1.0.0 prepublish: `nofat make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mup@1.0.0 prepublish script 'nofat make'.
npm ERR! This is most likely a problem with the mup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nofat make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls mup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/meteor/meteor-up/npm-debug.log
```

Here there is the [npm-debug.log.zip](https://github.com/kadirahq/meteor-up/files/305151/npm-debug.log.zip)

Am I missing something?

**Comment by ayushchd** [comment]
Here: https://github.com/kadirahq/meteor-up/issues/98#issuecomment-224679540

**Comment by g41n** [comment]
I've updated to npm3 (nodejs 6.2.1), as @madushan1000 said in [#98](https://github.com/kadirahq/meteor-up/issues/98#issuecomment-224793648), and `npm install` presents 2 warnings but works:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use
 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

Than `npm link` not works at first but running with `sudo` solved it.

Every `mup` command has this line as output, hope is not a problem:

```
(node:1398) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

Anyway `mup deploy` fails with this output:

```
(node:1996) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Building App Bundle Locally
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/pdfmake.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/vfs_fonts.js" as it exceeds the max of "100KB".
Error If encoding is specified then the first argument must be a string
```

Now I'll try with @maruns steps, as said by @ayushchd, and let you know...

**Comment by g41n** [comment]
Sadly no success, with @maruns steps the behaviour is the the same.
I've also tried to follow @maruns steps with the LTS version of node (actually 4.4.5) and the result is the one I've pasted in the first comment...

**Comment by madushan1000** [comment]
I think these two lines are coming from the `meteor build` command we use under the hood to build the meteor bundle. 

```
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/pdfmake.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/vfs_fonts.js" as it exceeds the max of "100KB".
Error If encoding is specified then the first argument must be a string
```

**Comment by g41n** [comment]
Updating Meteor from 1.2.1 to 1.3.2.4 (and many of the libraries) make it works.

Thank you for the support.

PS: I was stuck on 1.2.1 due to a library and npm compatibility, now it's time to solve that if I want to use this mup version, but that's another story.... ;)

**Comment by hamz250** [comment]
Worked for me by 
npm install --save-dev npm install babel-cli babel-preset-es2015 babel-preset-stage-3
