### ISSUE TITLE
PhantomJS ? 

### ISSUE THREAD

**Issue by RemyLespagnol** [zodern/meteor-up#170]
Hi,

It is possible to have PhantomJS pre-installed with meteor up ?
Or how to install it in the container ? 

Because I want to use spiderable and I have this error when I want to cache a page : 
`spiderable: phantomjs failed at http://picturals.com/login?%3F_escaped_fragment_=: Error: Command failed:
[163.172.154.215]    at ChildProcess.exithandler (child_process.js:658:15)
[163.172.154.215]    at ChildProcess.emit (events.js:98:17)
[163.172.154.215]    at maybeClose (child_process.js:766:16)
[163.172.154.215]    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
[163.172.154.215]stderr:
[163.172.154.215]stdout:
`

Regards,
Rémy.

**Comment by madushan1000** [comment]
Build a new docker image with PhantomJS dependencies installed using the `meteorhacks/meteord` base image push it to the docker registry, and set it as the docker image in mup.js file

**Comment by RemyLespagnol** [comment]
I will try this, and let you know if I succeed :+1: 
Thanks.

**Comment by RemyLespagnol** [comment]
Sorry, I forgot to reply to this post.
I wanted PhantomJS to use Spiderable, but I switch to prenreder.io, so I don't need PhantomJS anymore.

Thanks for your help :+1:
