### ISSUE TITLE
Cannot find module 'ssh2' on running mup commands

### ISSUE THREAD

**Issue by betharavikiran** [zodern/meteor-up#184]
I started seeing the below error on my windows 10 machine from morning. The commands were running fine until yesterday. I checked on a different windows 10 machine and saw the same error. 

Please advise to to resolve this.

mup setup
Error: Cannot find module 'ssh2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/utils.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/index.js:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by BastianWe** [comment]
hey,
you have to install ssh2.

```
npm install -g ssh2
```

**Comment by Tbutnyakov** [comment]
Or you can install it with global parameter.
in console: npm install -g ssh2

**Comment by betharavikiran** [comment]
I have installed ssh2, but the problem continues. please advise.

**Comment by Tbutnyakov** [comment]
@betharavikiran you set it to the global "-g" setting ?

**Comment by betharavikiran** [comment]
Hi,

after installing with -g option on console, i stopped seeing the ssh2
module missing error.
But, i realise that i am stuck between the older version of mup and the new
one. The version i was using until yesterday was generating mup.json file.

But what is confusing is that it was working for me until today morning and
then i started to see the ssh2 error.

I will try to configure the new mup and see if i can get it to work.

Thank you for your prompt replies. will keep you posted.

**Comment by Tbutnyakov** [comment]
Today package was updated. 
New version of package generate a strange mup.js file, that can't run, cause it have a few errors. I created a issue about it and...still wait for answer from KadiraTeam:)

https://github.com/kadirahq/meteor-up/issues/185

**Comment by betharavikiran** [comment]
aha, thanks. should i indicate to kadira team if their update is breaking
older version too, in know they already indicated that they dont support it.

**Comment by betharavikiran** [comment]
i also stuck with the same issue, looks like the mup process is not doing anything becoz it cannt process module.exports

let me know if you could get past as I am also using windows

**Comment by Tbutnyakov** [comment]
@betharavikiran ok! Hope guys from kadira will answer soon.

**Comment by afuggini** [comment]
I'm having problems too, I even run `mup` alone and get nothing. Is everyone having this issue too?

**Comment by Tbutnyakov** [comment]
@afuggini you asking  about "ssh2"? Or "meteor setup" problem?

**Comment by afuggini** [comment]
@Tbutnyakov I used to have the ssh2 issue until I run `npm install -g ssh2`. However I still cannot run mup at all, it doesn't do anything.

**Comment by Tbutnyakov** [comment]
@afuggini yep, you are not alone:)
I created a issue: https://github.com/kadirahq/meteor-up/issues/185

**Comment by madushan1000** [comment]
If you need the older mup version, install it using `npm install -g mup@0.x.x`. It's no longer supported and the new version is not backward compatible.

**Comment by sonuterrific** [comment]
I have the problem, I installed ssh2 by "npm install -g ssh2". but still receiving the same error.

 $ mup
Error: Cannot find module 'ssh2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/utils.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/index.js:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
$

**Comment by betharavikiran** [comment]
switch to mupx

**Comment by thegreatredfox** [comment]
mupx doesn't work for Meteor 1.4.x 
I installed ssh2 globally and then copied the folder inside the global mup/node_modules folder.
ssh2 is a devDependency and doesn't get install with mup.

**Comment by discdiver** [comment]
upgraded mup to 1.04 on mac os sierra. 
Then got 

> Error: Cannot find module 'ssh2'

 when tried to run mup deploy.

> npm install -g ssh2

 fixed the issue.
