### ISSUE TITLE
"Redeploying previous version of the app" ?

### ISSUE THREAD

**Issue by DiesIrae** [zodern/meteor-up#199]
When I get deploying errors, like everyone else, I get "Redeploying previous version of the app". I wonder what it means!

Every time the app stays down and the previous version don't get launched. When I then try `mup start`, it tries to start the one in error, not the previous one as I thought seeing this message. Is it a global (and somewhat normal?) behavior?

Thanks for this excellent tool by the way.

**Comment by madushan1000** [comment]
Yeah, that's normal behaviour, if the deployment fails, mup tries to deploy the old version.

**Comment by DiesIrae** [comment]
But is it normal that it fails to redeploy it every time?

**Comment by madushan1000** [comment]
IF you don't have a previous version, it's fine. But otherwise it's a problem. Do you have any logs?

**Comment by DiesIrae** [comment]
I have a previous version, so there's a bug somewhere. Here are some logs, when I put for example a bad mongoUrl (but the behavior is for any error):

```
$ mup deploy                                                                                                                         10:39:21
Building App Bundle Locally

Started TaskList: Pushing Meteor
[engine.matcha.wine] - Pushing Meteor App Bundle to The Server
[engine.matcha.wine] - Pushing Meteor App Bundle to The Server: SUCCESS
[engine.matcha.wine] - Pushing the Startup Script
[engine.matcha.wine] - Pushing the Startup Script: SUCCESS
{}

Started TaskList: Configuring  Meteor Environment Variables
[engine.matcha.wine] - Sending Environment Variables
[engine.matcha.wine] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[engine.matcha.wine] - Start Meteor
[engine.matcha.wine] - Start Meteor: SUCCESS
[engine.matcha.wine] - Verifying Deployment
[engine.matcha.wine] x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        all.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
            at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
            - - - - -
            at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:295:35)
            at emitOne (events.js:77:13)
            at [object Object].emit (events.js:169:7)
            at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:251:12)
            at [object Object].g (events.js:260:16)
            at emitTwo (events.js:87:13)
            at [object Object].emit (events.js:172:7)
            at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:150:49)
            at Socket.g (events.js:260:16)
            at emitOne (events.js:77:13)

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------

```

I'm on node 6.3.1, mup 1.0.2, but it has always been the same, even with previous versions.

**Comment by asafshen** [comment]
@DiesIrae same stderr for me..

did you have any advice? 
thanks

**Comment by Endtry** [comment]
Is there a fix for this issue? I am having the exact same error on my deploy using kadirahq/meteor-up with node 4.5.0 on Amazon EC2
