### ISSUE TITLE
mup deploy failed

### ISSUE THREAD

**Issue by stephane-r** [zodern/meteor-up#214]
Hi,

After `mup init` and `mup setup` server success with Meteor up, i run `mup deploy` and it fail at Verifying Deployment: FAILED :

```
-----------------------------------STDERR-----------------------------------
    node-gyp rebuild

    make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build'
      CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
      CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
      SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
      COPY Release/bcrypt_lib.node
    make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build'
    bcrypt@0.8.7 /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt
    bindings@1.2.1 /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bindings
    nan@2.3.5 /bundle/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/nan

    > buffertools@2.1.4 install /bundle/bundle/programs/server/npm/node_modules/bufferstream/node_modules/buffertools
    > node-gyp rebuild
```

I use Digital Ocean server on Ubuntu 14.04. I've install Node v4.4.7 and node-gyp.

If i run node-gyp rebuild, i've this error :

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Can you help me ?

**Comment by estebanutz** [comment]
@LeG3nDz Have you tried upgrading your local version of "npm-bcrypt" I was experiencing the same issues and upgrading to the latest version fixed it for me. "meteor update npm-bcrypt"

**Comment by xanatas** [comment]
Info:
According to the README, this implementation is approximately 2.7 times
slower than native: https://www.npmjs.com/package/bcryptjs

Apps that wish to continue using the native bcrypt package should run
`meteor npm install --save bcrypt` in the root application directory, and
the npm-bcrypt package will prefer that implementation.

**Comment by adammoisa** [comment]
I did that and still get this issue. Any ideas?
