### ISSUE TITLE
Another case of "x Verifying Deployment: FAILED"

### ISSUE THREAD

**Issue by martinhbramwell** [zodern/meteor-up#217]
Here's what I am seeing : 

```
you@yourpc:~/projects/meteor-mantra-kickstarter$ mup deploy --settings=settings.json
Building App Bundle Locally

[yourhost.yourpublic.work] - Pushing Meteor App Bundle to The Server: SUCCESS
[yourhost.yourpublic.work] - Pushing the Startup Script
[yourhost.yourpublic.work] - Pushing the Startup Script: SUCCESS
{ HOST_URI: 'localhost:3000',
  MAILGUN_DOMAIN: 'yourpublic.work',
  MAILGUN_KEY: 'key-23412342345523453245234532452345',
  LOGGLY_SUBDOMAIN: 'yourwork',
  LOGGLY_TOKEN: '78472f82-5dc9-phock-awff-9399c1b5d82e',
  public: 
   { PASSWORD_RESET: 
      { Route: '/prrq/',
        Html_1: '<b>If you did not request a password reset just ignore this.</b><br /><b>If you did request it, then please click <a href=\'http://',
        Html_2: '\'>this link</a> to open your password reset page.',
        Text_1: 'If you did not request a password reset just ignore this.\nIf you did request it, then please go to http://',
        Text_2: ' in order to reset your password.',
        Subject: 'Your Mantra Kickstarter password reset request',
        From: 'yourself@yourpublic.work' } } }

Started TaskList: Configuring  Meteor Environment Variables
[yourhost.yourpublic.work] - Sending Environment Variables
[yourhost.yourpublic.work] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[yourhost.yourpublic.work] - Start Meteor
[yourhost.yourpublic.work] - Start Meteor: SUCCESS
[yourhost.yourpublic.work] - Verifying Deployment
[yourhost.yourpublic.work] x Verifying Deployment: FAILED

  -----------------------------------STDERR-----------------------------------
  package.json meteor-dev-bundle@0.0.0 No description
  npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
  npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
  => Starting meteor app on port:80

  assert.js:93
    throw new assert.AssertionError({
          ^
  AssertionError: "undefined" === "function"
      at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
      at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Module.require (module.js:364:17)
      at require (module.js:380:17)
      at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
      at Module._compile (module.js:456:26)

  => Redeploying previous version of the app

  -----------------------------------STDOUT-----------------------------------

  To see more logs type 'mup logs --tail=50'

  ----------------------------------------------------------------------------
```

My mup.js looks like this : 

```
module.exports = {
  servers: {
    one: {
      host: 'yourhost.yourpublic.work',
      username: 'yourself'
    }
  },

  meteor: {
    name: 'meteor-mantra-kickstarter',
    path: '../meteor-mantra-kickstarter',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: false,
      debug: true
    },
    env: {
      PORT: 3000,
      ROOT_URL: 'https://yourhost.yourpublic.work',
      MONGO_URL: 'mongodb://localhost:27017/meteor'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 240,
    enableUploadProgressBar: true
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by martinhbramwell** [comment]
Ok, I got past this problem after finding this : 

[[1.4] mup: errors in production (AssertionError: "undefined" === "function")](https://github.com/meteor/meteor/issues/7475#issuecomment-235229269)
