### ISSUE TITLE
Error: Cannot find module './lib'

### ISSUE THREAD

**Issue by lanmower** [zodern/meteor-up#234]
node 4.4.7, ubuntu, downloaded from git, ran install, prepublish and link
# mup

module.js:327
    throw err;
    ^

Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/bin/mup:2:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

what can I try to resolve this?

**Comment by lanmower** [comment]
it runs without error with the index.js directly from the path, which is currently saving ability to deploy

**Comment by snajjar** [comment]
Hi,

Use docker image abernix/meteord:base for deployment instead of the default one from kadirahq (i don't know why it still isn't fixed). It will install the right node version (4.4.7) in the meteord container.

**Comment by elie222** [comment]
Did you work this out @lanmower? I'm having the same issue.

**Comment by elie222** [comment]
I just found the solution:
https://github.com/kadirahq/meteor-up/issues/95

**Comment by lanmower** [comment]
With dev copy npm run prepublish produces that path and it's contents
