### ISSUE TITLE
AssertionError: "undefined" === "function"

### ISSUE THREAD

**Issue by softwarerero** [zodern/meteor-up#243]
With mup 1.0.3 trying to deploy a Meteor 1.4.0.1 app to Ubuntu 16.04. `mup setup` works fine but `mup deploy` fails and leaves this in the logs:

```
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
[159.203.97.65]npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
[159.203.97.65]npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[159.203.97.65]=> Starting meteor app on port:80
[159.203.97.65]
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
```

**Comment by wolganens** [comment]
Try to run:
`npm update mup -g`
and then, in your mup.js
`meteor: {
.....
.....
docker: {
      image:'abernix/meteord:base'//optional
    },
dockerImage: 'abernix/meteord:base',
}`
Of course you don't need to specify docker image twice, but i don't know, what way is working. Sorry about my english, hope you can solve that.

**Comment by softwarerero** [comment]
Thank you, I think it was `docker: { image:'abernix/meteord:base' }`that did the trick.

**Comment by fidergo-stephane-gourichon** [comment]
Bug is not actually closed as long as people continue to run into problems.
Current README.md says `docker: { image: ...` is optional.

      image: 'kadirahq/meteord', // (optional)
      // image: 'abernix/meteord:base', // use this image if using Meteor 1.4+
      args:[ // lets you add/overwrite any parameter on the docker run command (optional)
