### ISSUE TITLE
Error: Cannot find module 'ssh2' on mup init on Fedora release 16

### ISSUE THREAD

**Issue by blackslate** [zodern/meteor-up#247]
Is meteor-up supported on Red Hat Linux?

```
# cat /etc/redhat-release 
Fedora release 16 (Verne)
```

Following the [ReadMe instructions](https://github.com/kadirahq/meteor-up/blob/master/README.md), I cd into the meteor app folder and run the following commands:

```
#mkdir .deploy
# cd .deploy
# mup init
```

Result:

```
Error: Cannot find module 'ssh2'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/madushan/mup/src/utils.js:5:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/madushan/mup/src/index.js:7:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

I check that ssh2 is installed:

```
# ls -al /usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/
total 32
drwxr-xr-x 8 nobody root 4096 Aug 25 16:58 .
drwxr-xr-x 7 nobody root 4096 Aug 25 16:58 ..
drwxr-xr-x 3 nobody root 4096 Aug 25 16:58 async
drwxr-xr-x 3 nobody root 4096 Aug 25 16:58 colors
drwxr-xr-x 3 nobody root 4096 Aug 25 16:58 debug
drwxr-xr-x 6 nobody root 4096 Aug 25 16:58 ejs
drwxr-xr-x 3 nobody root 4096 Aug 25 16:58 progress
drwxr-xr-x 7 nobody root 4096 Aug 25 16:58 ssh2
```

**Comment by madushan1000** [comment]
You might need to update to npm3

**Comment by blackslate** [comment]
npm is already at version 3

```
npm -version
3.10.3
```

**Comment by thegreatredfox** [comment]
I installed ssh2 globally and then copied the ssh2 folder into the global mup/node_modules folder.

It seems ssh2 is a devDependency and doesn't install automatically.
