### ISSUE TITLE
Deploy with SSL impossible

### ISSUE THREAD

**Issue by CrackedBeefcake** [zodern/meteor-up#257]
Cant setup a `ssl` encrypted meteor app. I tried using `mup` and `mupx` but both dont work. I played with the `mup.js` files and tried all kinds of config.  I used  `dockerImage: 'kadirahq/meteord'` and `dockerImage: 'abernix/meteord:base'`. 

```

module.exports = {
  servers: {
    one: {
      host: '138.68.68.xx',
      username: 'root'
    }
  },

  meteor: {
    ssl:{
      ssl:'ssl/ssl.pem',
      port: 443
    },
    name: 'app',
    path: '../app',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'https://app.sx',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

```

But there is allways a problem.
right now that error is:

```

Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Error response from daemon: No such container: app-frontend
    docker: Error response from daemon: driver failed programming external connectivity on endpoint app-frontend (394e2a991178b6a05404a00d5b6b7aca1dfbbab065bf5f21fa0f2b10fea7a862): Bind for 0.0.0.0:443 failed: port is already allocated.
```

**Comment by stefanve** [comment]
You have ssl:'ssl/ssl.pem',
should it not be crt: ...

**Comment by stefanve** [comment]
I am struggling with ssl too, different problems though, but on the remote machine you need to go in and stop the frontend, and probably the app as well
docker stop [appname]-frontend
docker stop [appname]

I hope you find a way, but with letsencrypt it seem hopeless. That worked fine with mupx

**Comment by CrackedBeefcake** [comment]
I tried that. Didnt work.
I created the `.pem` with `cat fullchain.pem privkey.pem > ssl.pm`. befor that i used`certificate` and `key`

Also the errors i get are mostly related to`ports` beeing used already.

**Comment by CrackedBeefcake** [comment]
And for the docker: I killed every process that came with `docker ps`. still the same error.

**Comment by CrackedBeefcake** [comment]
@stefanve can you deploy your app with `mupx` and `ssl`? If so, could you share your `mup.json`?

**Comment by stefanve** [comment]
I can, but only meteor < 1.4

**Comment by stefanve** [comment]
```
`{
  "servers": [
    {
      "host": "localhost",
      "username": "aaa",
      "password": "xxx",

      "env": {}
    }
  ],
  "setupMongo": true,
  "appName": "killer-app",
  "app": "/home/user/source",
  "ssl": {

    "certificate": "/etc/letsencrypt/live/domain.com/fullchain.pem",
    "key":"/etc/letsencrypt/live/domain.com/privkey.pem",
    "port": 443
  },

  "env": {
    "PORT": 80,
    "ROOT_URL": "https://domain.com"
  },
  "deployCheckWaitTime": 60,
  "enableUploadProgressBar": false
}`
```

**Comment by CrackedBeefcake** [comment]
Downgraded to `1.3.5.1`, `mupx deploy`. [it works](https://s-media-cache-ak0.pinimg.com/564x/27/0d/2d/270d2d8be0c7ea06e8ecf73586b698fc.jpg)

**Comment by dr-dimitru** [comment]
Try this for `mup.js`

``` js
module.exports = {
  servers: {
    one: {
      "host": "0.0.0.0", // Change to your address
      "username": "sshLogin",
      "password": "sshPass"
    },
  },
  meteor: {
    name: 'appNameCamelCase',
    path: '../../',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true
    },
    dockerImage: 'abernix/meteord:base', // This image should work
    ssl: {
       crt: 'ssl.pem', // Change to your ssl
       key: 'ssl.pem', // Change to your ssl
       port: 443
     },
  },
};
```

**Comment by CrackedBeefcake** [comment]
```
Finns:App Finn$ mup init
Finns:App Finn$ mup setup

Started TaskList: Setup Docker
[138.68.68.xxx] - setup docker
[138.68.68.xxx] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[138.68.68.xxx] - Setup Environment
[138.68.68.xxx] - Setup Environment: SUCCESS
[138.68.68.xxx] - Copying SSL Certificate Bundle
[138.68.68.xxx] - Copying SSL Certificate Bundle: SUCCESS
[138.68.68.xxx] - Copying SSL Private Key
[138.68.68.xxx] - Copying SSL Private Key: SUCCESS
[138.68.68.xxx] - Verifying SSL Configurations
[138.68.68.xxx] - Verifying SSL Configurations: SUCCESS
Finns:App Finn$ mup deploy
Building App Bundle Locally
Finns:App Finn$
```

Now the process just dies quietly.

This is the `mup.js` file

```
module.exports = {
  servers: {
    one: {
      host: '138.68.68.xxx',
      username: 'root'
      // I have SSH set up globally.
    }
  },

  meteor: {
    name: 'App',
    path: '../App',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    dockerImage: 'abernix/meteord:base',
    deployCheckWaitTime: 60,
    ssl: {
      crt: 'ssl/ssl.pem', 
      key: 'ssl/ssl.pem',
      port: 443
    }
  },
};

```

**Comment by dr-dimitru** [comment]
Could you check its logs?

**Comment by dr-dimitru** [comment]
May be you need to switch to mupx from mup..

**Comment by dr-dimitru** [comment]
Also I've found https://github.com/kadirahq/meteor-up/issues/189 related to silent quit

**Comment by CrackedBeefcake** [comment]
```
Finns:App Finn$ DEBUG=* mup deploy
  mup:module:default exec => mup deploy +0ms
  mup:module:meteor exec => mup meteor deploy +1ms
  mup:module:meteor exec => mup meteor push +2ms
Building App Bundle Locally
FinnS:App  Finn$
```

And when I try to access the `mup logs`:

```
[46.101.198.xxx]Error: No such container: App
```

**Comment by CrackedBeefcake** [comment]
In #https://github.com/kadirahq/meteor-up/issues/189 the issue is his `ssh .pem` file. I dont have that. My `ssh` is global.

**Comment by dr-dimitru** [comment]
It's ump logs, where is app (node.js) logs?

**Comment by CrackedBeefcake** [comment]
This is what happens when i try with `mupx`:

```

Finns:App Finn$ mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[46.101.198.xxx] - Installing Docker
[46.101.198.xxx] - Installing Docker: SUCCESS
[46.101.198.xxx] - Setting up Environment
[46.101.198.xxx] - Setting up Environment: SUCCESS
[46.101.198.xxx] - Copying MongoDB configuration
[46.101.198.xxx] - Copying MongoDB configuration: SUCCESS
[46.101.198.xxx] - Installing MongoDB
[46.101.198.xxx] - Installing MongoDB: SUCCESS
[46.101.198.xxx] - Copying SSL certificate bundle
[46.101.198.xxx] - Copying SSL certificate bundle: SUCCESS
[46.101.198.xxx] - Copying SSL private key
[46.101.198.xxx] - Copying SSL private key: SUCCESS
[46.101.198.xxx] - Verifying SSL configurations
[46.101.198.xxx] - Verifying SSL configurations: SUCCESS
Finns-MBP-4:App Finn$ mupx deploy

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Meteor app path    : /Users/finnfrotscher/Code/App
Using buildOptions : {}

Started TaskList: Deploy app 'App' (linux)
[46.101.198.zzz] - Uploading bundle
[46.101.198.zzz] - Uploading bundle: SUCCESS
[46.101.198.zzz] - Sending environment variables
[46.101.198.zzz] - Sending environment variables: SUCCESS
[46.101.198.zzz] - Initializing start script
[46.101.198.zzz] - Initializing start script: SUCCESS
[46.101.198.zzz] - Invoking deployment process
[46.101.198.zzz] - Invoking deployment process: SUCCESS
[46.101.198.zzz] - Verifying deployment
[46.101.198.zzz] x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------

    npm WARN deprecated semver behavior.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)
    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
Finns:App Finn$ mup logs --tail=50
[46.101.198.cc]=> Starting meteor app on port:80
[46.101.198.cc]    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

```

**Comment by dr-dimitru** [comment]
This issue is in docs:

> Q) I get an deploy verification error with logs like below (Similar to issue 88)
> 
> Verifying Deployment: FAILED
> 
> Error:
> -----------------------------------STDERR-----------------------------------
>  run:
> npm WARN deprecated
> npm WARN deprecated   npm -g install npm@latest
> npm WARN deprecated
> A) Try increasing the value of deployCheckWaitTime field in mup.js file.

**Comment by dr-dimitru** [comment]
Not actually sure if it's related
is `ecmascript` package in `.meteor/packages` file?

**Comment by CrackedBeefcake** [comment]
yes

**Comment by CrackedBeefcake** [comment]
trying with `deployCheckWaitTime: 180,`

**Comment by CrackedBeefcake** [comment]
How do i get the Node logs you asked about?

> It's ump logs, where is app (node.js) logs?

**Comment by dr-dimitru** [comment]
> How do i get the Node logs you asked about?

Idk, I don't use mup :)))

**Comment by dr-dimitru** [comment]
Should be in a docs I believe

**Comment by CrackedBeefcake** [comment]
With deployCheckWaitTime: 180 on mupx:

```
x Verifying deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)

    => Redeploying previous version of the app
```

**Comment by CrackedBeefcake** [comment]
and `mup` still just silently dies on `Building App Bundle Locally`

**Comment by CrackedBeefcake** [comment]
the Docs say 'mup logs`

**Comment by dr-dimitru** [comment]
This issue should be fixed by image with node v4.\* 
see: https://github.com/arunoda/meteor-up/issues/1091#issuecomment-238806157

**Comment by dr-dimitru** [comment]
> the Docs say 'mup logs`

No idea as I said, I have little experience with mup, and I just don't like it. As it doesn't make things simpler, but opposite.
Ask @arunoda ...

And take a look on: https://github.com/kadirahq/meteor-up/issues/172

**Comment by CrackedBeefcake** [comment]
You deploy by hand?

**Comment by dr-dimitru** [comment]
By two :)

Kind of by hands - simple shell script do the thing
Some of the hosts is checking git once a day and upgrade itself

**Comment by CrackedBeefcake** [comment]
Since I had A LOT!! of problems with mup i'll probably finally start to deploy without it. 
I never did that (thats just a tiny bit out of my league...)
do you have some guides or tutorials i could start with?

**Comment by dr-dimitru** [comment]
Simple: 
`meteor build` -> `rsync archive to remote` -> `tar -xvf ..` -> `rsync to app's dir`
And serve/start/manage with Phusion Passenger (_with build-in nginx_)

**Comment by CrackedBeefcake** [comment]
ok thanks. i will do that. with both hands :D

**Comment by dr-dimitru** [comment]
[This gist](https://gist.github.com/dr-dimitru/ed7b0cc77ea627a06c9af1f791699eda) should point you to the right direction

**Comment by zeroasterisk** [comment]
mup deploys working for me w/ SSL (though I'm going to recommend the ability to customize the nginx docker image - see #284 #285)

troubleshooting:
1. Make sure your `ROOT_URL` has `https` and is accurate.
2. Review your crt/pem & key files and permissions - are they copied to the server?
3. Re-run `mup setup` after editing ssl config & cert files
4. Try ssh-ing into the server and you might need to run docker commands to cleanup broken tests (bonus, you can restart the frontend without a re-deploy)

```
docker ps
docker kill myapp-dummy-http-server-for-ssl-check 
docker rm myapp-dummy-http-server-for-ssl-check 
docker restart myapp-frontend
```

here's my ssl config, FWIW

```
    ssl: {
      port: 443,
      crt: 'wildcard.pem',
      key: 'wildcard.key',
    },
```

**Comment by Tusharsb** [comment]
After failing on mup for a few hours, i ended up using Amazon's Elastic Load Balancer to run my meteor app behind SSL reverse proxy

**Comment by zeroasterisk** [comment]
I thought AWS ELB would not support websocket... Are you failing over to Ajax long polling under the hood?

**Comment by Tusharsb** [comment]
Thanks for pointing @zeroasterisk 
Indeed websocket was failing in Browser Console. Following the advice of https://www.built.io/blog/websockets-on-aws-s-elb I have now moved from http/https layer to TCP layer of AWS ELB - now websocket works successfully but I am no longer able to see the IP of visitors. 

I think I will follow advice of @FinnFrotscher at https://gist.github.com/dr-dimitru/ed7b0cc77ea627a06c9af1f791699eda#gistcomment-1864313 and try `mupx-letsencrypt`

**Comment by CrackedBeefcake** [comment]
I still recommend `mupx-letsencrypt`.

**Comment by edemaine** [comment]
Regarding the original error, I had the same issue until I realized that stud was running from an execution of the old form of mup.  I had to remove it by deleting `/usr/local/bin/stud` and `/etc/init/stud.conf`.  Now I can successfully bind to port 443 -- or at least that message is gone.
