### ISSUE TITLE
mup error

### ISSUE THREAD

**Issue by sonuterrific** [zodern/meteor-up#270]
Am recieving following error while trying mup command.
I installed ssh2 module by "npm install -g ssh2" but still getting the same error.

$ mup
Error: Cannot find module 'ssh2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/utils.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/index.js:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by DanielSmon** [comment]
Hi @sonuterrific, I'm able to get around that by installing ssh2 globally:
`npm install -g ssh2`

But after that I get an error executing meteor build:
`{ [Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\WINDOWS\\system32\\cmd.exe',
  path: 'C:\\WINDOWS\\system32\\cmd.exe',
  spawnargs:
   [ '/c',
     'meteor',
     'build',
     '--directory',
     'C:\\tmp\\eb9cc1c1-2dae-47f2-a8d7-2522e188ad3e',
     '--architecture',
     'os.linux.x86_64',
     '--server',
     'http://localhost:3000',
     '--server-only' ] }`

Same error on Ubuntu:
`{ [Error: spawn meteor ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs:
   [ 'build',
     '--directory',
     '/tmp/f11de5b5-f46e-4b68-83d2-7cc7e2b5d9ca',
     '--architecture',
     'os.linux.x86_64',
     '--server',
     'http://localhost:3000',
     '--server-only' ] }`

Does it work for you after installing ssh2?

**Comment by DanielSmon** [comment]
Ah, solved my build problem. I had the wrong path in mup.js. #225 talks about this. Because I'm in .deploy, I just used "../" for my meteor path and it's okay now.

As for the ssh2 issue, should that be a dependency on the mup package so that it automatically installs?

**Comment by sonuterrific** [comment]
Well @DanielSmon  the problem is solved, I  used mupx instead of mup.
Everything is working fine after installing mupx.
Install mupx by using "npm install -g mupx" command.

**Comment by thegreatredfox** [comment]
@sonuterrific Are you using Meteor 1.4+ ?
