### ISSUE TITLE
mupx deploy, verifying error

### ISSUE THREAD

**Issue by sonuterrific** [zodern/meteor-up#272]
Am getting the following Verifying error...

```
**x Verifying deployment: FAILED**

    -----------------------------------STDERR-----------------------------------
    package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

```

**Comment by derek-fong** [comment]
@sonuterrific 

https://github.com/arunoda/meteor-up/issues/1091
