### ISSUE TITLE
Error: Cannot find module '../'

### ISSUE THREAD

**Issue by gsabran** [zodern/meteor-up#275]
I'm trying to upgrade to `meteor 1.4`. I've updated mup to 1.0.3, upgraded Meteor and added

```
    docker: {
      image: 'abernix/meteord:base',
    },
```

to my mup config under meteor. I'm not getting the error

```
Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/meteorhacks_kadira-binary-deps/node_modules/.bin/node-pre-gyp:15:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

I don't really know where this is coming from, maybe because my app path is `../` but that could be so many other things. My mup config looks like

``` js
{
  servers: {
    staging: {
      host: 'someIp',
      username: 'ubuntu',
      pem: 'pathToSSHKey.pem',
    },
  },
  meteor: {
    name: 'mydomain',
    path: '../',
    servers: {
      staging: {},
    },
    env: {
      ROOT_URL: 'https://mydomain.com',
      MONGO_URL: 'mongodb://...',
      NODE_ENV: 'production',
    },
    deployCheckWaitTime: 150,
    enableUploadProgressBar: true,
    docker: {
      image: 'abernix/meteord:base',
    },
    ssl: {
      crt: 'pathToBundle.crt',
      key: 'pathToSecret.key',
      port: 443,
    },
  },
}
```

**Comment by gsabran** [comment]
Removing the package `meteorhacks:kadira-profiler` fixed the issue...

**Comment by s7dhansh** [comment]
<del>For me it was meteorhacks:picker. So meteorhacks packages are using something that is causing problem. As of now, no idea what.</del>

False alarm on picker. For me too it was momentjs:moment 2.15.2. 2.15.1 works great. The reason is pointed out by @cesarve77 .
I fixed it by using moment via npm. The code is more modular now.

**Comment by cesarve77** [comment]
For me has  momentjs:moment. It need's fsevents@1.0.14 packged which throw the error.

```

> fsevents@1.0.14 install /bundle/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

module.js:327
    throw err;
   ^

Error: Cannot find module '../'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/momentjs_moment/node_modules/fsevents/node_modules/.bin/node-pre-gyp:15:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)


```
