### ISSUE TITLE
Cannot find module 'ssh2'

### ISSUE THREAD

**Issue by mixcas** [zodern/meteor-up#276]
Installed `mup` just after installing node/npm and I'm getting this error

```
Error: Cannot find module 'ssh2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/utils.js:5:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/madushan/mup/src/index.js:7:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

```
$ node -v
4.5.0
$ npm -v
2.15.9
$ ls  /usr/local/lib/node_modules/mup/node_modules
archiver                   bluebird                   debug                      shelljs                    source-map-support         uuid
babel-polyfill             commander                  nodemiral                  silent-npm-registry-client underscore
```

**Comment by ewan-laws** [comment]
`npm install -g ssh2` fixed this for me.

**Comment by binaryme** [comment]
I got Error: Cannot find module 'babel-polyfill'
and the error does not get fixed executing 
`npm install -g babel-polyfill` nor `npm install -g ssh2`
`npm -v` 5.4.2 also tried to run npm v 8.0 and 7.0 so apparently it is not related to npm version

**Comment by binaryme** [comment]
Solved it, it did had to do with npm version, i had globally installed mup in version of node v7.10.1
and the error occurred in node v8.0.0, check my bin paths and after switching to the version with mup installed it worked.
<img width="1112" alt="captura de pantalla 2017-12-27 a la s 16 06 53" src="https://user-images.githubusercontent.com/10454130/34394706-ab340698-eb20-11e7-9b62-5ff6662dbb86.png">
<img width="944" alt="captura de pantalla 2017-12-27 a la s 16 09 56" src="https://user-images.githubusercontent.com/10454130/34394707-ab47fe96-eb20-11e7-8a18-85632c855511.png">
