### ISSUE TITLE
Any mup command results in "events.js: 72 throw er ... This socket is closed

### ISSUE THREAD

**Issue by xauxatz** [zodern/meteor-up#293]
My project has been running smoothly for a long time and mup/mupx has worked very well.
But now suddenly - out of the blue - mup deploy/reset/logs has started to give this error.
This is the complete error code:

Configuration file : mup.json
Settings file      : settings.json

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
    at Socket._write (net.js:635:19)
    at doWrite (_stream_writable.js:223:10)
    at writeOrBuffer (_stream_writable.js:213:5)
    at Socket.Writable.write (_stream_writable.js:180:11)
    at Socket.write (net.js:613:40)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at _stream_readable.js:560:7
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)

What could be causing it?

**Comment by zodern** [comment]
@xauxatz did you find the cause?

**Comment by xauxatz** [comment]
No - I fixed the problem but I made all sorts of changes to the project, and I am not sure which of them actually got rid of this particular problem.
