### ISSUE TITLE
Verifying Deployment fails, `deployCheckWaitTime` has no effect

### ISSUE THREAD

**Issue by blainehansen** [zodern/meteor-up#307]
I've thoroughly documented this issue [on this SO post](http://stackoverflow.com/questions/39650959/kadirahq-mup-fails-on-verifying-deployment), but here's what I am pretty sure is a reasonable reduction of the error message and the  `mup logs`:

Non-redundant portion of the Error Message:

```
(node:2785) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error:
```

Logs:

```
Error: $ROOT_URL, if specified, must be an URL
        at Error (native)
        at packages/meteor/url_server.js:8:1
        at packages/meteor/url_server.js:19:1
        at /bundle/bundle/programs/server/packages/meteor.js:1365:3
        at /bundle/bundle/programs/server/boot.js:292:10
        at Array.forEach (native)
        at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
        at /bundle/bundle/programs/server/boot.js:128:5

> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> node npm-rebuild.js


> bson@0.2.21 install /bundle/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:94: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/bson/build'

> kerberos@0.0.9 install /bundle/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
kerberos.target.mk:100: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/kerberos/build'

// references to a million node modules

> bcrypt@0.8.7 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
bcrypt@0.8.7 /bundle/bundle/programs/server/npm/node_modules/bcrypt

// references to a million different node modules

{
  "meteor-dev-bundle": "0.0.0",
  "npm": "3.10.5",
  "ares": "1.10.1-DEV",
  "http_parser": "2.5.2",
  "icu": "56.1",
  "modules": "46",
  "node": "4.4.7",
  "openssl": "1.0.2h",
  "uv": "1.8.0",
  "v8": "4.5.103.36",
  "zlib": "1.2.8"
}
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
=> Starting meteor app on port:80
/bundle/bundle/programs/server/boot.js:333
}).run();
```

Thank you ahead of time.

**Comment by blainehansen** [comment]
See the answer posted in on SO
http://stackoverflow.com/a/39669387/988335
