### ISSUE TITLE
TypeError: Cannot read property 'slice' of null at packages/meteor/url_server.js:11:1

### ISSUE THREAD

**Issue by dgroch** [zodern/meteor-up#311]
MUP is successfully uploading my app bundle to the server (ubuntu EC2 instance)
A look at the logs via `docker logs ...` shows the following.

Seems to be an issue while trying to boot the server.
Any ideas?

```
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.

> fibers@1.0.13 install /bundle/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-4.5` exists; testing
Binary is fine; exiting
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
amdefine@1.0.0 node_modules/amdefine

underscore@1.5.2 node_modules/underscore

meteor-promise@0.7.2 node_modules/meteor-promise

asap@2.0.4 node_modules/asap

semver@4.1.0 node_modules/semver

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

source-map-support@0.3.2 node_modules/source-map-support

source-map@0.1.32 node_modules/source-map

promise@7.1.1 node_modules/promise

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.5
├── supports-color@0.2.0
├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
└── has-ansi@0.1.0 (ansi-regex@0.2.1)

fibers@1.0.13 node_modules/fibers
=> Starting meteor app on port:80
/bundle/bundle/programs/server/boot.js:333
}).run();
   ^

TypeError: Cannot read property 'slice' of null
    at packages/meteor/url_server.js:11:1
    at packages/meteor/url_server.js:19:1
    at /bundle/bundle/programs/server/packages/meteor.js:1365:3
    at /bundle/bundle/programs/server/boot.js:292:10
    at Array.forEach (native)
    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /bundle/bundle/programs/server/boot.js:128:5
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80
/bundle/bundle/programs/server/boot.js:333
}).run();
```

**Comment by martinmunk** [comment]
I've got this as well.

Did you get it to run anyway?

Edit: I put "http://" in front of my ROOT_URL and it worked.

**Comment by zodern** [comment]
The validator will check for `http://` or `https://` in the `ROOT_URL`
