### ISSUE TITLE
Not rebuilding NPM modules for production architecture: cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild

### ISSUE THREAD

**Issue by 0o-de-lally** [zodern/meteor-up#312]
The new MUP deploys fine. However certain methods in my app import npm modules with binaries. 

When I invoke a method on the MUP deployment I get:

```
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)

/bundle/bundle/programs/server/npm/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /bundle/bundle/programs/server/npm/node_modules/contextify/build/Release/contextify.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/bundle/bundle/programs/server/npm/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at new require (module.js:380:17)

```

The 'invalid ELF header' indicates that the build is not correct for the target system (ubuntu). I'm developing on OSX.

Is there an intermediary step, or config I'm missing that would rebuild the node libraries?

**Comment by zodern** [comment]
@keyscores did you solve this?

**Comment by 0o-de-lally** [comment]
@zodern I honestly can't remember, but I don't think so. I abandoned MUP in favor of docker.  This is what I have been using: https://github.com/aedm/minimeteor

**Comment by zodern** [comment]
Thanks for the update.
