### ISSUE TITLE
Problem while deploying using mup

### ISSUE THREAD

**Issue by kgupta15** [zodern/meteor-up#325]
This is my mup.js file:

```
module.exports = {
  servers: {
    one: {
      host: '52.41.186.122',
      username: 'ubuntu',
      pem: 'aws-key/xanthelabs.pem'
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'deep-app',
    path: '/home/cortana/Desktop/deep-app',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      PORT: 8888,
      ROOT_URL: 'http://52.41.186.122',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 60
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

```

output of `mup setup`:

```

Started TaskList: Setup Docker
[52.41.186.122] - setup docker
[52.41.186.122] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[52.41.186.122] - Setup Environment

Started TaskList: Setup Mongo
[52.41.186.122] - setup environment
[52.41.186.122] - setup environment: SUCCESS
[52.41.186.122] - copying mongodb.conf
[52.41.186.122] - Setup Environment: SUCCESS
[52.41.186.122] - copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[52.41.186.122] - start mongo
[52.41.186.122] - start mongo: SUCCESS
```

Output of `mup deploy` :

```
Building App Bundle Locally

Started TaskList: Pushing Meteor
[52.41.186.122] - Pushing Meteor App Bundle to The Server
[52.41.186.122] - Pushing Meteor App Bundle to The Server: SUCCESS
[52.41.186.122] - Pushing the Startup Script
[52.41.186.122] - Pushing the Startup Script: SUCCESS

Started TaskList: Configuring  Meteor Environment Variables
[52.41.186.122] - Sending Environment Variables
[52.41.186.122] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[52.41.186.122] - Start Meteor
[52.41.186.122] - Start Meteor: SUCCESS
[52.41.186.122] - Verifying Deployment
[52.41.186.122] x Verifying Deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
    npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
    => Starting meteor app on port:80

    assert.js:93
      throw new assert.AssertionError({
            ^
    AssertionError: "undefined" === "function"
        at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
        at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
        at Module._compile (module.js:456:26)

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
(node:11028) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 
-----------------------------------STDERR-----------------------------------
package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
=> Starting meteor app on port:80

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: "undefined" === "function"
    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
    at Module._compile (module.js:456:26)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
```

How do I remove this error? Also, what is causing this error?

**Comment by lfilho** [comment]
Try running `npm install` or `meteor npm install` before

**Comment by kgupta15** [comment]
I ran the command and then tried deploying. Gives same error log.
Also as much as I know, `meteor` takes care of `meteor npm install` too. (atleast in v1.4)

**Comment by nzwade** [comment]
@lfilho https://github.com/kadirahq/meteord/issues/7

**Comment by lfilho** [comment]
Yeah, that's why I suggested it to him, the problem seemed similar...

**Comment by lvnr** [comment]
I have the same problem when trying to deploy to Amazon EC2 (Meteor 1.4.1.2)

**Comment by ffigueroa** [comment]
Same problem. 
Meteor 1.4.1.2 from macOS to Ubuntu 15.04.

**Comment by lfilho** [comment]
Double check that node version where the bundle was generated correspond with the node version being run in the docker image. I also run with into problems because of that but can't recall if the error messages were the same.

**Comment by kgupta15** [comment]
I ported to a different docker image that works for me. `'abernix/meteord:base'` is the one I am using now.

**Comment by cafe4it** [comment]
@daemonslayer 
Works for me! 
thanks you.
(Meteor 1.4.2.3)
