### ISSUE TITLE
Failure installing Mongo

### ISSUE THREAD

**Issue by timothyarmes** [zodern/meteor-up#34]
I'm testing this new version on my setup. I don't need mongo so my mup.js file doesn't include that section. As a result the setup procedure fails:

```
macpro:do Tim$ DEBUG=* mup-test setup
  mup:module:default exec => mup setup +0ms
  mup:module:docker exec => mup docker setup +0ms

Started TaskList: Setup Docker
[xx.xx.xx.xx] - setup docker
[xx.xx.xx.xx] - setup docker: SUCCESS
  mup:module:meteor exec => mup meteor setup +769ms

Started TaskList: Setup Meteor
[xx.xx.xx.xx] - Setup Environment
  mup:module:mongo exec => mup mongo setup +1ms
TypeError: Cannot read property '_host' of undefined
    at Object.setup (index.js:33:15)
    at index.js:52:15
    at run (/Users/Tim/Development/meteor-up/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:104:47)
    at /Users/Tim/Development/meteor-up/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/Users/Tim/Development/meteor-up/node_modules/babel-polyfill/node_modules/core-js/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:419:13)
```

Here's my mup.js file:

```
module.exports = {
   servers: {
      one: {
         host: 'xx.xx.xx.xx',
         user: 'root',
         pem: '../digitalocean'
      },
   },

   meteor: {
      name: 'beesily',
      path: '../../services/web',
      servers: {
         one: {},
      },
      setupMongo: 0,
      env: {
         ROOT_URL: 'http://xx.xx.xx.xx',
         MONGO_URL:  <url>,
         MONGO_OPLOG_URL: <url>,
         DISABLE_WEBSOCKETS: '1'
      },
   },
};
```

I'm taking out the calls to setup and start mongo so that I can continue testing.

**Comment by mnmtanish** [comment]
Hi @timothyarmes,
Thanks for reporting this (looks like a bug). I'll check it out in a few hours.

**Comment by madushan1000** [comment]
@timothyarmes This should be fixed by https://github.com/kadirahq/meteor-up/pull/41, Can you check?
