### ISSUE TITLE
Not deploying with 1.4.2

### ISSUE THREAD

**Issue by PolGuixe** [zodern/meteor-up#344]
_Disclaimer:
I don't know if this is different from https://github.com/kadirahq/meteor-up/issues/172 or https://github.com/kadirahq/meteor-up/issues/342 I just moved it to a separate issue as it seems different._

I just updated to 1.4.2 and I am getting this error:

```
Error: Can't find npm module 'react/lib/ReactComponentWithPureRenderMixin'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
    at Object.require (/bundle/bundle/programs/server/boot.js:200:17)
    at options.fallback (packages/modules-runtime.js:445:18)
    at require (packages/modules-runtime.js:112:16)
    at meteorInstall.node_modules.react-addons-pure-render-mixin.index.js (packages/modules.js:17838:18)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (/bundle/bundle/programs/server/packages/react-meteor-data.js:234:256)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
```

It deploys fine with 1.4.1.2

My `packages.json` is:

``` json
"dependencies": {
    "bcrypt": "^0.8.7",
    "faker": "^3.1.0",
    "install": "^0.8.1",
    "lodash": "^4.13.1",
    "mantra-core": "^1.7.0",
    "material-ui": "^0.16.1",
    "moment": "^2.15.1",
    "money-math": "^2.4.3",
    "npm": "^3.10.6",
    "react": "^15.3.2",
    "react-dimensions": "^1.3.0",
    "react-dom": "^15.3.x",
    "react-helmet": "^3.1.0",
    "react-komposer": "^1.13.1",
    "react-komposer-plus": "^2.2.3",
    "react-mounter": "^1.0.0",
    "react-redux": "^4.4.5",
    "react-simple-di": "^1.0.1",
    "react-tap-event-plugin": "^1.0.0",
    "redux": "^3.5.2",
    "redux-form": "^6.0.1",
    "redux-form-material-ui": "^4.0.1"
  },
  "devDependencies": {
    "babel-core": "6.x.x",
    "babel-plugin-react-require": "2.x.x",
    "babel-polyfill": "6.x.x",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "6.x.x",
    "babel-preset-stage-2": "6.x.x",
    "babel-register": "^6.9.0",
    "babel-root-slash-import": "1.x.x",
    "chai": "3.x.x",
    "enzyme": "^2.2.0",
    "eslint": "2.7.x",
    "eslint-plugin-react": "4.3.x",
    "jsdom": "^8.0.4",
    "mocha": "2.x.x",
    "react-addons-test-utils": "15.3.x",
    "sinon": "1.17.x",
    "@kadira/storybook": "^2.5.2"
  }
```

**Comment by PolGuixe** [comment]
As @abernix suggested the error also occurs when when I do `meteor build` and I run the bundle in my machine.

**Comment by abernix** [comment]
This still isn't the place for this since it's not related to `meteor-up`, but let's try to handle it in the meteor repo where you've also opened the issue.

Suggest to close.

**Comment by PolGuixe** [comment]
As suggested by @abernix I am closing this issue here. Issue raised at meteor's repo: https://github.com/meteor/meteor/issues/7984
