### ISSUE TITLE
Deploy failed - app with node canvas

### ISSUE THREAD

**Issue by mfeuermann** [zodern/meteor-up#366]
Hello 

i have problem with deploying app where is included npm canvas. 
Locally working fine also with --production flag.

npm canvas required
sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

im using dockerImage: 'abernix/meteord:base'

Can you help me with this issue ? 
Thanks

[81.2.241.148]
> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> node npm-rebuild.js

[81.2.241.148]
> bcrypt@0.8.7 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
> node-gyp rebuild

[81.2.241.148]make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
[81.2.241.148]  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
[81.2.241.148]  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
[81.2.241.148]  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
[81.2.241.148]  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
[81.2.241.148]  COPY Release/bcrypt_lib.node
[81.2.241.148]make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
[81.2.241.148]
> canvas@1.6.2 install /bundle/bundle/programs/server/npm/node_modules/canvas
> node-gyp rebuild

[81.2.241.148]./util/has_lib.sh: 31: ./util/has_lib.sh: pkg-config: not found
[81.2.241.148]gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
[81.2.241.148]gyp ERR! configure error 
[81.2.241.148]gyp ERR! stack Error: `gyp` failed with exit code: 1
[81.2.241.148]gyp ERR! stack     at ChildProcess.onCpExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
[81.2.241.148]gyp ERR! stack     at emitTwo (events.js:87:13)
[81.2.241.148]gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
[81.2.241.148]gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[81.2.241.148]gyp ERR! System Linux 3.16.0-4-amd64
[81.2.241.148]gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[81.2.241.148]gyp ERR! cwd /bundle/bundle/programs/server/npm/node_modules/canvas
[81.2.241.148]gyp ERR! node -v v4.4.7
[81.2.241.148]gyp ERR! node-gyp -v v3.4.0
[81.2.241.148]gyp ERR! not ok 
[81.2.241.148]
[81.2.241.148]npm ERR! Linux 3.16.0-4-amd64
[81.2.241.148]npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--update-binary"
[81.2.241.148]npm ERR! node v4.4.7
[81.2.241.148]npm ERR! npm  v3.10.8
[81.2.241.148]npm ERR! code ELIFECYCLE
[81.2.241.148]npm ERR! canvas@1.6.2 install: `node-gyp rebuild`
[81.2.241.148]npm ERR! Exit status 1
[81.2.241.148]npm ERR! 
[81.2.241.148]npm ERR! Failed at the canvas@1.6.2 install script 'node-gyp rebuild'.
[81.2.241.148]npm ERR! Make sure you have the latest version of node.js and npm installed.
[81.2.241.148]npm ERR! If you do, this is most likely a problem with the canvas package,
[81.2.241.148]npm ERR! not with npm itself.
[81.2.241.148]npm ERR! Tell the author that this fails on your system:
[81.2.241.148]npm ERR!     node-gyp rebuild
[81.2.241.148]npm ERR! You can get information on how to open an issue for this project with:
[81.2.241.148]npm ERR!     npm bugs canvas
[81.2.241.148]npm ERR! Or if that isn't available, you can get their info via:
[81.2.241.148]npm ERR!     npm owner ls canvas
[81.2.241.148]npm ERR! There is likely additional logging output above.
[81.2.241.148]
[81.2.241.148]npm ERR! Please include the following file with any support request:
[81.2.241.148]npm ERR!     /bundle/bundle/programs/server/npm/npm-debug.log
[81.2.241.148]
[81.2.241.148]npm WARN meteor-dev-bundle@0.0.0 No description
[81.2.241.148]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[81.2.241.148]npm WARN meteor-dev-bundle@0.0.0 No license field.
[81.2.241.148]npm ERR! Linux 3.16.0-4-amd64
[81.2.241.148]npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
[81.2.241.148]npm ERR! node v4.4.7
[81.2.241.148]npm ERR! npm  v3.10.8
[81.2.241.148]npm ERR! code ELIFECYCLE
[81.2.241.148]npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
[81.2.241.148]npm ERR! Exit status 1
[81.2.241.148]npm ERR! 
[81.2.241.148]npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
[81.2.241.148]npm ERR! Make sure you have the latest version of node.js and npm installed.
[81.2.241.148]npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
[81.2.241.148]npm ERR! not with npm itself.
[81.2.241.148]npm ERR! Tell the author that this fails on your system:
[81.2.241.148]npm ERR!     node npm-rebuild.js
[81.2.241.148]npm ERR! You can get information on how to open an issue for this project with:
[81.2.241.148]npm ERR!     npm bugs meteor-dev-bundle
[81.2.241.148]npm ERR! Or if that isn't available, you can get their info via:
[81.2.241.148]npm ERR!     npm owner ls meteor-dev-bundle
[81.2.241.148]npm ERR! There is likely additional logging output above.
[81.2.241.148]
[81.2.241.148]npm ERR! Please include the following file with any support request:
[81.2.241.148]npm ERR!     /bundle/bundle/programs/server/npm-debug.log

**Comment by mfeuermann** [comment]
Resolved by using different image, that image contains required packages (cairo etc..)
romaroma/meteord. Thanks romaroma!
