### ISSUE TITLE
How to fix deployment issue? Installing bcrypt and libpq

### ISSUE THREAD

**Issue by jvallarvisp** [zodern/meteor-up#369]
```
$ mup start

Started TaskList: Start Meteor
[35.163.139.67] - Start Meteor
[35.163.139.67] - Start Meteor: SUCCESS
[35.163.139.67] - Verifying Deployment
[35.163.139.67] x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        RR!     npm owner ls meteor-dev-bundle
        npm ERR! There is likely additional logging output above.
        
        npm ERR! Please include the following file with any support request:
        npm ERR!     /bundle/bundle/programs/server/npm-debug.log
        
        > meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
        > node npm-rebuild.js
        
        
        > bcrypt@0.8.7 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
        > node-gyp rebuild
        
        make: Entering directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
          CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
          CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
          SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
          COPY Release/bcrypt_lib.node
        make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
        
        > libpq@1.8.5 install /bundle/bundle/programs/server/npm/node_modules/libpq
        > node-gyp rebuild
        
         
        => Redeploying previous version of the app
         
        -----------------------------------STDOUT-----------------------------------
        
        To see more logs type 'mup logs --tail=50'
        
        ----------------------------------------------------------------------------

```

**Comment by ibrahimzahoor** [comment]
@jvallarvisp Remove bcrypt from the package.js file as a dependancy, Meteor bcrypt would work fine with the following error 

```
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

 meteor npm install --save bcrypt
```

After removing the bcrypt npm package your deployment would be fine

**Comment by Floriferous** [comment]
Is it ok to ignore this warning? Not sure what exactly it entails ?

**Comment by jvallarvisp** [comment]
@ibrahimzahoor Thanks. How about libpq? Do you have an idea on how to install it?

```

[35.163.139.67]> libpq@1.8.5 install /bundle/bundle/programs/server/npm/node_modules/libpq
[35.163.139.67]> node-gyp rebuild
[35.163.139.67]
[35.163.139.67]find: `/usr/pg*': No such file or directory
[35.163.139.67]gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
[35.163.139.67]gyp ERR! configure error 
[35.163.139.67]gyp ERR! stack Error: `gyp` failed with exit code: 1
[35.163.139.67]gyp ERR! stack     at ChildProcess.onCpExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
[35.163.139.67]gyp ERR! stack     at emitTwo (events.js:87:13)
[35.163.139.67]gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
[35.163.139.67]gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[35.163.139.67]gyp ERR! System Linux 4.4.0-47-generic
[35.163.139.67]gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[35.163.139.67]gyp ERR! cwd /bundle/bundle/programs/server/npm/node_modules/libpq
[35.163.139.67]gyp ERR! node -v v4.4.7
[35.163.139.67]gyp ERR! node-gyp -v v3.4.0
[35.163.139.67]gyp ERR! not ok 
[35.163.139.67]
[35.163.139.67]npm ERR! Linux 4.4.0-47-generic
[35.163.139.67]npm ERR! argv "/opt/nodejs/bin/node" "/opt/nodejs/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
[35.163.139.67]npm ERR! node v4.4.7
[35.163.139.67]npm ERR! npm  v3.10.8
[35.163.139.67]npm ERR! code ELIFECYCLE
[35.163.139.67]npm ERR! libpq@1.8.5 install: `node-gyp rebuild`
[35.163.139.67]npm ERR! Exit status 1
[35.163.139.67]npm ERR! 
[35.163.139.67]npm ERR! Failed at the libpq@1.8.5 install script 'node-gyp rebuild'.
[35.163.139.67]npm ERR! Make sure you have the latest version of node.js and npm installed.
[35.163.139.67]npm ERR! If you do, this is most likely a problem with the libpq package,
[35.163.139.67]npm ERR! not with npm itself.
[35.163.139.67]npm ERR! Tell the author that this fails on your system:
[35.163.139.67]npm ERR!     node-gyp rebuild
[35.163.139.67]npm ERR! You can get information on how to open an issue for this project with:
[35.163.139.67]npm ERR!     npm bugs libpq
[35.163.139.67]npm ERR! Or if that isn't available, you can get their info via:
[35.163.139.67]npm ERR!     npm owner ls libpq
[35.163.139.67]npm ERR! There is likely additional logging output above.
[35.163.139.67]
[35.163.139.67]npm ERR! Please include the following file with any support request:
[35.163.139.67]npm ERR!     /bundle/bundle/programs/server/npm/npm-debug.log
[35.163.139.67]
```

**Comment by ibrahimzahoor** [comment]
@Floriferous This warning only comes on Ubuntu 16, If you want to install the npm `bcrypt` package you can go for Ubuntu 14 instance, Ubuntu 14 is more stable for MUP deployment according to my experience.

**Comment by ibrahimzahoor** [comment]
@jvallarvisp You can install `libpq-dev` it on the Docker container by customising the container you're using. So you would modify a container and upload that on docker hub and mention its name in the `dockerImage:"username:dockerContainer"`.

or by looking at the error `find: /usr/pg*: No such file or directory` i think you need to install the dependency `pg_config` or `pg` for it to work.

**Comment by guillim** [comment]
@jvallarvisp i had similar issue so I created the docker that could overcome this. try it: 
dockerImage:"guillim/meteord"

Now it works great !

It is bascially the docker created by abernix but where I updated node (from v4 to v6) and installed some npm packages i needed (including  node-gyp)

**Comment by doronsever** [comment]
I had the same or similar issue, also with node gyp and bcrypt.
If you are using abernix/meteord:base, you need that your node version that is installed on your computer is the same as abernix/meteord:base.

I had node 5.12.0 on my computer and when i moved to node 4.7.0, which abernix/meteord:base uses, everything started to work again.

**Comment by PolGuixe** [comment]
@doronsever it worked for me.

I bit of a pain having to change node versions continuously
