### ISSUE TITLE
Unable to deploy app with replicaset 'No valid replicaset members found'

### ISSUE THREAD

**Issue by 33Fraise33** [zodern/meteor-up#380]
Hello,

When deploying using meteor up using a full replicaset I'm unable to deploy without getting an error. Our current productionsetup is a single mongoserver with a replicaset initiated which works just fine. Now I fired up 3 servers and created a new replicaset for our staging setup. Each node communicates within the replicaset over the internal network. I entered the hostnames in /etc/hosts like this (on all the mongo servers & the webserver):

```
10.0.0.3 mongo1
10.0.0.4 mongo2
10.0.0.5 mongo3
```

The replicaset is working properly confirmed with commands like `rs.status()`. From the meteor app server I'm able to ping mongo1, mongo2 etc. I'm also able to login with our credentials from the app server. But when I deploy with meteor-up I get the following error:

```
MongoError: no valid replicaset members found
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:219:27)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:103:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    - - - - -
    at [object Object]._onTimeout (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:653:33)
    at Timer.listOnTimeout (timers.js:92:15)
```

my mup file is the following: 

```
module.exports = {
  servers: {
    webbeta: {
      host: 'x.x.x.x',
      username: 'username',
      pem: 'privatekeyfile.pem',
      opts: {
        port: 22
      }
    }
  },

  meteor: {
    name: 'appname',
    path: '../.',
    docker: {
      image: 'abernix/meteord:base',
      args: [
        '--memory-reservation 1024M'
      ]
    },
    servers: {
      webbeta: {}
    },
    buildOptions: {
      serverOnly: true,
      debug: true,
      cleanAfterBuild: true, // default
      buildLocation: '/tmp/' // defaults to /tmp/<uuid> - do not enter anything here for windows
    },
    env: {
      ROOT_URL: 'http://appurl.domain.com',
      MONGO_URL: 'mongodb://user:password@mongo1,mongo2,mongo3/dbname?replicaSet=rs0',
      MONGO_OPLOG_URL: 'mongodb://oplogger:password@mongo1,mongo2,mongo3/local?authSource=admin&replicaSet=rs0'
    },
    deployCheckWaitTime: 120
  }
};
```

Using ip addresses in the connection string instead of hostnames gives me the error: `no primary found in replicaset`. 
Putting only one hostname in the connection string doesn't matter.

Is there anything I should change? 
Possible issues I thought about: 
- Docker doesn't recognise the host file
- My connection url is incorrect (tried with socketTimeoutMS=300000 etc)
- My mongo setup is in some kind of way incorrect 
- Other

**Comment by 33Fraise33** [comment]
I managed to resolve this. What I was trying to do was keep all data traffic over the local network (VM's on azure in my case).

Apparently docker uses a specific hosts file different to the one at /etc/hosts. You can resolve this by using the `--network=host` argument under docker args.

More info about this can be found over here:
https://docs.docker.com/engine/reference/run/#/network-settings

You could also use --add-hosts and add every host but that was suboptimal for my case.
