### ISSUE TITLE
mup deploy on windows doesn't work  Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by keithn** [zodern/meteor-up#397]
It has an error with the build, but it does seem to build the application if I go to the tmp directory ( may not be fully building it perhaps).  But doesn't get any further than this.

```
Building App Bundle Locally
{ cwd: 'C:\\Repositories\\ss' }
{ Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\WINDOWS\\system32\\cmd.exe',
  path: 'C:\\WINDOWS\\system32\\cmd.exe',
  spawnargs:
   [ '/c',
     'meteor',
     'build',
     '--directory',
     'C:\\tmp\\0542c7c6-8096-4f50-9a49-cee81d92b89c',
     '--architecture',
     'os.linux.x86_64',
     '--server',
     'http://localhost:3000',
     '--server-only' ] }

=> Build Error. Check the logs printed above.
(node:8580) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build-error
(node:8580) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by zodern** [comment]
This usually happens when the path to the app is incorrect. Version 1.2.2 will display a better error message.
