### ISSUE TITLE
Problems with Mongo 3.4 image with some requests

### ISSUE THREAD

**Issue by bensventures** [zodern/meteor-up#398]
Just a heads up for people having issues suddenly with Mongo db. My deploy was crashing the past few days and I think I've just figured out why.

Mup uses the `mongo:latest` image in docker. The image has just been updated in the Docker repo to use the latest `3.4` version of Mongo DB, which has some backward incompatible changes. https://docs.mongodb.com/master/release-notes/3.4-compatibility/#backwards-incompatible-features

In my case $geoNear queries where failling. 

I manually changed the `mongo-start.sh` to lock it to mongo `3.2.11` and everything went back to working.

Here it is the new content of `mongo-start.sh`
```
#!/bin/bash

set -e
# we use this data directory for the backward compatibility
# older mup uses mongodb from apt-get and they used this data directory
sudo mkdir -p /var/lib/mongodb

sudo docker pull mongo:3.2.11
set +e
sudo docker rm -f mongodb
set -e

sudo docker run \
  -d \
  --restart=always \
  --publish=127.0.0.1:27017:27017 \
  --volume=/var/lib/mongodb:/data/db \
  --volume=/opt/mongodb/mongodb.conf:/mongodb.conf \
  --name=mongodb \
  mongo:3.2.11 mongod -f /mongodb.conf
```

**Comment by nosleepfilipe** [comment]
Hey @bensventures i have exactly the same issue, can you explain me how can i change that?
how can i change that in the server? I'm using digital ocean for the hosting.

**Comment by bensventures** [comment]
you have to change the file I mentioned on your computer, not on the server. The file is located in the global `node_modules` folder. On a mac `/usr/local/lib/node_modules/mup/lib/modules/mongo/assets/mongo-start.sh`

You'll see code similar to what I pasted above, and you want to add the version of mongo to those lines:
```
...
sudo docker pull mongo
...
mongo mongod -f /mongodb.conf
```

After that run `mup setup` and hopefully that should be it.

**Comment by nosleepfilipe** [comment]
just change the file but now im getting another error.

```
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/bundle/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [mongodb:27017]
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/accounts-base/accounts_common.js:141:1
    at /bundle/bundle/programs/server/packages/accounts-base.js:243:4
    at /bundle/bundle/programs/server/packages/accounts-base.js:1659:3
    at /bundle/bundle/programs/server/boot.js:222:10
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)
```

this is my config
```
...
 meteor: {
    name: 'elyweddingsDocker',
    path: '/Users/nosleepfilipe/repo/com.elyweddings',
    port:3000,
    servers: {
      one: {}
    },
    buildOptions: {
      //serverOnly: true,
      cleanAfterBuild: true, // default
    },
    env: {
      ROOT_URL: 'http://elyweddings.com',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 10
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};

```


this is the containers on the server 
```
root@elyweddings:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                               PORTS                        NAMES
7f25469aae7f        kadirahq/meteord    "/bin/sh -c 'bash $ME"   3 minutes ago       Restarting (8) About a minute ago    0.0.0.0:80->80/tcp           elyweddingsDocker
3d180924c99b        mongo:3.2.11        "/entrypoint.sh mongo"   5 minutes ago       Restarting (14) About a minute ago   127.0.0.1:27017->27017/tcp   mongodb
```


thanks for the help

**Comment by bensventures** [comment]
You shouldn't need to put a `MONGO_URL` in the config if you are running a local instance, mup will do that for you. Maybe try removing the line from the config.

here is mine for example:

```
module.exports = {
    servers: {
        one: {
            host: 'ip', //Staging
            username: 'username',
            password: 'password'
        }
    },
    meteor: {
        name: 'appname',
        path: '../../../project',
        port: 3000,
        volumes: {
            "/var/www/app-uploads": "/app-uploads", // put uploads outisde of docker
            "/etc/localtime": "/etc/localtime" // Have docker container time same as server time
        },
        docker: {
            image: 'abernix/meteord:base' // meteord image comaptible with 1.4.x
        },
        servers: {
            one: {}
        },
        env: {
            PORT: "3000",
            ROOT_URL: 'https://websiteurl.com',
            "MAIL_URL": "smtp://smtpserverurl"
        },
        enableUploadProgressBar: true,
        deployCheckWaitTime: 60
    },
    mongo: {
        oplog: true,
        port: 27017,
        servers: {
            one: {}
        }
    }
};
```

**Comment by nosleepfilipe** [comment]
still getting the same error

```
[139.59.153.120]
[139.59.153.120]/bundle/bundle/programs/server/node_modules/fibers/future.js:278
[139.59.153.120]						throw(ex);
[139.59.153.120]						      ^
[139.59.153.120]Error: failed to connect to [mongodb:27017]
[139.59.153.120]    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
[139.59.153.120]    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
[139.59.153.120]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
[139.59.153.120]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
[139.59.153.120]    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
[139.59.153.120]    at new Mongo.Collection (packages/mongo/collection.js:98:1)
[139.59.153.120]    at packages/accounts-base/accounts_common.js:141:1
[139.59.153.120]    at /bundle/bundle/programs/server/packages/accounts-base.js:243:4
[139.59.153.120]    at /bundle/bundle/programs/server/packages/accounts-base.js:1659:3
[139.59.153.120]    at /bundle/bundle/programs/server/boot.js:222:10
[139.59.153.120]    - - - - -
[139.59.153.120]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
[139.59.153.120]    at [object Object].emit (events.js:106:17)
[139.59.153.120]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
[139.59.153.120]    at [object Object].emit (events.js:98:17)
[139.59.153.120]    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
[139.59.153.120]    at Socket.emit (events.js:95:17)
[139.59.153.120]    at net.js:441:14
[139.59.153.120]    at process._tickCallback (node.js:458:13)
[139.59.153.120]npm WARN deprecated This version of npm lacks support for important features,
[139.59.153.120]npm WARN deprecated such as scoped packages, offered by the primary npm
[139.59.153.120]npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[139.59.153.120]npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[139.59.153.120]npm WARN deprecated
[139.59.153.120]npm WARN deprecated   npm -g install npm@latest-2
[139.59.153.120]npm WARN deprecated
[139.59.153.120]npm WARN deprecated To upgrade to the latest stable version, run:
[139.59.153.120]npm WARN deprecated
[139.59.153.120]npm WARN deprecated   npm -g install npm@latest
[139.59.153.120]npm WARN deprecated
[139.59.153.120]npm WARN deprecated (Depending on how Node.js was installed on your system, you
[139.59.153.120]npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[139.59.153.120]npm WARN deprecated on Windows, run them from an Administrator prompt.)
[139.59.153.120]npm WARN deprecated
[139.59.153.120]npm WARN deprecated If you're running the version of npm bundled with
[139.59.153.120]npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[139.59.153.120]npm WARN deprecated will be bundled with a version of npm@2, which has some small
[139.59.153.120]npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[139.59.153.120]npm WARN deprecated semver behavior.
[139.59.153.120]npm WARN package.json meteor-dev-bundle@0.0.0 No description
[139.59.153.120]npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[139.59.153.120]npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[139.59.153.120]=> Starting meteor app on port:80
```

this is my config now

```
module.exports = {
  servers: {
    one: {
      host: '*******',
      username: '*******',
      //pem: '~/.ssh/id_rsa.pub'
      // pem:
      password:'*******',
      // or leave blank for authenticate from ssh-agent
    }
  },
  meteor: {
     name: 'elyweddingsDocker',
     path: '/Users/nosleepfilipe/repo/com.elyweddings',
     port: 3000,
     docker: {
         image: 'kadirahq/meteord' // meteord image comaptible with 1.4.x
     },
     servers: {
         one: {}
     },
     env: {
         PORT: "3000",
         ROOT_URL: 'http://elyweddings.com',
     },
     enableUploadProgressBar: true,
     deployCheckWaitTime: 60
 },
 mongo: {
     oplog: true,
     port: 27017,
     servers: {
         one: {}
     }
 },
};
```

**Comment by bensventures** [comment]
Mm not sure what is happening then. I suppose you've run `mup setup` and `mup deploy` after changing the config? Maybe check on the server the status of the Docker containers, if they are using the correct images, if they are stable (not restarting all the time)

You could also try stoping and deleting all the containers before doing the `mup setup` to start fresh.

Make sure you don't have a local mongo already listening on the 27017 port, that would prevent the docket container from starting properly too.

**Comment by nosleepfilipe** [comment]
Stoped all the containers and delete all the images and containers from the server.

stop my local mongoDb service


this is my mongo-start.sh
(nosleepfilipe in ~/.npm-packages/lib/node_modules/mup/lib/modules/mongo/assets/mongo-start.sh)
```
#!/bin/bash

set -e
# we use this data directory for the backward compatibility
# older mup uses mongodb from apt-get and they used this data directory
sudo mkdir -p /var/lib/mongodb

sudo docker pull mongo:3.2.11
set +e
sudo docker rm -f mongodb
set -e

sudo docker run \
  -d \
  --restart=always \
  --publish=127.0.0.1:27017:27017 \
  --volume=/var/lib/mongodb:/data/db \
  --volume=/opt/mongodb/mongodb.conf:/mongodb.conf \
  --name=mongodb \
  mongo:3.2.11 mongod -f /mongodb.conf
```


i have done the setup and deploy again.

this is the mup.json
```
module.exports = {
  servers: {
    one: {
      host: '139.59.153.120',
      username: '*******',
      //pem: '~/.ssh/id_rsa.pub'
      // pem:
      password:'*******',
      // or leave blank for authenticate from ssh-agent
    }
  },
  meteor: {
     name: 'elyweddingsDocker',
     path: '/Users/nosleepfilipe/repo/com.elyweddings',
     port: 3000,
     docker: {
         image: 'kadirahq/meteord' // meteord image comaptible with 1.4.x
     },
     servers: {
         one: {}
     },
     env: {
         PORT: "3000",
         ROOT_URL: 'http://elyweddings.com',
     },
     enableUploadProgressBar: true,
     deployCheckWaitTime: 60
 },
 mongo: {
     oplog: true,
     port: 27017,
     servers: {
         one: {}
     }
 },
};

```


this is the containers
```
root@elyweddings:~# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                        NAMES
b643e6bece50        kadirahq/meteord    "/bin/sh -c 'bash $ME"   54 seconds ago      Restarting (8) 7 seconds ago    0.0.0.0:3000->80/tcp         elyweddingsDocker
97d6ae011a11        mongo:3.2.11        "/entrypoint.sh mongo"   3 minutes ago       Restarting (14) 3 seconds ago   127.0.0.1:27017->27017/tcp   mongodb
```

this is the images
```
root@elyweddings:~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mongo               3.2.11              c5185a594064        2 weeks ago         342.7 MB
kadirahq/meteord    latest              807754a01782        4 months ago        330.7 MB
```



this is the error

```
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

/bundle/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
Error: failed to connect to [mongodb:27017]
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:98:1)
    at packages/accounts-base/accounts_common.js:141:1
    at /bundle/bundle/programs/server/packages/accounts-base.js:243:4
    at /bundle/bundle/programs/server/packages/accounts-base.js:1659:3
    at /bundle/bundle/programs/server/boot.js:222:10
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:555:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)
```

**Comment by bensventures** [comment]
For the output of `docker ps` it looks like your containers keep restarting. I can understand the meteor one restarting because of the mongo connection error but not sure what would be happening to the mongo container.

A few ideas: 
* check the docker logs (`/var/log/upstart/docker.log` on ubuntu)
* check what is running on port 27017 on the server, maybe something is already using the port and the mongo container cannot start properly
* stop the containers and start them with the debug option `docker -D start mongodb`

**Comment by nosleepfilipe** [comment]
hey @bensventures just to let you know, i have delete the droplet and created a new one and now everything is working perfectly. thanks for your help =)

and Happy news years

**Comment by bensventures** [comment]
great news @nosleepfilipe thanks for taking the time to update us :)

Happy new years too.

**Comment by shadowcodex** [comment]
This needs to be added as a config option in mup.js
