### ISSUE TITLE
AssertionError: "undefined" === "function" and deprecation 

### ISSUE THREAD

**Issue by yawlhead91** [zodern/meteor-up#422]
Hi there I cannot seem to get the deployment to work I have tried just about everything. Removing opt folder, docker images , updates and downgrading node and npm. I created a new Ubuntu VM , installed node and meteor , also tried with out them installed on the machine. I tried deploying from my windows machine but also my Ubuntu machine. I also tried moving the deploy wait time up , Everything. I keep getting this error. I cant seem to get it at all .

Error
```

	-----------------------------------STDERR-----------------------------------
	
	npm WARN deprecated semver behavior.
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
	=> Starting meteor app on port:80
	
	assert.js:93
	  throw new assert.AssertionError({
	        ^
	AssertionError: "undefined" === "function"
	    at wrapPathFunction (/bundle/bundle/programs/server/mini-files.js:77:10)
	    at Object.<anonymous> (/bundle/bundle/programs/server/mini-files.js:108:24)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Module.require (module.js:364:17)
	    at require (module.js:380:17)
	    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
	    at Module._compile (module.js:456:26)
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------

```

Mup.js

```
module.exports = {
  servers: {
    one: {
      host: '1.2.3.4',
      username: 'xxx',
      password:'xxx',
    }
  },

  meteor: {
    name: 'xxx',
    path: '.',
    servers: {
      one: {
      host: '1.2.3.4',
      username: 'xxx',
      password:'xxx',
      }
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://1.2.3.4:2222',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

    //dockerImage: 'kadirahq/meteord'
    deployCheckWaitTime: 300
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
};
```

**Comment by yawlhead91** [comment]
Issue was r

**Comment by SaiMun92** [comment]
Did u solve it in the end? How do you solve it? I am currently facing this issue now

**Comment by yawlhead91** [comment]
Hi @icecoolcat  

I did thanks to https://github.com/abernix,

You have to set the docker image in the mup file to 

`dockerImage: 'abernix/meteord',`

Then make sure node, meteor node and npm are the same vresions on both client and server in my case.

Meteor node - v4.6.2
Node - v4.6.2

Meteor npm - 3.10.9
npm - 3.10.9


I did reinstall both node and meteor first removing everything. 

Hope this helps

**Comment by SaiMun92** [comment]
Nice!!!!! That did the trick!!! Thanks a lot mann!!!!!!

**Comment by yawlhead91** [comment]
@icecoolcat  No problem
