### ISSUE TITLE
joi module - SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by ClarenceL** [zodern/meteor-up#453]
Immediately after updating to 1.2.1 I get this error on deploy

/Users/clarencel/.npm-packages/lib/node_modules/mup/node_modules/joi/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:/Users/z-mod/dev/meteor-up/src/index.js:3:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by ClarenceL** [comment]
Never mind my nodejs was just very old
