### ISSUE TITLE
Supports-Color crashes deployment

### ISSUE THREAD

**Issue by jkalodner** [zodern/meteor-up#464]
I've always had a lot of trouble with meteor up, but I've never run into this problem before.

On `mup deploy`, it runs for maybe 30 seconds, then prints the following error:

`Building App Bundle Locally
/Users/jacobkalodner/.meteor/packages/templating-compiler/.1.3.0.nhx3l++os+web.browser+web.cordova/plugin.compileTemplatesBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:177
      throw error;
      ^

Error: ENOENT: no such file or directory, stat '/Users/jacobkalodner/Documents/assessment/node_modules/.bin/supports-color'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.realpathSync (fs.js:1456:12)
    at Object.wrapper [as realpath] (/tools/fs/files.js:1535:35)
    at isWithinProdPackage (/tools/isobuild/bundler.js:485:28)
    at /tools/isobuild/builder.js:546:15
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at /tools/isobuild/builder.js:556:11
    at Array.forEach (native)
    at walk (/tools/isobuild/builder.js:464:34)
    at Builder.copyDirectory (/tools/isobuild/builder.js:594:5)
    at /tools/isobuild/bundler.js:2040:17
    at Function._.each._.forEach (/Users/jacobkalodner/.meteor/packages/meteor-tool/.1.4.2_6.18jbvwi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at JsImage.write (/tools/isobuild/bundler.js:1999:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2268:13)
    at /tools/isobuild/bundler.js:2363:30
    at /tools/isobuild/bundler.js:2496:9
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:2486:26
    at /tools/isobuild/bundler.js:2426:7
    at /tools/isobuild/bundler.js:2827:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2660:31)
    at /tools/isobuild/bundler.js:2607:32
    at Object.withCache (/tools/fs/files.js:1601:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2607:16)
    at buildCommand (/tools/cli/commands.js:952:30)
    at Command.func (/tools/cli/commands.js:827:12)
    at /tools/cli/main.js:1483:23

=> Build Error. Check the logs printed above.
(node:689) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build-error`

It appears to be a problem with the supports-color file. However, if I actually go to the location (/Users/jacobkalodner/Documents/assessment/node_modules/.bin) and get a list of the files there, supports-color is present. But when I attempt to access it, I get 'no such file or directory' again.

I'm completely lost here.

**Comment by zodern** [comment]
Are you able to run the app locally after seeing this error?

**Comment by jkalodner** [comment]
Yes, running it locally works perfectly.

**Comment by zodern** [comment]
Try building your app and see if it works:

`meteor build --directory ./.test-build --architecture os.linux.x86_64 --server-only`

**Comment by jkalodner** [comment]
On the build, it throws the exact same error.

**Comment by zodern** [comment]
It might be a bug with meteor then.

**Comment by jkalodner** [comment]
Simply deleting the supports-color file did the trick. Thanks!

**Comment by zodern** [comment]
> I've always had a lot of trouble with meteor up

When you have time, would you mind sharing what troubles you've had? My goal right now is to make meteor up more reliable and less error prone.
