### ISSUE TITLE
Deployment at new DO droplet Ubuntu16.04 failed

### ISSUE THREAD

**Issue by s7dhansh** [zodern/meteor-up#476]
```
ReferenceError: NumberLong is not defined
    at mongodb.init.rs.js (root/etc/mongodb/init.rs.js:5:21)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at /bundle/bundle/programs/server/app/app.js:4184:1
    at /bundle/bundle/programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
    at /bundle/bundle/programs/server/boot.js:128:5
    at /bundle/bundle/programs/server/boot.js:344:5
    at Function.run (/bundle/bundle/programs/server/profile.js:480:12)
```

The deployments at old droplets (also 16.04) work fine, except for occasional `Unhandled promise rejection` errors.

The config:
```
module.exports = {
	servers: {
		production: {
			host: 'xxx',
			username: 'root',
		}
	},
	meteor: {
		name: 'visits',
		path: '/a/visits',
		servers: {
			production: {}
		},
		buildOptions: {
			serverOnly: true,
		},
		env: {
			ROOT_URL: 'xxx',
			PORT: 3060,
			MONGO_URL: 'mongodb://xxx',
			MONGO_OPLOG_URL: 'mongodb://xxx',
			MAIL_URL: 'smtp://xxx',
			METEOR_ENV: 'production',
		},
		docker: {
			image: 'abernix/meteord:base',
			args: ['-v /etc/timezone:/etc/timezone', '-v /etc/localtime:/etc/localtime']
		},
		deployCheckWaitTime: 180 //default 10
	},
};
```

**Comment by s7dhansh** [comment]
Sorry, it was some problem at the code end.
