### ISSUE TITLE
Verifying deployment: FAILED because of const unicodeNormalizePath = (path) => { Unexpected token >

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#505]
my global node version is and meteor version is 4.7.3
npm v4.3.0 
Here is mupx log

[146.185.183.65] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[146.185.183.65] npm WARN deprecated 
[146.185.183.65] npm WARN deprecated If you're running the version of npm bundled with
[146.185.183.65] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[146.185.183.65] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[146.185.183.65] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[146.185.183.65] npm WARN deprecated semver behavior.
[146.185.183.65] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[146.185.183.65] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[146.185.183.65] npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[146.185.183.65] npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/bundle/bundle/programs/server)
[146.185.183.65] => Starting meteor app on port:80
[146.185.183.65] 
[146.185.183.65] /bundle/bundle/programs/server/mini-files.js:74
[146.185.183.65] const unicodeNormalizePath = (path) => {
[146.185.183.65]                                      ^
[146.185.183.65] SyntaxError: Unexpected token >
[146.185.183.65]     at Module._compile (module.js:439:25)
[146.185.183.65]     at Object.Module._extensions..js (module.js:474:10)
[146.185.183.65]     at Module.load (module.js:356:32)
[146.185.183.65]     at Function.Module._load (module.js:312:12)
[146.185.183.65]     at Module.require (module.js:364:17)
[146.185.183.65]     at require (module.js:380:17)
[146.185.183.65]     at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
[146.185.183.65]     at Module._compile (module.js:456:26)
[146.185.183.65]     at Object.Module._extensions..js (module.js:474:10)
[146.185.183.65]     at Module.load (module.js:356:32)
[146.185.183.65] npm WARN deprecated This version of npm lacks support for important features,
[146.185.183.65] npm WARN deprecated such as scoped packages, offered by the primary npm
[146.185.183.65] npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[146.185.183.65] npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[146.185.183.65] npm WARN deprecated 
[146.185.183.65] npm WARN deprecated   npm -g install npm@latest-2
[146.185.183.65] npm WARN deprecated 
[146.185.183.65] npm WARN deprecated To upgrade to the latest stable version, run:
[146.185.183.65] npm WARN deprecated 
[146.185.183.65] npm WARN deprecated   npm -g install npm@latest
[146.185.183.65] npm WARN deprecated 
[146.185.183.65] npm WARN deprecated (Depending on how Node.js was installed on your system, you
[146.185.183.65] npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[146.185.183.65] npm WARN deprecated on Windows, run them from an Administrator prompt.)
[146.185.183.65] npm WARN deprecated 
[146.185.183.65] npm WARN deprecated If you're running the version of npm bundled with
[146.185.183.65] npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[146.185.183.65] npm WARN deprecated will be bundled with a version of npm@2, which has some small
[146.185.183.65] npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[146.185.183.65] npm WARN deprecated semver behavior.
[146.185.183.65] npm WARN package.json meteor-dev-bundle@0.0.0 No description
[146.185.183.65] npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[146.185.183.65] npm WARN package.json meteor-dev-bundle@0.0.0 No README data

**Comment by Cu4rach4** [comment]
Change node version, use nvm to install version stable or 4.7.2.

**Comment by zodern** [comment]
Are you using mup or mupx? It looks like the server has the wrong node version.

**Comment by jyoti-openair** [comment]
I'm using mupx, I updated node to 4.7.2 but the problem persisted so I updated it to 6.10.0 still same problem.

**Comment by Cu4rach4** [comment]
> my global node version is and meteor version is 4.7.3
npm v4.3.0
Here is mupx log

You are using MUPX, so you need to run with node 0.10.44.-

**Comment by zodern** [comment]
@jyoti-openair what meteor version are you using? It looks like you are using Meteor 1.4, which mupx doesn't support. If that is the case, you will need to migrate to mup. The readme has a migration guide.

**Comment by jyoti-openair** [comment]
ok. I performed migration steps. Now Im getting

Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

I have few sites hosted via nginx in port 80. How can I fix this ? Can I change the port ? Because when I change port of my existing sites, its not pointed correctly untill its port 80, so I cannot change anything out there

**Comment by Cu4rach4** [comment]
You can setting up the port to use on your mup.js.

**Comment by jyoti-openair** [comment]
I have set PORT 3000 already, I'm not sure where the issue was so I tried,
pm2-meteor, now I have deployed using it

**Comment by zodern** [comment]
@jyoti-openair did you also have mup setup `ssl`? That would have been using port 80.

**Comment by jyoti-openair** [comment]
No there is no ssl, this is my mup setup

```
module.exports = {
  servers: {
    one: {
      host: '***.***.***.**',
      username: '*******',
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'appName',
    path: '/home/jyoti/git/appName/',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://laopen.space',
      MONGO_URL: 'mongodb://localhost/openspace',
    },


    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
    },
    deployCheckWaitTime: 600,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: false
  },

)  mongo: {
    oplog: true,
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {},
    },
  },
};

```

**Comment by zodern** [comment]
It's missing `meteor.env.PORT`, but if that was set `mup` shouldn't have been using port 80.

**Comment by jyoti-openair** [comment]
Hi, thanks! @zodern that was the catch, mup and PORT environment along with I had to remove node_modules and reinstall. Had to switch back to mup from pm2 as, there were mongo error could be because of less memory. Will see how it goes with mup.

**Comment by abeaudoin2013** [comment]
Hey there. I'm using mup (not mupx) and I'm still getting errors:

```
[138.197.101.26]=> Starting meteor app on port:80
[138.197.101.26]
[138.197.101.26]/bundle/bundle/programs/server/mini-files.js:74
[138.197.101.26]const unicodeNormalizePath = (path) => {
[138.197.101.26]                                     ^
[138.197.101.26]SyntaxError: Unexpected token >
[138.197.101.26]    at Module._compile (module.js:439:25)
[138.197.101.26]    at Object.Module._extensions..js (module.js:474:10)
[138.197.101.26]    at Module.load (module.js:356:32)
[138.197.101.26]    at Function.Module._load (module.js:312:12)
[138.197.101.26]    at Module.require (module.js:364:17)
[138.197.101.26]    at require (module.js:380:17)
[138.197.101.26]    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:9:13)
[138.197.101.26]    at Module._compile (module.js:456:26)
[138.197.101.26]    at Object.Module._extensions..js (module.js:474:10)
[138.197.101.26]    at Module.load (module.js:356:32)
```
I'm using node version 6.10.0. Meteor 1.4.3.2. Do I need a different version of Node?

**Comment by zodern** [comment]
@abeaudoin2013 what dockerImage is in your config? If you are using meteor 1.4, it should be `abernix/meteord:base`

**Comment by abeaudoin2013** [comment]
Yes, changed that to ```abernix/meteord:base```, but now I'm getting this error: 

```
[138.197.101.26]npm ERR! Linux 4.4.0-70-generic
[138.197.101.26]npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
[138.197.101.26]npm ERR! node v4.8.0
[138.197.101.26]npm ERR! npm  v3.10.10
[138.197.101.26]npm ERR! code ELIFECYCLE
[138.197.101.26]npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
[138.197.101.26]npm ERR! Exit status 1
[138.197.101.26]npm ERR! 
[138.197.101.26]npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
[138.197.101.26]npm ERR! Make sure you have the latest version of node.js and npm installed.
[138.197.101.26]npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
[138.197.101.26]npm ERR! not with npm itself.
[138.197.101.26]npm ERR! Tell the author that this fails on your system:
[138.197.101.26]npm ERR!     node npm-rebuild.js
[138.197.101.26]npm ERR! You can get information on how to open an issue for this project with:
[138.197.101.26]npm ERR!     npm bugs meteor-dev-bundle
[138.197.101.26]npm ERR! Or if that isn't available, you can get their info via:
[138.197.101.26]npm ERR!     npm owner ls meteor-dev-bundle
[138.197.101.26]npm ERR! There is likely additional logging output above.
[138.197.101.26]
[138.197.101.26]npm ERR! Please include the following file with any support request:
[138.197.101.26]npm ERR!     /bundle/bundle/programs/server/npm-debug.log
```

**Comment by rclai** [comment]
I'm having the same problem and I have the right Docker image in place, but my error instead says:

```
/root/.meteor/packages/meteor-tool/.1.4.4_1.1t9hste++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/cli/main.js:1487
}).run();
   ^

SyntaxError: Unexpected token y
    at Object.parse (native)
    at /tools/cli/main.js:803:12

=> Build Error. Check the logs printed above.
Error: build-error
    at ChildProcess.<anonymous> (/root/.nvm/versions/node/v6.10.2/lib/node_modules/mup/lib/modules/meteor/build.js:46:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

If I try to build using the `meteor` CLI, it works fine, just not with `mup` unfortunately.
