### ISSUE TITLE
Meteor mup deploy error

### ISSUE THREAD

**Issue by iAssureIT** [zodern/meteor-up#524]
I am deploying simple meteor app on AWS EC2 Ubuntu server. I did **mup setup** command. It worked fine. 
But I am getting following error on **mup deploy** command, as follows. Need urgent help on this. 

```
Building App Bundle Locally
{ cwd: '/var/meteor/test' }
{ Error: spawn meteor ENOENT
    at exports._errnoException (util.js:1033:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn meteor',
  path: 'meteor',
  spawnargs:
   [ 'build',
     '--directory',
     '/tmp/35617308-d87e-47aa-a4b1-e6dfba69105e',
     '--architecture',
     'os.linux.x86_64',
     '--server-only' ] }

=> Build Error. Check the logs printed above.
(node:11152) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build-error
(node:11152) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Node  v7.7.6
NPM  v4.1.2

My mup.js file is as follows: 

```
module.exports = {
  servers: {
    one: {
      host: '35.xxx.xxx.xxx',
      username: 'ubuntu',
      pem: '~/.ssh/Ubuntu-key.pem',
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'test',
    path: '../../test',
    servers: {
      one: {},
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://musissive.in',
      MONGO_URL: 'mongodb://localhost/meteor',
    },


    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
    },
    deployCheckWaitTime: 60,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: false
  },

  mongo: {
    oplog: true,
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {},
    },
  },
};

```

**Comment by zodern** [comment]
The spawn error usually happens when meteor is not installed, or your path to the app is incorrect.

**Comment by iAssureIT** [comment]
Thank you for quick reply zodern! 
I was following some tutorials over internet for meteor deploy. I did install nodejs, npm and mup. Thought that should be sufficient. But now I installed meteor & mongodb on ubuntu server like 

`curl https://install.meteor.com | /bin/sh`

`sudo apt-get install mongodb`

Now I tried again **mup setup** and **mup deploy** commands. Again got different type of error on deploy command. 

What must be causing this error? This is standard meteor app created by meteor on my development machine. Then I uploaded it on ubuntu server. 

```
Building App Bundle Locally
/home/ubuntu/.meteor/packages/meteor-tool/.1.4.3_1.194k2uz++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: EISDIR: illegal operation on a directory, unlink '/var/meteor/test/.meteor/local/dev_bundle'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at exports.makeLink (/tools/cli/dev-bundle-links.js:20:8)
    at [object Object]._.extend.ensureDevBundleLink (/tools/project-context.js:1476:7)
    at [object Object]._.extend._readFile (/tools/project-context.js:1410:10)
    at new exports.ReleaseFile (/tools/project-context.js:1360:8)
    at /tools/cli/main.js:898:22

=> Build Error. Check the logs printed above.
(node:13417) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: build-error
(node:13417) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by zodern** [comment]
Try deleting everything in `/var/meteor/test/.meteor/local/dev_bundle`.

**Comment by iAssureIT** [comment]
zodern, you are simply great! 
I deleted everything that started with dev_dundle (1 directory & 3 files found) in .meteor/local. 
Now '**meteor deploy**' command worked successfully. 

Thank you very very much, zodern!

**Comment by zodern** [comment]
I'm glad you got it working!

I added a section about the spawn error to the troubleshooting guide in the readme.
