### ISSUE TITLE
deploying problem

### ISSUE THREAD

**Issue by maxlibin** [zodern/meteor-up#535]
can anyone help me take a look why when i do mup deploy, I received these error?
Verifying Deployment: FAILED

```
	-----------------------------------STDERR-----------------------------------
	all.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
	    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
	    - - - - -
	    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
	    at emitOne (events.js:77:13)
	    at [object Object].emit (events.js:169:7)
	    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:260:12)
	    at [object Object].g (events.js:260:16)
	    at emitTwo (events.js:87:13)
	    at [object Object].emit (events.js:172:7)
	    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
	    at Socket.g (events.js:260:16)
	    at emitOne (events.js:77:13)

	=> Redeploying previous version of the app

	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=50'

	----------------------------------------------------------------------------
(node:41409) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error:
-----------------------------------STDERR-----------------------------------
all.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at [object Object].g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at [object Object].emit (events.js:172:7)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
(node:41409) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

after stop and start aws again::

x copying mongodb.conf: FAILED
	Failure
(node:42301) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failure
(node:42301) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 x Copying SSL Certificate Bundle: FAILED

**Comment by zodern** [comment]
You are using an old version of meteor-up. Please update by running `npm i -g mup`

**Comment by zodern** [comment]
@maxlibin are you still having problems?

**Comment by maxlibin** [comment]
sorry, the problem is program getting bigger and bigger so deploy failed.
