### ISSUE TITLE
Error response from daemon: endpoint [appname] not found

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#544]

**Comment by zodern** [comment]
`Endpoint not found` is normal.

The real problem is `Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use`. Are you deploying multiple apps to the server, or do you have something else running using port 80?

**Comment by SidSyed** [comment]
I had an nginx server running so I stopped it and this is the error I'm getting now:

```x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        t new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
            at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
            at fileEvaluate (packages/modules-runtime.js:197:9)
            at require (packages/modules-runtime.js:120:16)
            at /bundle/bundle/programs/server/packages/accounts-base.js:2019:15
            at /bundle/bundle/programs/server/packages/accounts-base.js:2030:3

        > meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
        > node npm-rebuild.js

        {
          "meteor-dev-bundle": "0.0.0",
          "npm": "3.10.10",
          "ares": "1.10.1-DEV",
          "http_parser": "2.7.0",
          "icu": "56.1",
          "modules": "46",
          "node": "4.8.0",
          "openssl": "1.0.2k",
          "uv": "1.9.1",
          "v8": "4.5.103.45",
          "zlib": "1.2.8"
        }
        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.
        => Starting meteor app on port:80

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=50'

        ----------------------------------------------------------------------------```

**Comment by zodern** [comment]
Looks like it is missing part of the error message. Do you get the whole error when running `mup logs --tail=200`?

**Comment by SidSyed** [comment]
[149.56.140.165]    at fileEvaluate (packages/modules-runtime.js:197:9)
[149.56.140.165]    - - - - -
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]    at [object Object].emit (events.js:169:7)
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
[149.56.140.165]    at [object Object].g (events.js:260:16)
[149.56.140.165]    at emitTwo (events.js:87:13)
[149.56.140.165]    at [object Object].emit (events.js:172:7)
[149.56.140.165]    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
[149.56.140.165]    at Socket.g (events.js:260:16)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]
[149.56.140.165]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[149.56.140.165]> node npm-rebuild.js
[149.56.140.165]
[149.56.140.165]{
[149.56.140.165]  "meteor-dev-bundle": "0.0.0",
[149.56.140.165]  "npm": "3.10.10",
[149.56.140.165]  "ares": "1.10.1-DEV",
[149.56.140.165]  "http_parser": "2.7.0",
[149.56.140.165]  "icu": "56.1",
[149.56.140.165]  "modules": "46",
[149.56.140.165]  "node": "4.8.0",
[149.56.140.165]  "openssl": "1.0.2k",
[149.56.140.165]  "uv": "1.9.1",
[149.56.140.165]  "v8": "4.5.103.45",
[149.56.140.165]  "zlib": "1.2.8"
[149.56.140.165]}
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No description
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No license field.
[149.56.140.165]=> Starting meteor app on port:80
[149.56.140.165]
[149.56.140.165]/bundle/bundle/programs/server/node_modules/fibers/future.js:313
[149.56.140.165]                                                throw(ex);
[149.56.140.165]                                                ^
[149.56.140.165]MongoError: failed to connect to server [mongodb:27017] on first connect
[149.56.140.165]    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
[149.56.140.165]    at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
[149.56.140.165]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[149.56.140.165]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[149.56.140.165]    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
[149.56.140.165]    at new Mongo.Collection (packages/mongo/collection.js:99:40)
[149.56.140.165]    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
[149.56.140.165]    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
[149.56.140.165]    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
[149.56.140.165]    at fileEvaluate (packages/modules-runtime.js:197:9)
[149.56.140.165]    - - - - -
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]    at [object Object].emit (events.js:169:7)
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
[149.56.140.165]    at [object Object].g (events.js:260:16)
[149.56.140.165]    at emitTwo (events.js:87:13)
[149.56.140.165]    at [object Object].emit (events.js:172:7)
[149.56.140.165]    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
[149.56.140.165]    at Socket.g (events.js:260:16)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]
[149.56.140.165]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[149.56.140.165]> node npm-rebuild.js
[149.56.140.165]
[149.56.140.165]{
[149.56.140.165]  "meteor-dev-bundle": "0.0.0",
[149.56.140.165]  "npm": "3.10.10",
[149.56.140.165]  "ares": "1.10.1-DEV",
[149.56.140.165]  "http_parser": "2.7.0",
[149.56.140.165]  "icu": "56.1",
[149.56.140.165]  "modules": "46",
[149.56.140.165]  "node": "4.8.0",
[149.56.140.165]  "openssl": "1.0.2k",
[149.56.140.165]  "uv": "1.9.1",
[149.56.140.165]  "v8": "4.5.103.45",
[149.56.140.165]  "zlib": "1.2.8"
[149.56.140.165]}
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No description
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No license field.
[149.56.140.165]=> Starting meteor app on port:80
[149.56.140.165]
[149.56.140.165]/bundle/bundle/programs/server/node_modules/fibers/future.js:313
[149.56.140.165]                                                throw(ex);
[149.56.140.165]                                                ^
[149.56.140.165]MongoError: failed to connect to server [mongodb:27017] on first connect
[149.56.140.165]    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
[149.56.140.165]    at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
[149.56.140.165]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[149.56.140.165]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[149.56.140.165]    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
[149.56.140.165]    at new Mongo.Collection (packages/mongo/collection.js:99:40)
[149.56.140.165]    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
[149.56.140.165]    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
[149.56.140.165]    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
[149.56.140.165]    at fileEvaluate (packages/modules-runtime.js:197:9)
[149.56.140.165]    - - - - -
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]    at [object Object].emit (events.js:169:7)
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
[149.56.140.165]    at [object Object].g (events.js:260:16)
[149.56.140.165]    at emitTwo (events.js:87:13)
[149.56.140.165]    at [object Object].emit (events.js:172:7)
[149.56.140.165]    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
[149.56.140.165]    at Socket.g (events.js:260:16)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]
[149.56.140.165]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[149.56.140.165]> node npm-rebuild.js
[149.56.140.165]
[149.56.140.165]{
[149.56.140.165]  "meteor-dev-bundle": "0.0.0",
[149.56.140.165]  "npm": "3.10.10",
[149.56.140.165]  "ares": "1.10.1-DEV",
[149.56.140.165]  "http_parser": "2.7.0",
[149.56.140.165]  "icu": "56.1",
[149.56.140.165]  "modules": "46",
[149.56.140.165]  "node": "4.8.0",
[149.56.140.165]  "openssl": "1.0.2k",
[149.56.140.165]  "uv": "1.9.1",
[149.56.140.165]  "v8": "4.5.103.45",
[149.56.140.165]  "zlib": "1.2.8"
[149.56.140.165]}
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No description
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No license field.
[149.56.140.165]=> Starting meteor app on port:80
[149.56.140.165]
[149.56.140.165]/bundle/bundle/programs/server/node_modules/fibers/future.js:313
[149.56.140.165]                                                throw(ex);
[149.56.140.165]                                                ^
[149.56.140.165]MongoError: failed to connect to server [mongodb:27017] on first connect
[149.56.140.165]    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
[149.56.140.165]    at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
[149.56.140.165]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[149.56.140.165]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[149.56.140.165]    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
[149.56.140.165]    at new Mongo.Collection (packages/mongo/collection.js:99:40)
[149.56.140.165]    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
[149.56.140.165]    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
[149.56.140.165]    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
[149.56.140.165]    at fileEvaluate (packages/modules-runtime.js:197:9)
[149.56.140.165]    - - - - -
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]    at [object Object].emit (events.js:169:7)
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
[149.56.140.165]    at [object Object].g (events.js:260:16)
[149.56.140.165]    at emitTwo (events.js:87:13)
[149.56.140.165]    at [object Object].emit (events.js:172:7)
[149.56.140.165]    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
[149.56.140.165]    at Socket.g (events.js:260:16)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]
[149.56.140.165]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[149.56.140.165]> node npm-rebuild.js
[149.56.140.165]
[149.56.140.165]{
[149.56.140.165]  "meteor-dev-bundle": "0.0.0",
[149.56.140.165]  "npm": "3.10.10",
[149.56.140.165]  "ares": "1.10.1-DEV",
[149.56.140.165]  "http_parser": "2.7.0",
[149.56.140.165]  "icu": "56.1",
[149.56.140.165]  "modules": "46",
[149.56.140.165]  "node": "4.8.0",
[149.56.140.165]  "openssl": "1.0.2k",
[149.56.140.165]  "uv": "1.9.1",
[149.56.140.165]  "v8": "4.5.103.45",
[149.56.140.165]  "zlib": "1.2.8"
[149.56.140.165]}
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No description
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[149.56.140.165]npm WARN meteor-dev-bundle@0.0.0 No license field.
[149.56.140.165]=> Starting meteor app on port:80
[149.56.140.165]
[149.56.140.165]/bundle/bundle/programs/server/node_modules/fibers/future.js:313
[149.56.140.165]                                                throw(ex);
[149.56.140.165]                                                ^
[149.56.140.165]MongoError: failed to connect to server [mongodb:27017] on first connect
[149.56.140.165]    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
[149.56.140.165]    at new MongoConnection (packages/mongo/mongo_driver.js:217:27)
[149.56.140.165]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[149.56.140.165]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[149.56.140.165]    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
[149.56.140.165]    at new Mongo.Collection (packages/mongo/collection.js:99:40)
[149.56.140.165]    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
[149.56.140.165]    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
[149.56.140.165]    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
[149.56.140.165]    at fileEvaluate (packages/modules-runtime.js:197:9)
[149.56.140.165]    - - - - -
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:325:35)
[149.56.140.165]    at emitOne (events.js:77:13)
[149.56.140.165]    at [object Object].emit (events.js:169:7)
[149.56.140.165]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
[149.56.140.165]    at [object Object].g (events.js:260:16)
[149.56.140.165]    at emitTwo (events.js:87:13)
[149.56.140.165]    at [object Object].emit (events.js:172:7)
[149.56.140.165]    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:173:49)
[149.56.140.165]    at Socket.g (events.js:260:16)
[149.56.140.165]    at emitOne (events.js:77:13)

**Comment by zodern** [comment]
Run `mup docker ps`, and make check that there is a running mongo container and it is exposing port 27017.

**Comment by SidSyed** [comment]
Thanks for all the help so far.
I'm getting 
`error unknown command ps`
Perhaps we can click up on discord or something that allows for quicker messaging?

**Comment by zodern** [comment]
I created a room on Gitter: https://gitter.im/meteor-up/Lobby. 

> I'm getting
error unknown command ps

It is a newer command. You probably need to update mup with `npm i -g mup`.

**Comment by ghost** [comment]
@zodern @SadekSyed I have the same problem. How did you resolve it?

**Comment by SadekSyed** [comment]
I rewrote my code in express.

I know that isn't the response you wanted to hear. Sorry /:
