### ISSUE TITLE
Error when deploying to Digital Ocean and Mongo DB in Compose

### ISSUE THREAD

**Issue by jerocosio** [zodern/meteor-up#557]
Hi, so it has been a while since I updated my app so today I updated to the latest version of Meteor (1.4.3.2) and MUP (1.2.5), and tried to make a deploy to my droplet on Digital Ocean but I'm having trouble with MUP, when I try to deploy to the server I'm receiving this error:

```
[192.241.224.96] x Verifying Deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	          Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	curl: (52) Empty reply from server
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=50'
	
	----------------------------------------------------------------------------
```

when I tried to acces the logs using 'mup logs --tail=50' at first I didn't receive anything, but after a few minutes I got this error:

```
[192.241.224.96]=> Starting meteor app on port:80
[192.241.224.96]
[192.241.224.96]/bundle/bundle/programs/server/node_modules/fibers/future.js:313
[192.241.224.96]						throw(ex);
[192.241.224.96]						^
[192.241.224.96]MongoError: no primary found in replicaset
[192.241.224.96]    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
[192.241.224.96]    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
[192.241.224.96]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[192.241.224.96]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[192.241.224.96]    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
[192.241.224.96]    at new Mongo.Collection (packages/mongo/collection.js:99:40)
[192.241.224.96]    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
[192.241.224.96]    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
[192.241.224.96]    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
[192.241.224.96]    at fileEvaluate (packages/modules-runtime.js:197:9)
[192.241.224.96]    - - - - -
[192.241.224.96]    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:524:28
[192.241.224.96]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:303:24)
[192.241.224.96]    at [object Object].g (events.js:260:16)
[192.241.224.96]    at emitOne (events.js:77:13)
[192.241.224.96]    at [object Object].emit (events.js:169:7)
[192.241.224.96]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:326:21)
[192.241.224.96]    at emitOne (events.js:77:13)
[192.241.224.96]    at [object Object].emit (events.js:169:7)
[192.241.224.96]    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
[192.241.224.96]    at [object Object].g (events.js:260:16)
```

My mup.js files is:

```
module.exports = {
  servers: {
    one: {
      "host": "xxx.xxx.xxx",
      "username": "xxx",
      "password": "xxx"
    }
  },

  meteor: {
    name: 'vnoAdmin',
    path: '../vnoAdmin',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      "ROOT_URL": "https://xxx.xxx.com",
      "MONGO_URL": "mongodb://xxx:yyy@c146.alcatraz.0.mongolayer.com:10146,alcatraz.1.mongolayer.com:10146/mongovynodb?replicaSet=set-xxx&readPreference=primaryPreferred",
    },

    docker: {
      image: 'abernix/meteord:base', // use this image if using Meteor 1.4+
      // (optional) Only used if using your own ssl certificates. Default is "meteorhacks/mup-frontend-server"
      imageFrontendServer: 'meteorhacks/mup-frontend-server',
    },
    deployCheckWaitTime: 60,
    enableUploadProgressBar: true
  },

};
```

I have searched and tried everything with no luck, do anyone has a good recomendation?

**Comment by jerocosio** [comment]
It was a problem with the URL I was using on the MONGO_URL, it was wrong and had some extra characters.

**Comment by thearabbit** [comment]
You solved already? Pl share
