### ISSUE TITLE
Docker not stable

### ISSUE THREAD

**Issue by PolGuixe** [zodern/meteor-up#570]
I just had a weird experience. I was running a meteor app in an EC2 instance. The instance was stopped without notification.

I start it again. Checked if the docker image was on. I checked it several times with `docker ps` and the `STATUS` field was never bigger than 30 seconds. The `CONTAINER ID`, was always the same. It seemed like docker was rebooting the container.

I just launched a new instance and deployed there and is working fine. 

Has anyone experienced something similar?

**Comment by zodern** [comment]
Did the app's logs show if app crashed or any indication on why it restarted?

**Comment by tomtom87** [comment]
@PolGuixe what size EC2 instance are you using, I had similar issues until using a medium

**Comment by PolGuixe** [comment]
@tomtom87 this was using a t2.micro.

@zodern I am investigating the logs. ;)

**Comment by tomtom87** [comment]
@PolGuixe I have to use t2.medium to get it to work. just get strange errors like yours from docker otherwise

**Comment by PolGuixe** [comment]
Do you think the problem is with memory? or disk space?

**Comment by PolGuixe** [comment]
These are the logs I am getting: 

```
=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
[object Object]
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/future.js:278
						throw(ex);
						      ^
[object Object]
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /bundle/bundle/programs/server/packages/accounts-base.js:1814:4
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
=> Starting meteor app on port:80
```

It's strange because it used to work without problems

**Comment by avishaan** [comment]
@PolGuixe try setting up a swap file on your instance and then trying it. I had a similar issue on DO due to insufficient memory

**Comment by tomtom87** [comment]
@PolGuixe yes run the medium size and you must set a swap file
