### ISSUE TITLE
mobileSettings not working?

### ISSUE THREAD

**Issue by tormodboga** [zodern/meteor-up#629]
If I leave the default mobileSettings and set serverOnly to false, I get the following error when deploying:

```
Error: ENOENT: no such file or directory, open '{"yourMobileSetting":"setting value"}'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.wrapper [as readFile] (/tools/fs/files.js:1586:35)
    at CordovaBuilder.copyWWW (/tools/cordova/builder.js:382:24)
    at CordovaProject.prepareFromAppBundle (/tools/cordova/project.js:196:13)
    at /tools/cli/commands.js:1000:24
    at /tools/utils/buildmessage.js:359:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/cli/commands.js:991:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.main.captureAndExit (/tools/cli/main.js:273:29)
    at buildCommand (/tools/cli/commands.js:990:10)
    at Command.func (/tools/cli/commands.js:824:12)
    at /tools/cli/main.js:1483:23
```

It seems that Cordova is expecting a filename to open, not an object?
Anyone else found out how to make this work?

If I remove the mobileSettings, it will look for the default settings.json file, but I don't want to use that..

I am using mup version 1.2.8 and Meteor version 1.5 (same issue on 1.4.4.2 as well)

**Comment by zodern** [comment]
I will close this in favor of #929
