### ISSUE TITLE
MongoError: no mongos proxy available

### ISSUE THREAD

**Issue by kdekooter** [zodern/meteor-up#649]
How can one connect to an existing external MongoDB cluster?

Application startup fails with the following:

```
/bundle/bundle/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: no mongos proxy available
    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:211:27)
    at [object Object]._.extend._startTailing (packages/mongo/oplog_tailing.js:200:33)
    at new OplogHandle (packages/mongo/oplog_tailing.js:76:8)
    at new MongoConnection (packages/mongo/mongo_driver.js:214:25)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
    at new Mongo.Collection (packages/mongo/collection.js:99:40)
    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
    - - - - -
    at [object Object]._onTimeout (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/mongos.js:636:28)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by kdekooter** [comment]
I found the flaw: the MONGO_OPLOG_URL needs the replicaSet to be set explicity
