### ISSUE TITLE
Bind for 0.0.0.0:8001 failed: port is already allocated.

### ISSUE THREAD

**Issue by kayrules** [zodern/meteor-up#67]
```
Error: 
-----------------------------------STDERR-----------------------------------
sudo: unable to resolve host Neur0n
sudo: unable to resolve host Neur0n
sudo: unable to resolve host Neur0n
sudo: unable to resolve host Neur0n
sudo: unable to resolve host Neur0n
Failed to remove container (playroom-frontend): Error response from daemon: No such container: playroom-frontend
docker: Error response from daemon: failed to create endpoint playroom on network bridge: Bind for 0.0.0.0:8001 failed: port is already allocated.
-----------------------------------STDOUT-----------------------------------
playroom
base: Pulling from meteorhacks/meteord
518dc1482465: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
537c534356b6: Already exists
b65a0e1e554b: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
Digest: sha256:b5a4f6efa98e4070792ed36d33b14385a28e6ceda691a492ee5b9f2431b1515a
Status: Image is up to date for meteorhacks/meteord:base
8ccfd7d6d2c2ba0c672d0d4e38bb867caaeac8e5b9abba394ca26f018cc6f518
----------------------------------------------------------------------------
    at /Users/kayrules/Downloads/meteor-up/node_modules/nodemiral/lib/coreTasks.js:39:16
    at /Users/kayrules/Downloads/meteor-up/node_modules/nodemiral/lib/session.js:146:9
    at Channel.<anonymous> (/Users/kayrules/Downloads/meteor-up/node_modules/nodemiral/lib/ssh.js:125:9)
    at emitOne (events.js:78:13)
    at Channel.emit (events.js:170:7)
    at SSH2Stream.<anonymous> (/Users/kayrules/Downloads/meteor-up/node_modules/nodemiral/node_modules/ssh2/lib/Channel.js:124:14)
    at SSH2Stream.g (events.js:261:16)
    at emitNone (events.js:68:13)
    at SSH2Stream.emit (events.js:167:7)
    at parsePacket (/Users/kayrules/Downloads/meteor-up/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3435:10)
    at SSH2Stream._transform (/Users/kayrules/Downloads/meteor-up/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:552:13)
    at SSH2Stream.Transform._read (_stream_transform.js:168:10)
    at SSH2Stream._read (/Users/kayrules/Downloads/meteor-up/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
    at SSH2Stream.Transform._write (_stream_transform.js:156:12)
    at doWrite (_stream_writable.js:293:12)
    at writeOrBuffer (_stream_writable.js:279:5)
```

I had this issue when re-run `mup deploy` to a previously deployed project on port 8001. `mup setup` successfully run without any issue. Killing the port running on host & kill docker process with the same port and then re-run `mup deploy` solved the issue.

```
$ docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                      PORTS                        NAMES
77212422859e        meteorhacks/meteord:base   "/bin/sh -c 'bash $ME"   15 minutes ago      Created                                                  playroom
a2a546e109d8        mongo                      "/entrypoint.sh mongo"   29 minutes ago      Up 29 minutes               127.0.0.1:27017->27017/tcp   mongodb
2b0b06d8dbcc        83d6a4b61a93               "/bin/sh -c 'bash $ME"   52 minutes ago      Exited (1) 52 minutes ago                                sleepy_kilby
08fc9527b72e        83d6a4b61a93               "/bin/sh -c 'bash $ME"   53 minutes ago      Exited (1) 53 minutes ago                                cocky_liskov
2906fa63680e        83d6a4b61a93               "/bin/sh -c 'bash $ME"   53 minutes ago      Exited (1) 53 minutes ago                                compassionate_banach
fe3b1e1456d3        meteorhacks/meteord:base   "/bin/sh -c 'bash $ME"   4 days ago          Up 56 minutes               0.0.0.0:8001->80/tcp         webeme
92e60fb906f4        meteorhacks/meteord:base   "/bin/sh -c 'bash $ME"   5 days ago          Up 56 minutes               0.0.0.0:8002->80/tcp         webeme-prototype
$
$ docker kill fe3b1e1456d3
```

**Comment by madushan1000** [comment]
Is this from the old `mupx` or this version? Did you change the app name between the deployments?

**Comment by kayrules** [comment]
this is from this version. yes, I did changed the name. Was it caused by the name change?

**Comment by madushan1000** [comment]
Yeah, We use app name to recognize the docker container while redeploying. This error comes up because mup can't figure out which container is bounded to your specified port.

**Comment by kayrules** [comment]
Thanks @madushan1000. Noted on this.

**Comment by iboxgithub** [comment]
Hi, 

thanks for the information, nevertheless how would you do to deploy 2 apps on the same server in this case? My first app deployment works perfect but when I try to deploy the second I have the same kind of error

> Error response from daemon: No such container: cryptarbot-frontend
> docker: Error response from daemon: driver failed programming external connectivity on endpoint myapp2 (998e60614eb8cd5ccbfe91432971b80bb11dbf1913b48999205e7bb4060a20a9): Bind for 0.0.0.0:80 failed: port is already allocated.

when I run

>  netstat -tulpn

 I have 
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 10.0.3.1:53             0.0.0.0:*               LISTEN      14232/dnsmasq   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1626/sshd       
tcp6       0      0 :::80                   :::*                    LISTEN      17005/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1626/sshd       
udp        0      0 10.0.3.1:53             0.0.0.0:*                           14232/dnsmasq   
udp        0      0 0.0.0.0:67              0.0.0.0:*                           14232/dnsmasq   
```

I am using kadirahq/meteor-up

Thanks for your help
