### ISSUE TITLE
Frequent server crashes and auto-restarts with "Error: expected to be _runningOrRunScheduled"

### ISSUE THREAD

**Issue by derwaldgeist** [zodern/meteor-up#676]
Since I upgraded from Meteor 1.2 to 1.5 and thus from `mupx` to this `mup`, I noticed a lot of situations when the server crashes arbitrarily and re-starts itself. This is noticable only because it takes way longer until a request finished.

A couple of minutes ago, this occurred again, right after I started the server after a fresh deploy, so I could capture the situation. In the logs I found this (excerpt at the point where it crashes):

```
{"line":"106","file":"percolate_migrations.js","message":"Migrations: Finished migrating.","time":{"$date":1501089989174},"level":"info"}
/bundle/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: expected to be _runningOrRunScheduled
    at [object Object]._.extend._run (packages/meteor.js:797:13)
    at packages/meteor.js:789:14

> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
> node npm-rebuild.js


> bcrypt@1.0.2 install /bundle/bundle/programs/server/npm/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/bundle/bundle/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote
abbrev@1.1.0 /bundle/bundle/programs/server/npm/node_modules/abbrev
```

The first line is the last log message from the server when it was started for the first time.

The exception to occurred when I did some stuff in the app, and the following lines are the first messages of the auto-restarted server.

What may cause these crashes with `Error: expected to be _runningOrRunScheduled`?

Update: These errors seem to be related to sending either e-mails or push notifications. Sometimes, the server restarts multiple times (10 or so) after such an action. I also tried to run it with `debug: true`, but this didn't yield more information in the logs.

**Comment by derwaldgeist** [comment]
I now had the problem with the local dev server, too. So it is not related to `mup`. Closing this, sorry for bothering.
