### ISSUE TITLE
fibers.node is missing

### ISSUE THREAD

**Issue by ahmay98** [zodern/meteor-up#68]
I'm trying to deploy meteor 1.3 beta 12.

Got the following log on 'mup deploy' --

[198.199.98.76]npm WARN deprecated This version of npm lacks support for important features,
[198.199.98.76]npm WARN deprecated such as scoped packages, offered by the primary npm
[198.199.98.76]npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
[198.199.98.76]npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
[198.199.98.76]npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
[198.199.98.76]npm WARN package.json meteor-dev-bundle@0.0.0 No description
[198.199.98.76]npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[198.199.98.76]npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[198.199.98.76]=> Starting meteor app on port:80
[198.199.98.76]
[198.199.98.76]/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
[198.199.98.76] throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
[198.199.98.76]Error:`/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`is missing. Try reinstalling`node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by madushan1000** [comment]
It looks like this is an issue with meteor-1.3-beta-x with meteord. Take a look at this issue thread https://github.com/meteorhacks/meteord/issues/78

**Comment by madushan1000** [comment]
I'm closing this since this is not an issue with mup.
