### ISSUE TITLE
mup.js deployment failed, database names cannot contain the character '.'

### ISSUE THREAD

**Issue by gurjit03** [zodern/meteor-up#688]
I don't have any `.` dot character in my `DB name` and it has been causing issues to deploy the app. 
The application is working charm on my local system.
Below is my mup.js file.
```
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '45.79.94.190',
      username: 'root',
     // pem: './path/to/pem'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  meteor: {
    // TODO: change app name and path
    name: 'boomerplaza',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://boomerplaza.com',
      MONGO_URL: 'mongodb://localhost/meteor',
      PORT: 3000    
},

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma seperated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:base',
      // imagePort: 80, // (default: 80, some images EXPOSE different ports)
    },

    // This is the maximum time in seconds it will wait
    // for your app to start
    // Add 30 seconds if the server has 512mb of ram
    // And 30 more if you have binary npm dependencies.
    deployCheckWaitTime: 60,

    deployCheckPort: 3000,	

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```

Below is the error logs I get by `mup logs`
```
mup logs --tail=100
[45.79.94.190]  "http_parser": "2.7.0",
[45.79.94.190]  "icu": "56.1",
[45.79.94.190]  "modules": "46",
[45.79.94.190]  "node": "4.8.3",
[45.79.94.190]  "openssl": "1.0.2k",
[45.79.94.190]  "uv": "1.9.1",
[45.79.94.190]  "v8": "4.5.103.47",
[45.79.94.190]  "zlib": "1.2.11"
[45.79.94.190]}
[45.79.94.190]npm WARN meteor-dev-bundle@0.0.0 No description
[45.79.94.190]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[45.79.94.190]npm WARN meteor-dev-bundle@0.0.0 No license field.
[45.79.94.190]=> Starting meteor app on port:80
[45.79.94.190]
[45.79.94.190]/bundle/bundle/programs/server/node_modules/fibers/future.js:280
[45.79.94.190]						throw(ex);
[45.79.94.190]						^
[45.79.94.190]MongoError: database names cannot contain the character '.'
[45.79.94.190]    at Function.MongoError.create (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
[45.79.94.190]    at validateDatabaseName (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:1683:70)
[45.79.94.190]    at new Db (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:156:3)
[45.79.94.190]    at createServer (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:383:12)
[45.79.94.190]    at connect (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:516:12)
[45.79.94.190]    at Function.MongoClient.connect (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:246:3)
[45.79.94.190]    at new MongoConnection (packages/mongo/mongo_driver.js:169:11)
[45.79.94.190]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[45.79.94.190]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[45.79.94.190]    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
[45.79.94.190]
[45.79.94.190]> meteor-dev-bundle@0.0.0 install /bundle/bundle/programs/server
[45.79.94.190]> node npm-rebuild.js
[45.79.94.190]
[45.79.94.190]{
[45.79.94.190]  "meteor-dev-bundle": "0.0.0",
[45.79.94.190]  "npm": "3.10.10",
[45.79.94.190]  "ares": "1.10.1-DEV",
[45.79.94.190]  "http_parser": "2.7.0",
[45.79.94.190]  "icu": "56.1",
[45.79.94.190]  "modules": "46",
[45.79.94.190]  "node": "4.8.3",
[45.79.94.190]  "openssl": "1.0.2k",
[45.79.94.190]  "uv": "1.9.1",
[45.79.94.190]  "v8": "4.5.103.47",
[45.79.94.190]  "zlib": "1.2.11"
[45.79.94.190]}
[45.79.94.190]npm WARN meteor-dev-bundle@0.0.0 No description
[45.79.94.190]npm WARN meteor-dev-bundle@0.0.0 No repository field.
[45.79.94.190]npm WARN meteor-dev-bundle@0.0.0 No license field.
[45.79.94.190]=> Starting meteor app on port:80
[45.79.94.190]
[45.79.94.190]/bundle/bundle/programs/server/node_modules/fibers/future.js:280
[45.79.94.190]						throw(ex);
[45.79.94.190]						^
[45.79.94.190]MongoError: database names cannot contain the character '.'
[45.79.94.190]    at Function.MongoError.create (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
[45.79.94.190]    at validateDatabaseName (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:1683:70)
[45.79.94.190]    at new Db (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:156:3)
[45.79.94.190]    at createServer (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:383:12)
[45.79.94.190]    at connect (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:516:12)
[45.79.94.190]    at Function.MongoClient.connect (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongo_client.js:246:3)
[45.79.94.190]    at new MongoConnection (packages/mongo/mongo_driver.js:169:11)
[45.79.94.190]    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
[45.79.94.190]    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
[45.79.94.190]    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)

``` 

Any help is appreciated :pray:

**Comment by gurjit03** [comment]
It was the appname that was causing me the issues. so closing the issue now
