### ISSUE TITLE
Bcrypt/node-gyp issues

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#696]
I tried deploying multiple times and I kept running into issues with node-gyp:

```
gyp ERR! build error
	bcrypt_lib.target.mk:98: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt_node.o' failed
	make: Leaving directory '/bundle/bundle/programs/server/npm/node_modules/bcrypt/build'
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
	gyp ERR! stack     at emitTwo (events.js:87:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
	gyp ERR! System Linux 4.4.0-87-generic
	gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /bundle/bundle/programs/server/npm/node_modules/bcrypt
	gyp ERR! node -v v4.8.3
	gyp ERR! node-gyp -v v3.4.0
```

While looking at my `package.json` I realized that it included `bcrypt` directly as a dependency for some reason (my other Meteor projects don't). So I removed it, and deployment worked!

I thought I'd make a note of it in case it helps other people.

**Comment by elie222** [comment]
The reason to add it as a dependency is:
```
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

meteor npm install --save bcrypt

in the root directory of your application.
```
