### ISSUE TITLE
mup deployment fails contain name not lowercase

### ISSUE THREAD

**Issue by benjaminsweetnam247** [zodern/meteor-up#720]
I'm having trouble deploying atm I think it's because there is a capital in the name.

~/W/etaSms-update   development *  .deploy  mup deploy                                                                                                                                                    8.3s  Thu 31 Aug 10:47:25 2017
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[52.63.46.175] - Pushing Meteor App Bundle to The Server
[52.63.46.175] - Pushing Meteor App Bundle to The Server: SUCCESS
[52.63.46.175] - Prepare Bundle
[52.63.46.175] x Prepare Bundle: FAILED

	-----------------------------------STDERR-----------------------------------
	Error response from daemon: No such container: etaSms
	invalid argument "mup-etaSms:build" for t: invalid reference format: repository name must be lowercase
	See 'docker build --help'.
	Error response from daemon: No such container: etaSms
	Error: failed to start containers: etaSms
	-----------------------------------STDOUT-----------------------------------
	base: Pulling from abernix/meteord
	Digest: sha256:680d55194f4cce47dac3373ad54d7c3ca53e28e7c8f40d29ef43f82fa460da4b
	Status: Image is up to date for abernix/meteord:base
	----------------------------------------------------------------------------

**Comment by benjaminsweetnam247** [comment]
yea changing the name works but probably should look at converting names to all lower case to fix on deployment

**Comment by benjaminsweetnam247** [comment]
also ran into an issue with it recreating the database as It already exists but in a different case

MongoError: db already exists with different case already have: [etaSms] trying to create [etasms]
    at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:449:15)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:832:10)
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:677:20)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1493:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:51:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at /built_app/programs/server/packages/accounts-base.js:2031:15
    at /built_app/programs/server/packages/accounts-base.js:2042:3
    - - - - -
    at Function.MongoError.create (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at /built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/db.js:1083:80
    at /built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)

**Comment by zodern** [comment]
It will be fixed in 1.3.2.
