### ISSUE TITLE
New mup project: SyntaxError: Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by Falieson** [zodern/meteor-up#725]
I'm running `mup deploy` for the first time from a new project.

Meteor: METEOR@1.6-beta.24

*ERROR LOG*
```
Started TaskList: Start Meteor
[165.227.0.1] - Start Meteor
[165.227.0.1] - Start Meteor: SUCCESS
[165.227.0.1] - Verifying Deployment
[165.227.0.1] x Verifying Deployment: FAILED

	-----------------------------------STDERR-----------------------------------
	ay.forEach (native)
	    at Function._.each._.forEach (/built_app/programs/server/node_modules/underscore/underscore.js:79:11)
	    at /built_app/programs/server/boot.js:194:5
	    at /built_app/programs/server/boot.js:436:5
	    at Function.run (/built_app/programs/server/profile.js:510:12)
	    at /built_app/programs/server/boot.js:435:11
	=> Starting meteor app on port:9000
	/built_app/programs/server/packages/ejson.js:158
	    let sign;
	    ^^^

	SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
	    at /built_app/programs/server/boot.js:365:18
	    at Array.forEach (native)
	    at Function._.each._.forEach (/built_app/programs/server/node_modules/underscore/underscore.js:79:11)
	    at /built_app/programs/server/boot.js:194:5
	    at /built_app/programs/server/boot.js:436:5
	    at Function.run (/built_app/programs/server/profile.js:510:12)
	    at /built_app/programs/server/boot.js:435:11
	Error: No such image: mup-meteor-backend:previous
	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=100'

	----------------------------------------------------------------------------
```

*MUP.JSON*
```
module.exports = {
  servers: {
    one: {
      host: '165.227.0.1',
      username: 'root',
    }
  },
  app: {
    name: 'meteor-backend',
    path: '../',
    servers: {
      one: {
        env: {
          PORT: 9000
        }
      },
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://165.227.0.1',
      MONGO_URL: 'mongodb://localhost/meteor',
    },
    docker: {
      image: 'abernix/meteord:base',
    },
    enableUploadProgressBar: true
  },
  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```

**Comment by Falieson** [comment]
Seems like third times the charm... didn't have this issue after re-running `mup deploy`

**Comment by zodern** [comment]
What meteor version are you using?

**Comment by Falieson** [comment]
@zodern METEOR@1.6-beta.24 , thanks

**Comment by zodern** [comment]
Change the docker image in your config to `abernix/meteord:node-8.4.0-base`. It has the correct node version for Meteor 1.6.

**Comment by Falieson** [comment]
THANK YOU! 🎉

**Comment by Falieson** [comment]
@zodern that didn't fix it =(

https://github.com/zodern/meteor-up/issues/726
