### ISSUE TITLE
New mup project: Error: Can't find npm module 'common-tags'.

### ISSUE THREAD

**Issue by Falieson** [zodern/meteor-up#726]
Meteor: METEOR@1.6-beta.24

```
[165.227.10.224] - Verifying Deployment
[165.227.10.224] x Verifying Deployment: FAILED

	-----------------------------------STDERR-----------------------------------
	e (packages/modules-runtime.js:333:9)
	    at require (packages/modules-runtime.js:228:16)
	    at /built_app/programs/server/app/app.js:432:1
	=> Starting meteor app on port:9000
	/built_app/programs/server/node_modules/fibers/future.js:280
							throw(ex);
							^

	Error: Can't find npm module 'common-tags'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
	    at Object.require (/built_app/programs/server/boot.js:266:17)
	    at makeInstallerOptions.fallback (packages/modules-runtime.js:641:18)
	    at require (packages/modules-runtime.js:234:16)
	    at index.js (packages/modules.js:396:19)
	    at fileEvaluate (packages/modules-runtime.js:333:9)
	    at require (packages/modules-runtime.js:228:16)
	    at package-scripts.js (package-scripts.js:1:32)
	    at fileEvaluate (packages/modules-runtime.js:333:9)
	    at require (packages/modules-runtime.js:228:16)
	    at /built_app/programs/server/app/app.js:432:1

	=> Redeploying previous version of the app

	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=100'

	----------------------------------------------------------------------------
```

```
module.exports = {
  servers: {
    one: {
      host: '165.227.10.224',
      username: 'root',
    }
  },
  app: {
    name: 'meteor-backend',
    path: '/Users/sjcfmett/Code/web-admin/backend',
    servers: {
      one: {
        env: {
          PORT: 9000
        }
      },
    },
    buildOptions: {
      serverOnly: true,
    },
    env: {
      ROOT_URL: 'http://165.227.10.224',
      MONGO_URL: 'mongodb://localhost/meteor',
    },
    docker: {
      image: 'abernix/meteord:node-8.4.0-base',
    },
    enableUploadProgressBar: true
  },
  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```

**Comment by Falieson** [comment]
I've started an issue with meteord https://github.com/abernix/meteord/issues/21 since I've reproduced the error without MUP
