### ISSUE TITLE
Deploying 1.6.0 beta.30: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by thijssmudde** [zodern/meteor-up#748]
Meteor up doesn't seem to work with 1.6.0 beta.30.

```
- Verifying Deployment
- Verifying Deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	t Array.forEach (native)
	    at Function._.each._.forEach (/built_app/programs/server/node_modules/underscore/underscore.js:79:11)
	    at /built_app/programs/server/boot.js:194:5
	    at /built_app/programs/server/boot.js:437:5
	    at Function.run (/built_app/programs/server/profile.js:510:12)
	    at /built_app/programs/server/boot.js:436:11
	=> Starting meteor app on port:80
	/built_app/programs/server/packages/ejson.js:172
	    let sign;
	    ^^^
	
	SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
	    at /built_app/programs/server/boot.js:366:18
	    at Array.forEach (native)
	    at Function._.each._.forEach (/built_app/programs/server/node_modules/underscore/underscore.js:79:11)
	    at /built_app/programs/server/boot.js:194:5
	    at /built_app/programs/server/boot.js:437:5
	    at Function.run (/built_app/programs/server/profile.js:510:12)
	    at /built_app/programs/server/boot.js:436:11
	 
	=> Redeploying previous version of the app
	 
	-----------------------------------STDOUT-----------------------------------
	
	To see more logs type 'mup logs --tail=100'
	
	----------------------------------------------------------------------------
```

mup logs --tail 100 doesnt give more useful info

**Comment by zodern** [comment]
Change the docker image in your config to `abernix/meteord:node-8.4.0-base`. It has the correct node version of Meteor 1.6.
