### ISSUE TITLE
"Cannot find module" error on deploy

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#753]
My app starts fine locally, and I've previously been able to deploy it without any problems, but I'm now running into this error on `mup deploy`:

```
[45.55.57.152]=> Starting meteor app on port:80
[45.55.57.152]Note: you are using a pure-JavaScript implementation of bcrypt.
[45.55.57.152]While this implementation will work correctly, it is known to be
[45.55.57.152]approximately three times slower than the native implementation.
[45.55.57.152]In order to use the native implementation instead, run
[45.55.57.152]
[45.55.57.152]  meteor npm install --save bcrypt
[45.55.57.152]
[45.55.57.152]in the root directory of your application.
[45.55.57.152]/bundle/bundle/programs/server/node_modules/fibers/future.js:280
[45.55.57.152]						throw(ex);
[45.55.57.152]						^
[45.55.57.152]
[45.55.57.152]Error: Cannot find module 'meteor/vulcan:email'
[45.55.57.152]    at Function.Module._resolveFilename (module.js:325:15)
[45.55.57.152]    at Function.require.resolve (internal/module.js:16:19)
[45.55.57.152]    at Object.require (/bundle/bundle/programs/server/boot.js:225:32)
[45.55.57.152]    at makeInstallerOptions.fallback (packages/modules-runtime.js:641:18)
[45.55.57.152]    at require (packages/modules-runtime.js:234:16)
[45.55.57.152]    at meteorInstall.node_modules.meteor.zensroom.lib.modules.emails.js (packages/zensroom/lib/modules/emails.js:1:30)
[45.55.57.152]    at fileEvaluate (packages/modules-runtime.js:333:9)
[45.55.57.152]    at require (packages/modules-runtime.js:228:16)
[45.55.57.152]    at meteorInstall.node_modules.meteor.zensroom.lib.modules.index.js (packages/zensroom/lib/modules/index.js:1:298)
[45.55.57.152]    at fileEvaluate (packages/modules-runtime.js:333:9)
[45.55.57.152]    at require (packages/modules-runtime.js:228:16)
[45.55.57.152]    at meteorInstall.node_modules.meteor.zensroom.lib.server.main.js (packages/zensroom/lib/server/main.js:1:14)
[45.55.57.152]    at fileEvaluate (packages/modules-runtime.js:333:9)
[45.55.57.152]    at require (packages/modules-runtime.js:228:16)
[45.55.57.152]    at /bundle/bundle/programs/server/packages/zensroom.js:7696:15
[45.55.57.152]    at /bundle/bundle/programs/server/packages/zensroom.js:7702:3
[45.55.57.152]    at /bundle/bundle/programs/server/boot.js:339:34
[45.55.57.152]    at Array.forEach (native)
[45.55.57.152]    at Function._.each._.forEach (/bundle/bundle/programs/server/node_modules/underscore/underscore.js:79:11)
[45.55.57.152]    at /bundle/bundle/programs/server/boot.js:158:5
[45.55.57.152]    at /bundle/bundle/programs/server/boot.js:388:5
[45.55.57.152]    at Function.run (/bundle/bundle/programs/server/profile.js:510:12)
[45.55.57.152]
```

In this case, `vulcan:email` is a local package and the app can find it without any trouble locally. The only thing is that it's not in the main app repo, but in a separate directory loaded via the `METEOR_PACKAGE_DIRS` env variable. Could that be a problem?

Then again, so are every other [Vulcan](http://vulcanjs.org) packages in the app and they don't seem to be trigerring an error…?

**Comment by SachaG** [comment]
Turns out the fix was to add a dependency on that package inside the package that makes use of it. Pretty obvious, but the fact that it worked fine locally threw me off…
