### ISSUE TITLE
fresh deployment failing on meteor 1.2

### ISSUE THREAD

**Issue by chrisbutler** [zodern/meteor-up#766]
i can't deploy to a fresh environment on the latest version, following the getting started guide completely... what am i missing?

meteor 1.2, no node_modules

```
mup deploy --verbose
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[54.211.43.80] - Pushing Meteor App Bundle to The Server
[54.211.43.80] - Pushing Meteor App Bundle to The Server: SUCCESS
[54.211.43.80] - Prepare Bundle
base: Pulling from abernix/meteord
Digest: sha256:680d55194f4cce47dac3373ad54d7c3ca53e28e7c8f40d29ef43f82fa460da4b
Status: Image is up to date for abernix/meteord:base
Error response from daemon: No such container: mytlslink
Sending build context to Docker daemon  80.52MB
Step 1/7 : FROM abernix/meteord:base
# Executing 1 build trigger...
Step 1/1 : ENV NODE_VERSION ${NODE_VERSION:-4.8.3}
 ---> Using cache
 ---> 631a176c80e1
Step 2/7 : RUN mkdir /built_app
 ---> Using cache
 ---> 4d6385bffcdc
Step 3/7 : COPY ./ /built_app
...
 ---> Using cache
 ---> 4788514cf364
Step 7/7 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Running in 1eee96335a64

> fibers@1.0.5 install /built_app/programs/server/node_modules/fibers
> node ./build.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/built_app/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function 'v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)':
../src/fibers.cc:132:54: error: no matching function for call to 'v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)'
   return Signature::New(isolate, receiver, argc, argv);
                                                      ^
../src/fibers.cc:132:54: note: candidate is:
In file included from /root/.node-gyp/4.8.3/include/node/node.h:42:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/4.8.3/include/node/v8.h:4675:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/root/.node-gyp/4.8.3/include/node/v8.h:4675:27: note:   candidate expects 2 arguments, 4 provided
../src/fibers.cc: In function 'void uni::SetResourceConstraints(v8::Isolate*, v8::ResourceConstraints*)':
../src/fibers.cc:140:3: error: 'SetResourceConstraints' is not a member of 'v8'
   v8::SetResourceConstraints(isolate, constraints);
   ^
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   'uni::SetResourceConstraints'
  void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
       ^
../src/fibers.cc: In function 'v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)':
../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
fibers.target.mk:103: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: Leaving directory '/built_app/programs/server/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.0-1022-aws
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /built_app/programs/server/node_modules/fibers
gyp ERR! node -v v4.8.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
meteor-dev-bundle@0.0.0 /built_app/programs/server
+-- amdefine@1.0.0
+-- ansi-regex@0.2.1
+-- ansi-styles@1.1.0
+-- asap@2.0.3
+-- chalk@0.5.1
+-- eachline@2.3.3
+-- escape-string-regexp@1.0.3
+-- has-ansi@0.1.0
+-- meteor-promise@0.5.0
+-- promise@7.0.4
+-- semver@4.1.0
+-- source-map@0.1.32
+-- source-map-support@0.3.2
+-- strip-ansi@0.3.0
+-- supports-color@0.2.0
+-- type-of@2.0.1
`-- underscore@1.5.2

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 4.4.0-1022-aws
npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! node v4.8.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /built_app/programs/server/npm-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
Error response from daemon: No such container: mytlslink
Error: failed to start containers: mytlslink
[54.211.43.80] x Prepare Bundle: FAILED

	-----------------------------------STDERR-----------------------------------
	Error response from daemon: No such container: mytlslink
	The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	Error response from daemon: No such container: mytlslink
	Error: failed to start containers: mytlslink
	-----------------------------------STDOUT-----------------------------------
	Linux 4.4.0-1022-aws
	npm ERR! argv "/opt/nodejs/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
	npm ERR! node v4.8.3
	npm ERR! npm  v3.10.10
	npm ERR! code ELIFECYCLE

	npm ERR! fibers@1.0.5 install: `node ./build.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the fibers package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node ./build.js
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs fibers
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls fibers
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /built_app/programs/server/npm-debug.log

	----------------------------------------------------------------------------
```

**Comment by chrisbutler** [comment]
so i found buried in the documentation this line about using a different docker image: https://github.com/zodern/meteor-up/blame/master/docs/docs.md#L114

would be great if this could be called out more prominently in the documentation

**Comment by zodern** [comment]
@chrisbutler it's now more prominent: http://meteor-up.com/docs#meteor-support

**Comment by chrisbutler** [comment]
thanks @zodern! 1.6 support?!?! 🎆
