### ISSUE TITLE
Error: connect ECONNREFUSED 192.168.100.12:22

### ISSUE THREAD

**Issue by MartiniHenry1988** [zodern/meteor-up#773]
I have a Meteor App based on Angular 1.3 + Meteor 1.5.2.2.
I am using Ubuntu 17.
I am trying to deploy my Meteor App on local machine first before going for live server.
But I am facing this issue when running `mup setup` command

```
martinihenry@martinihenry:~/mytestapp-prod/.deploy$ mup setup

Started TaskList: Setup Docker
[192.168.100.12] - Setup Docker
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.100.12:22
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)
```
Here is my mup.json:

```
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '192.168.100.12',
      username: 'root',
      // pem: './path/to/pem'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'mytestapp-prod',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: '192.168.100.12:3000',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma separated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      // change to 'kadirahq/meteord' if your app is using Meteor 1.3 or older
      image: 'abernix/meteord:base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```
What could be wrong here?

**Comment by zodern** [comment]
@MartiniHenry1988 are you able to ssh into the machine you are deploying to?

**Comment by pmogollons** [comment]
Hi,

Im having a similar issue using mup 1.3.3 and 1.3.5 (Havent tested in any more versions), where I get sometimes a EPIPE error and sometimes an ECONNRESET error

Im able to ssh to my server and looks like mup is also connecting to it, but it fails after it.

````
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[52.168.176.164] - Pushing Meteor App Bundle to The Server
[======                                 ] 17% 43.6sevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
````

````
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[52.168.176.164] - Pushing Meteor App Bundle to The Server
[===                                    ] 11% 46.1sevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)
````

**Comment by ghost** [comment]
I am also having the same issue with Meteor 1.6:
```
Started TaskList: Setup Docker
[192.168.1.104] - Setup Docker
events.js:110
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.1.104:5555
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1181:14)
```

mup.js 
```
module.exports = {
  servers: {
    one: {
      host: '192.168.1.104',
      username: 'gabriel',
      password: 'gabriel',
      opts: {
        port: 5555
      }
    }
  },

  app: {
    name: 'ReportApp',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'http://reportapp.com',
      MONGO_URL: 'mongodb://localhost/meteor',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
    },

    docker: {
      image: 'abernix/meteord:base',
    },

    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  },
};
```

**Comment by lc3t35** [comment]
Same for me but only with proxy option, pass if I comment proxy (which does not setup proxy)
````
mup setup --settings settings-staging.json 

Started TaskList: Setup Docker
[@] - Setup Docker
[@] - Setup Docker: SUCCESS

Started TaskList: Setup Meteor
[@] - Setup Environment
[@] - Setup Environment: SUCCESS

Started TaskList: Setup proxy
[@] - Setup Environment
[@] - Setup Environment: SUCCESS
[@] - Pushing the Startup Script
[@] - Pushing the Startup Script: SUCCESS
[@] - Pushing Nginx Config
[@] - Pushing Nginx Config: SUCCESS
[@] - Cleaning Up SSL Certificates
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED @:22
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
````
If I remove proxy option
````
Started TaskList: Setup Docker
[@] - Setup Docker
[@] - Setup Docker: SUCCESS

Started TaskList: Setup Meteor
[@] - Setup Environment
[@] - Setup Environment: SUCCESS

Started TaskList: Setup Mongo
[@] - Setup Environment
[@] - Setup Environment: SUCCESS
[@] - Copying mongodb.conf
[@] - Copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[@] - Start Mongo
[@] - Start Mongo: SUCCESS

Next, you should run:
    mup deploy
````
Here is proxy option in mup.js
````
//  proxy: {
//    domains: 'x.y.z',
//    ssl: {
//      letsEncryptEmail: 'a@b.c',
//    }
//  }
````

**Comment by lc3t35** [comment]
Workaround : 
````
1) remove proxy from config and deploy
2) mup deploy --settings settings-staging.json
3) add proxy in config file and setup proxy only
mup proxy setup
Started TaskList: Setup proxy
[@] - Setup Environment
[@] - Setup Environment: SUCCESS
[@] - Pushing the Startup Script
[@] - Pushing the Startup Script: SUCCESS
[@] - Pushing Nginx Config
[@] - Pushing Nginx Config: SUCCESS
[@] - Cleaning Up SSL Certificates
[@] - Cleaning Up SSL Certificates: SUCCESS

Started TaskList: Start proxy
[@] - Start proxy
[@] - Start proxy: SUCCESS
5) mup reconfig --settings settings-staging.json
Started TaskList: Configuring App
[@] - Pushing the Startup Script
[@] - Pushing the Startup Script: SUCCESS
[@] - Sending Environment Variables
[@] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[@] - Start Meteor
[@] - Start Meteor: SUCCESS
[@] - Verifying Deployment
[@] - Verifying Deployment: SUCCESS
````
For information mup proxy status fails too 
````
mup status
=> Servers
  - @: Ubuntu 16.04

=> Docker Status
 - @: 17.05.0-ce Running

=> Meteor Status
 - @: running 
    Created at 2018-03-14T23:14:42.482710285Z
    Restarted 0 times
    ENV: 
     - ROOT_URL=https:// ....
....
 - NODE_VERSION=8.4.0
    Exposed Ports:
     - 80/tcp
    App available through reverse proxy
     - Available in app's docker container: true
Error: connect ECONNREFUSED @:22
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
````

**Comment by lc3t35** [comment]
Hi, any news on that issue ?

**Comment by lc3t35** [comment]
It seems that the configuration of the server and especially ufw could be the cause of this.
I've setup the server with this guide : https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04
Then stopped nginx and apply
````
% mup reconfig --config ... --settings ...
Started TaskList: Configuring App
[x] - Pushing the Startup Script
[x] - Pushing the Startup Script: SUCCESS
[x] - Sending Environment Variables
[x6] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[x] - Start Meteor
[x] - Start Meteor: SUCCESS
[x] - Verifying Deployment
[x] - Verifying Deployment: SUCCESS

% mup proxy reconfig-shared --config ... --settings ...
Started TaskList: Configuring Proxy's Shared Settings
[x] - Sending shared variables
[x] - Sending shared variables: SUCCESS
[x] - Sending proxy environment variables
[x] - Sending proxy environment variables: SUCCESS
[x] - Sending let's encrypt environment variables
[x] - Sending let's encrypt environment variables: SUCCESS
[x] - Sending nginx config
[x] - Sending nginx config: SUCCESS

Started TaskList: Start proxy
[x] - Start proxy
[x] - Start proxy: SUCCESS

% mup proxy status --config ... --settings ...
=> Reverse Proxy Status
 - (x) :
   - NGINX:
     - Status: running
     - Ports:
       - HTTPS: 443
       - HTTP: 80
   - Let's Encrypt
     - Status: running

% mup restart --config ... --settings ...
Started TaskList: Restart Meteor
[x] - Stop Meteor
[x] - Stop Meteor: SUCCESS
[x] - Start Meteor
[x] - Start Meteor: SUCCESS
[x] - Verifying Deployment
[x] - Verifying Deployment: SUCCESS
````
All green !

**Comment by copleston** [comment]
I kept on receiving `Error: connect ECONNREFUSED` when it was trying to copy the certificate bundle. I checked the firewall status with `sudo ufw status` and saw this:

```
To                         Action      From
--                         ------      ----
22                         LIMIT       Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
22 (v6)                    LIMIT       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
```
`sudo ufw allow '22'` allowed my port 22 connection to persist, and presumably stop limiting the data flow when it was transferring some files.

```
To                         Action      From
--                         ------      ----
22                         ALLOW       Anywhere
80                         ALLOW       Anywhere
443                        ALLOW       Anywhere
22 (v6)                    ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
```
This fixed my problem!

**Comment by ebradbury** [comment]
Thanks @oliverjc.

In my case, I had to also removed a 'limit' ufw rule.

`ufw delete limit 22/tcp` then `ufw allow 22/tcp`
