### ISSUE TITLE
Deploy Error: Received exit code 0 while establishing SFTP session

### ISSUE THREAD

**Issue by teintinu** [zodern/meteor-up#78]
How interpret that error?

``` bash
$ mup deploy
Building App Bundle Locally

Started TaskList: Pushing Meteor
[54.232.209.247] - Pushing Meteor App Bundle to The Server
[54.94.234.103] - Pushing Meteor App Bundle to The Server
[54.94.234.103] x Pushing Meteor App Bundle to The Server: FAILED
    Received exit code 0 while establishing SFTP session
Error: Received exit code 0 while establishing SFTP session
    at Channel.onExit (/home/hoda51/zscan.aws/meteor-up/node_modules/ssh2/lib/client.js:757:19)
    at Channel.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Channel.emit (events.js:182:7)
    at SSH2Stream.<anonymous> (/home/hoda51/zscan.aws/meteor-up/node_modules/ssh2/lib/Channel.js:183:14)
    at emitOne (events.js:90:13)
    at SSH2Stream.emit (events.js:182:7)
    at parse_CHANNEL_REQUEST (/home/hoda51/zscan.aws/meteor-up/node_modules/ssh2-streams/lib/ssh.js:4356:8)
    at parsePacket (/home/hoda51/zscan.aws/meteor-up/node_modules/ssh2-streams/lib/ssh.js:3727:12)
    at SSH2Stream._transform (/home/hoda51/zscan.aws/meteor-up/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/home/hoda51/zscan.aws/meteor-up/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at SSH2Stream.Writable.write (_stream_writable.js:207:11)
```

the setup works well

``` bash
$ mup setup
Started TaskList: Setup Docker
[54.232.209.247] - setup docker
[54.94.234.103] - setup docker
[54.232.209.247] - setup docker: SUCCESS
[54.94.234.103] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[54.232.209.247] - Setup Environment
[54.94.234.103] - Setup Environment
[54.94.234.103] - Setup Environment: SUCCESS
[54.232.209.247] - Setup Environment: SUCCESS
```

**Comment by madushan1000** [comment]
Looks like your VM has SFTP disabled. See if it is. Are you logging in using a password or a ssh-key?

**Comment by teintinu** [comment]
I'm using ssh-key. `mup setup` runs without errrors.
I'm using a Ubuntu machine on AWS, SFTP is enabled by default.

**Comment by madushan1000** [comment]
Can you post your `mup.js` file here?

**Comment by teintinu** [comment]
``` js
module.exports = {
    servers: {
        A: {
            host: '54.232.209.247',
            username: 'root',
            pem: '../tolentino.pem',
        },
        B: {
            host: '54.94.234.103',
            username: 'root',
            pem: '../tolentino.pem',
        },
    },

    meteor: {
        name: 'zscan',
        path: '/home/hoda51/zscan/meteor',
        servers: {
            A: {
                host: '54.232.209.247',
                username: 'root',
                pem: '../tolentino.pem',
            },
            B: {
                host: '54.94.234.103',
                username: 'root',
                pem: '../tolentino.pem',
            },
        },
        env: {
            ROOT_URL: 'http://zscan.hoda5.com',
            MONGO_URL: 'mongodb://localhost/zscan'
        },
    },

    mongo: {
        oplog: true,
        port: 27017,
        servers: {
            one: {},
        },
    },
};
```

**Comment by madushan1000** [comment]
You don't have to redefine servers under `meter.servers`. Just do something like this

``` javascript
meteor: {
  ...
  servers: {
    A: {}, B {}
  }
}
```

I'm not sure this is still the problem though. Can you try to deploy to one server, without doing both at ones.

**Comment by danwild** [comment]
I encountered the exact same issue un Ubuntu 14.04, and found this in mup logs:

**Please login as the user "ubuntu" rather than the user "root".**

So - changed `username: 'ubuntu'` and it deployed successfully.
