### ISSUE TITLE
deploy failed

### ISSUE THREAD

**Issue by maxlibin** [zodern/meteor-up#782]
can anyone tell me whats wrong with my deploy here?

 x Verifying Deployment: FAILED

	-----------------------------------STDERR-----------------------------------
	js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^

	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)

	=> Redeploying previous version of the app

	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=100'

	----------------------------------------------------------------------------

 !  ~/w/t   v2 *$  .deploy  mup logs --tail=100
[]=> Starting meteor app on port:80
[]{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
[]js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by zodern** [comment]
What meteor version are you using, and what is the docker image in your config?

**Comment by yanickrochon** [comment]
Got the same problem with Meteor 1.6. My docker image is `abernix/meteord:base`.

**Comment by zodern** [comment]
Try using the `abernix/meteord:node-8.4.0-base` docker image.

**Comment by yanickrochon** [comment]
Worked! Thanks!

**Comment by maxlibin** [comment]
host and domain using my domains not shown here.

```module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '...',
      username: 'maxli',
      pem: '/Users/max/.ssh/id_rsa',
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'mysite',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'https://mysite.com',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    ssl: { // (optional)
      // Enables let's encrypt (optional)
      // autogenerate: {
      //   email: 'email.address@domain.com',
      //   // comma separated list of domains
      //   domains: 'website.com,www.website.com'
      // }
      crt: './t.crt', // this is a bundle of certificates
      key: './t.key', // this is the private key of the certificate
      port: 443 // 443 is the default value and it's the standard HTTPS port
    },

    deployCheckWaitTime: 180,
    enableUploadProgressBar: true,

    docker: {
      // change to 'kadirahq/meteord' if your app is using Meteor 1.3 or older
      //image: 'abernix/meteord:base',
      image: 'abernix/meteord:node-8.4.0-base'
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

**Comment by maxlibin** [comment]
here's the new problem now.

```
-----------------------------------STDERR-----------------------------------
	built_app/programs/server/npm/node_modules/react/react.js:3:18)
	    at Module._compile (module.js:573:30)
	    at Object.Module._extensions..js (module.js:584:10)
	    at Module.load (module.js:507:32)
	    at tryModuleLoad (module.js:470:12)
	    at Function.Module._load (module.js:462:3)
	=> Starting meteor app on port:80
	/built_app/programs/server/node_modules/fibers/future.js:280
							throw(ex);
							^

	Error: Cannot find module './lib/React'
	    at Function.Module._resolveFilename (module.js:489:15)
	    at Function.Module._load (module.js:439:25)
	    at Module.require (module.js:517:17)
	    at require (internal/module.js:11:18)
	    at Object.<anonymous> (/built_app/programs/server/npm/node_modules/react/react.js:3:18)
	    at Module._compile (module.js:573:30)
	    at Object.Module._extensions..js (module.js:584:10)
	    at Module.load (module.js:507:32)
	    at tryModuleLoad (module.js:470:12)
	    at Function.Module._load (module.js:462:3)

	=> Redeploying previous version of the app

	-----------------------------------STDOUT-----------------------------------

	To see more logs type 'mup logs --tail=100'

	----------------------------------------------------------------------------

**Comment by maxlibin** [comment]
ok finally works now, i have remove my node_modules and meteor npm install.
