### ISSUE TITLE
mup deploy failed at Preparing Bundle

### ISSUE THREAD

**Issue by tpmh31292** [zodern/meteor-up#785]
Hi, I'm having problem with deploying my app. Was doing fine few days ago, but it suddenly happened today and I haven't been able to deploy since then. Thought it was a problem with npm itself, so I updated mup, node and npm to latest version but it still happens.

Here is my `mup.cmd deploy --verbose` . Can anyone please help?

```
[xxx.xxx.xxx.xxx] - Pushing Meteor App Bundle to The Server
[xxx.xxx.xxx.xxx] - Pushing Meteor App Bundle to The Server: SUCCESS
[xxx.xxx.xxx.xxx] - Prepare Bundle
base: Pulling from abernix/meteord
Digest: sha256:b77c06e918d75e313167ac7aaf123407eeb424136fba528cbdcfcb7ff1be65bb
Status: Image is up to date for abernix/meteord:base
clientdiary
Sending build context to Docker daemon  306.5MB
Step 1/8 : FROM abernix/meteord:base
 Executing 1 build trigger...
Step 1/1 : ENV NODE_VERSION ${NODE_VERSION:-4.8.4}
 ---> Using cache
 ---> e15d24ff01e0
Step 2/8 : RUN mkdir /built_app
 ---> Using cache
 ---> 105b988a2df0
Step 3/8 : COPY ./ /built_app
 ---> Using cache
 ---> da09581bb9bc
Step 4/8 : ENV ROOT_URL [mydomain]
 ---> Using cache
 ---> aef3d2b964f4
Step 5/8 : ENV MONGO_URL [myMongo]
 ---> Using cache
 ---> e4e3c4c3aaca
Step 6/8 : ENV MONGO_OPLOG_URL [myMongoOplog]
 ---> Using cache
 ---> b0c0acc93f0e
Step 7/8 : ENV CLUSTER_WORKERS_COUNT auto
 ---> Using cache
 ---> c560a2481c4c
Step 8/8 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Running in f1e0c9ca155a

> fibers@1.0.13 install /built_app/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-v8-4.5` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /built_app/programs/server
> node npm-rebuild.js


> v8-profiler@5.6.5 preinstall /built_app/programs/server/npm/node_modules/meteor/meteorhacks_kadira-binary-deps/node_modules/v8-profiler
> node -e 'process.exit(0)'


> v8-profiler@5.6.5 install /built_app/programs/server/npm/node_modules/meteor/meteorhacks_kadira-binary-deps/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! v8-profiler@5.6.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the v8-profiler@5.6.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-05T00_54_41_150Z-debug.log
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! Exit status 126
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-05T00_54_41_173Z-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 126
clientdiary
[xxx.xxx.xxx.xxx] x Prepare Bundle: FAILED

        -----------------------------------STDERR-----------------------------------
        The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 126
        -----------------------------------STDOUT-----------------------------------
        m Exit status 126
        npm ERR!
        npm ERR! Failed at the v8-profiler@5.6.5 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-11-05T00_54_41_150Z-debug.log
        npm WARN meteor-dev-bundle@0.0.0 No description
        npm WARN meteor-dev-bundle@0.0.0 No repository field.
        npm WARN meteor-dev-bundle@0.0.0 No license field.
        npm ERR! code ELIFECYCLE
        npm ERR! errno 126
        npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
        npm ERR! Exit status 126
        npm ERR!
        npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-11-05T00_54_41_173Z-debug.log
        [myAppName]
        ----------------------------------------------------------------------------
```

**Comment by zodern** [comment]
Did you try removing `node_modules` and then running `meteor npm install`?

**Comment by tpmh31292** [comment]
You mean removing the node_modules folder in my meteor project? And meteor npm install mup?
I installed mup globally.

**Comment by zodern** [comment]
Sorry for not being more specific. Please try reinstalling your meteor project's npm dependencies by deleting `node_modules` in your meteor project and running `meteor npm install`. You shouldn't need to reinstall mup.

**Comment by tpmh31292** [comment]
No luck, still the same error with exit code 126

**Comment by tpmh31292** [comment]
@zodern removing the meteorhacks:kadira-profiler package made it works now.
But now another problem happens at Verifying Deployment. I set the `deployCheckWaitTime ` to 180 but this error still exists.

the Meteor version as shown in `.meteor/release` is METEOR@1.4.1.1
I also tried moving the mup.js and settings.json to a location outside of the app’s folder but still not working.

```
[xxx.xxx.xxx.xxx] x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        ules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
            at Function.Module._load (module.js:300:12)
        => Starting meteor app on port:80
        /built_app/programs/server/node_modules/fibers/future.js:280
                                                        throw(ex);
                                                        ^

        Error: Cannot find module 'websocket-driver'
            at Function.Module._resolveFilename (module.js:325:15)
            at Function.Module._load (module.js:276:25)
            at Module.require (module.js:353:17)
            at require (internal/module.js:12:17)
            at Object.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/ddp-server/node_modules/sockjs/node_modules/faye-websocket/lib/faye/websocket.js:8:14)
            at Module._compile (module.js:409:26)
            at Object.Module._extensions..js (module.js:416:10)
            at Module.load (module.js:343:32)
            at Module.Mp.load (/built_app/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
            at Function.Module._load (module.js:300:12)

        => Redeploying previous version of the app

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=100'

        ----------------------------------------------------------------------------
```

**Comment by rootedsoftware** [comment]
I was getting a similar error: "Cannot find module 'graphql/language/printer'" I needed to install ```meteor npm install --save graphql```

**Comment by tpmh31292** [comment]
Thanks, did that and it works now. But I don't understand why it asked for it, I didn't have and didn't use that package before.
