### ISSUE TITLE
Verifying Deployment: FAILED

### ISSUE THREAD

**Issue by chackerian** [zodern/meteor-up#786]
When I try to deploy, I am getting this error message. Recently I updated to meteor 1.6 and some packages and mup so I am pretty sure one of those things is the cause of this. My code seems fine. 

Verifying Deployment: FAILED

	-----------------------------------STDERR-----------------------------------
	js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^

	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)

**Comment by zodern** [comment]
@chackerian change the docker image in your config to `abernix/meteord:node-8.4.0-base`

**Comment by chackerian** [comment]
That fixed it. Thanks.
