### ISSUE TITLE
"Error: read ECONNRESET" during "mup.cmd setup"

### ISSUE THREAD

**Issue by fahadakhan96** [zodern/meteor-up#797]
This is what I get when I run `mup.cmd setup`

```
Started TaskList: Setup Docker
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Setup Docker
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Setup Docker: SUCCESS

Started TaskList: Setup Meteor
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Setup Environment
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Setup Environment: SUCCESS

Started TaskList: Setup Mongo
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Setup Environment
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Setup Environment: SUCCESS
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Copying mongodb.conf
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Copying mongodb.conf: SUCCESS

Started TaskList: Start Mongo
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Start Mongo
[ec2-13-58-8-6.us-east-2.compute.amazonaws.com] - Start Mongo: SUCCESS
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at TCP.onread (net.js:619:25)
```
Please help. Below is my **mup.js**.
```
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '<hostname>',
      username: '<username>',
      pem: './path/to/pem'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'name',
    path: '../name',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://<hostname>',
      MONGO_URL: 'mongodb://localhost/meteor',
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma separated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```

**Comment by fahadakhan96** [comment]
Fixed after trying from a different internet connection!
