### ISSUE TITLE
Mup fails  at "Verifying Deployment: FAILED"

### ISSUE THREAD

**Issue by ken4ward** [zodern/meteor-up#804]
Firstly I'll like to say thank you to the Meteor group for the great work ongoing. I have used Mup in projects of v1.5.x which worked brilliantly. I updated the same project to v1.6 and it keeps failing now. I have insdtalled a couple of libraries from NPM. As the log reads that `libbase64` is missing but it is wrong becase this exist in MY package.json
This is the third day I have been trying to deploy to a Ubuntu-16 server but Mup keeps failing. I have set the configuration as indicated on the doc. Please @zodern, @arunoda, @wizonesolutions, what's this error log saying. Please help out.
This is the package.json file
```
{
  "name": "schoolapps",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "async": "^2.5.0",
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "bluebird": "^3.5.1",
    "email-templates": "^3.1.7",
    "handlebars": "^4.0.11",
    "iconv-lite": "^0.4.19",
    "libbase64": "^0.2.0",
    "mailer": "^0.6.7",
    "meteor-node-stubs": "~0.2.4",
    "mime": "^2.0.3",
    "mongo-object": "0.0.3",
    "node": "file:///Program Files/nodejs",
    "nodemailer": "^4.4.0",
    "pug": "^2.0.0-rc.4",
    "range-parser": "^1.2.0",
    "shared": "^0.2.0",
    "simpl-schema": "^0.3.2",
    "warp.email-processor": "^0.1.3"
  },
  "devDependencies": {
    "bulk-email-verifier": "^1.0.4"
  }
}

```

This is my mup settings
```
module.exports = {
  servers: {
    one: {
      host: 'xxx.xxx.xxx.xxx',
      username: 'root',
       password: 'myserverpassword'
    }
  },

  app: {
    name: 'schoolapps',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'https://rabonni.com',
      MONGO_URL: 'mongodb://ken4ward:mynewdatabasepassword@ds259855.mlab.com:59855/rabonnischool'
    },

    docker: {
       image: 'abernix/meteord:node-8.4.0-base',
    },
      enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```

THis is the error log
```
tar: bundle/programs/server/npm/node_modules/meteor/reywood_publish-composite/node_modules/eslint/node_modules/table/node_modules/string-width\node_modules\strip-ansi\node_modules\ansi-regex\package.json: time stamp 2017-11-17 13:31:19 is 28233.488314573 s in the future
tar: bundle/programs/server/npm/node_modules/meteor/reywood_publish-composite/node_modules/eslint/node_modules/table/node_modules/string-width\node_modules\strip-ansi\node_modules\ansi-regex\readme.md: time stamp 2017-11-17 13:31:19 is 28233.488280633 s in the future

tar: bundle/programs/server/npm/node_modules/meteor/reywood_publish-composite/node_modules/eslint-config-airbnb/node_modules/eslint-plugin-import/node_modules/minimatch/node_modules/brace-expansion/node_modules/concat-map/README.markdown: time stamp 2017-11-17 13:31:20.052 is 28229.871812435 s in the future
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'


tar: bundle/programs/server/npm/node_modules/meteor/reywood_publish-composite/node_modules/eslint-config-airbnb/node_modules/eslint-plugin-import/node_modules/eslint-module-utils/node_modules/pkg-dir/node_modules/find-up/node_modules/pinkie-promise/node_modules/pinkie/readme.md: time stamp 2017-11-17 13:31:19.959 is 28229.7085152 s in the future
tar: bundle: time stamp 2017-11-17 13:31:47 is 28256.749475885 s in the future
Sending build context to Docker daemon    186MB
Step 1/7 : FROM abernix/meteord:node-8.4.0-base
# Executing 1 build trigger
 ---> Using cache
 ---> db32ac284b4a
Step 2/7 : RUN mkdir /built_app
 ---> Using cache
 ---> 32725a1b376e
Step 3/7 : COPY ./ /built_app
 ---> Using cache
 ---> adfda3fc59f6
Step 4/7 : ENV ROOT_URL=https://rabonni.com
 ---> Using cache
 ---> a8234e2393c7
Step 5/7 : ENV MONGO_URL=mongodb://mongodb:27017/schoolapps
 ---> Using cache
 ---> beeb68ce84bf
Step 6/7 : ENV PORT=3000
 ---> Using cache
 ---> bc922cc5c8f8
Step 7/7 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Using cache
 ---> 3060ab7eecd1
Successfully built 3060ab7eecd1
Successfully tagged mup-schoolapps:build
schoolapps
Total reclaimed space: 0B
[xxx.xxx.xxx.xxx] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[xxx.xxx.xxx.xxx] - Pushing the Startup Script
[xxx.xxx.xxx.xxx] - Pushing the Startup Script: SUCCESS
[xxx.xxx.xxx.xxx] - Sending Environment Variables
[xxx.xxx.xxx.xxx] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[xxx.xxx.xxx.xxx] - Start Meteor
using image
removing last
Image mup-schoolapps:latest
Volume
Removing docker containers. Errors about nonexistent endpoints and containers are normal.
schoolapps
Error response from daemon: endpoint schoolapps not found
Error: No such container: schoolapps-frontend
Error response from daemon: endpoint schoolapps-frontend not found
Error: No such container: schoolapps-nginx-letsencrypt
Error response from daemon: endpoint schoolapps-nginx-letsencrypt not found
Error: No such container: schoolapps-nginx-proxy
Error response from daemon: endpoint schoolapps-nginx-proxy not found
Finished removing docker containers
0429f1bb36b77928fb8ec43109940e5121d5a510765d3f338981cb32d317d772
Ran abernix/meteord:node-8.4.0-base
[xxx.xxx.xxx.xxx] - Start Meteor: SUCCESS
[xxx.xxx.xxx.xxx] - Verifying Deployment
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 3000: Connection refused
 
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
=> Starting meteor app on port:80

/built_app/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^
Error: Cannot find module 'libbase64'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/epaminond_nodemailer/node_modules/nodemailer/node_modules/libmime/src/libmime.js:4:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)


=> Redeploying previous version of the app

To see more logs type 'mup logs --tail=100'

[xxx.xxx.xxx.xxx] x Verifying Deployment: FAILED

        -----------------------------------STDOUT-----------------------------------

        To see more logs type 'mup logs --tail=100'

        ----------------------------------------------------------------------------

C:\Programs\contract\schoolapps\.deploy>
```

**Comment by lucalanzano81** [comment]
+1

**Comment by sayantan-das-bchu** [comment]
+1

**Comment by elie222** [comment]
+1

**Comment by elie222** [comment]
I have this same error on MUP 1.3.3 and 1.3.7.

Issue seems to be at this line:
`Failed to connect to localhost port 80: Connection refused`

**Comment by elie222** [comment]
This may help us:
https://github.com/zodern/meteor-up/issues/818

Trying myself now.

**Comment by elie222** [comment]
Nope. That didn't solve it.

**Comment by nchokoev** [comment]
Can you please verify that the file 
'/built_app/programs/server/npm/node_modules/meteor/epaminond_nodemailer/node_modules/nodemailer/node_modules/libmime/src/libmime.js'
exists on the container?

**Comment by elie222** [comment]
How do you verify this?

On 5 Dec 2017 17:56, "nickich" <notifications@github.com> wrote:

Can you please verify that the file
'/built_app/programs/server/npm/node_modules/meteor/
epaminond_nodemailer/node_modules/nodemailer/node_
modules/libmime/src/libmime.js'
exists on the container?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zodern/meteor-up/issues/804#issuecomment-349348366>,
or mute
the thread

**Comment by nchokoev** [comment]
@elie222 
Try with:

`sudo docker run -ti --entrypoint=/bin/ls <your_image> /built_app/programs/server/npm/node_modules/meteor/epaminond_nodemailer/node_modules/nodemailer/node_modules/libmime/src/`

where '<your_image>' is your image ID. You can get it with 'sudo docker images'. 

Can you post the output of this command?

Do you deploy from Windows?

**Comment by rkstar** [comment]
i'm having this same problem with mup 1.3.7 and i ran the above to get this:
```
:~# sudo docker run -ti --entrypoint=/bin/ls a1b2c3d4e5f6g7 /built_app/programs/server/npm/node_modules/meteor/epaminond_nodemailer/node_modules/nodemailer/node_modules/libmime/src/

/bin/ls: cannot access /built_app/programs/server/npm/node_modules/meteor/epaminond_nodemailer/node_modules/nodemailer/node_modules/libmime/src/: No such file or directory
```

**Comment by zodern** [comment]
This should be fixed in newer versions of Mup.
