### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by derwaldgeist** [zodern/meteor-up#822]
I updated my app to Meteor 1.6 and to the latest mup version 1.37.

The deployment succeeded, but Nginx shows a Bad Gateway message. In the logs, I see this error: 

```
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
=> Starting meteor app on port:80
/built_app/programs/server/boot.js:50
    const { pause } = require("./debug.js");
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/built_app/main.js:4:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
=> Starting meteor app on port:80
/built_app/programs/server/boot.js:50
```

This error repeats multiple times.

Seems as if there's a problem with ES6 code.

**Comment by derwaldgeist** [comment]
I could solve this by changing the Docker image to `abernix/meteord:node-8-base` as suggested here: https://github.com/zodern/meteor-up/issues/808#issuecomment-346740335

Closing this issue, but it would be great if this was mentioned in the docs.

**Comment by ziedmahdi** [comment]
@derwaldgeist it is mentioned [in the docs](http://meteor-up.com/docs.html#meteor-support).

I think what's better is if you check the docs and previous issues before creating a new one.

**Comment by derwaldgeist** [comment]
Ah, I only looked at the sample configuration code: http://meteor-up.com/docs.html#everything-configured. There was no mention of the docker image there, only for 1.3 and below. And when I opened this issue, I wasn't aware this was related to Meteor 1.6. As soon as I realised, I closed it :-)
