### ISSUE TITLE
mup logs don't print deployment error logs

### ISSUE THREAD

**Issue by gsabran** [zodern/meteor-up#84]
My build failed:

```
$ mup deploy
Building App Bundle Locally

Started TaskList: Pushing Meteor
[52.207.215.18] - Pushing Meteor App Bundle to The Server
[52.207.215.18] - Pushing Meteor App Bundle to The Server: SUCCESS
[52.207.215.18] - Pushing the Startup Script
[52.207.215.18] - Pushing the Startup Script: SUCCESS

Started TaskList: Configuring  Meteor Environment Variables
[52.207.215.18] - Sending Environment Variables
[52.207.215.18] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[52.207.215.18] - Start Meteor
[52.207.215.18] - Start Meteor: SUCCESS
[52.207.215.18] - Verifying Deployment
[52.207.215.18] x Verifying Deployment: FAILED

    -----------------------------------STDERR-----------------------------------
    g directory `/bundle/bundle/programs/server/node_modules/fibers/build'
    Installed in `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
    ansi-regex@0.2.1 node_modules/ansi-regex

        [Some stack trace]

    => Starting meteor app on port:80

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
[STDERR and STDOUT are printed twice, that's fine]

----------------------------------------------------------------------------
    at pathToMeteor-up/node_modules/nodemiral/lib/coreTasks.js:39:16
    at pathToMeteor-up/node_modules/nodemiral/lib/session.js:146:9
    at Channel.<anonymous> (pathToMeteor-up/node_modules/nodemiral/lib/ssh.js:125:9)
    at emitOne (events.js:77:13)
    at Channel.emit (events.js:169:7)
    at SSH2Stream.<anonymous> (pathToMeteor-up/node_modules/nodemiral/node_modules/ssh2/lib/Channel.js:124:14)
    at SSH2Stream.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at SSH2Stream.emit (events.js:166:7)
    at parsePacket (pathToMeteor-up/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3435:10)
    at SSH2Stream._transform (pathToMeteor-up/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (pathToMeteor-up/node_modules/nodemiral/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
```

All right I don't know what happened so as suggested by stdout I'll hit

```
$mup logs --tail=5000
```

and I get

```
$ mup logs --tail=5000
[someIP]npm WARN deprecated This version of npm lacks support for important features,
[someIP]npm WARN deprecated such as scoped packages, offered by the primary npm
[someIP]npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[someIP]npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[someIP]npm WARN deprecated 
[someIP]npm WARN deprecated   npm -g install npm@latest-2
[someIP]npm WARN deprecated 
[someIP]npm WARN deprecated To upgrade to the latest stable version, run:
[someIP]npm WARN deprecated 
[someIP]npm WARN deprecated   npm -g install npm@latest
[someIP]npm WARN deprecated 
[someIP]npm WARN deprecated (Depending on how Node.js was installed on your system, you
[someIP]npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[someIP]npm WARN deprecated on Windows, run them from an Administrator prompt.)
[someIP]npm WARN deprecated 
[someIP]npm WARN deprecated If you're running the version of npm bundled with
[someIP]npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[someIP]npm WARN deprecated will be bundled with a version of npm@2, which has some small
[someIP]npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[someIP]npm WARN deprecated semver behavior.
[someIP]npm WARN package.json meteor-dev-bundle@0.0.0 No description
[someIP]npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[someIP]npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[someIP]=> Starting meteor app on port:80
[someIP]Kadira: completed instrumenting the app
[someIP]Kadira: Successfully connected
```

which looks like some logs from the running server but not from the deployment

**Comment by madushan1000** [comment]
Yes, This error is thrown by mup, which is running on your local machine because it can't verify meteor app is running. `mup logs` pulls docker logs from the server, which seems to be running fine. Increasing the `deployCheckWaitTime` on `mup.js` should work.  

If you'd like to help get more reliable deploy check, Check this issue https://github.com/kadirahq/meteor-up/issues/73.

**Comment by gsabran** [comment]
I see. So it's a bit confusing, both due to the stdout advice and the fact that nothing in the trace indicate anything local. But now I know. Hope that google is gonna show this issue for people looking for a clue.
I'll increase deployCheckWaitTime and see.
Thanks a lot!
