### ISSUE TITLE
Could I deploy on Local PC?

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#841]
I tried to deploy on `My Local PC`
```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '192.168.0.114',
      username: 'root',
      // pem: './path/to/pem'
      // password: 'server-password'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'element',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://192.168.0.114',
      MONGO_URL: 'mongodb://localhost/element',
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma separated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:node-8.4.0-base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```
Get error
````js
mup setup
----------
Started TaskList: Setup Docker
[192.168.0.114] - Setup Docker
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.0.114:22
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```
Please help me!

**Comment by nchokoev** [comment]
> module.exports = {
>   servers: {
>     one: {
>       // TODO: set host address, username, and authentication method
>       host: '192.168.0.114',
>       username: 'root',
>       // pem: './path/to/pem'
>       // password: 'server-password'
>       // or neither for authenticate from ssh-agent
>     }

Maybe provide password for 'root', and make sure you can SSH to it.

**Comment by thearabbit** [comment]
thanks for your reply.
I base on `Mac`, I tried to put the `password: '123456'` but still the same problem.
Could you help with `SSH`?

**Comment by nchokoev** [comment]
@thearabbit 
Do you deploy on MAC?
Provide the passwoord for 'root'.

**Comment by thearabbit** [comment]
thanks for your reply.
My PC password or any? I tried to add my PC password, but still don't work
Please help me

**Comment by nchokoev** [comment]
@thearabbit Please make sure you can SSH to the PC. Use the same credentials.

**Comment by thearabbit** [comment]
I can't connect my PC via this
```
~ ssh root@192.168.0.101
ssh: connect to host 192.168.0.101 port 22: Connection refused
```
How to solve?

**Comment by nchokoev** [comment]
@thearabbit 
[http://osxdaily.com/2011/09/30/remote-login-ssh-server-mac-os-x/](http://osxdaily.com/2011/09/30/remote-login-ssh-server-mac-os-x/)
[http://osxdaily.com/2016/08/16/enable-ssh-mac-command-line/](http://osxdaily.com/2016/08/16/enable-ssh-mac-command-line/)

**Comment by thearabbit** [comment]
thanks I will try soon

**Comment by thearabbit** [comment]
Now I can log into my local PC via `ssh`
```
➜  ~ ssh theara@192.168.0.103
Password:
Last login: Fri Jan  5 10:58:57 2018
➜  ~
```
And then I try `mup setup` on my project after `exit` of `ssh` access
```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '192.168.0.103',
      username: 'theara',
      // pem: './path/to/pem'
      password: ' ***'
      // or neither for authenticate from ssh-agent
    }
  },

  app: {
    // TODO: change app name and path
    name: 'localapp',
    path: '../../meteor-app',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: 'http://192.168.0.103',
      MONGO_URL: 'mongodb://localhost/localdb',
    },

    // ssl: { // (optional)
    //   // Enables let's encrypt (optional)
    //   autogenerate: {
    //     email: 'email.address@domain.com',
    //     // comma separated list of domains
    //     domains: 'website.com,www.website.com'
    //   }
    // },

    docker: {
      // change to 'abernix/meteord:base' if your app is using Meteor 1.4 - 1.5
      image: 'abernix/meteord:node-8.4.0-base',
    },

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};
```
Get error
```js
➜  .deploy git:(master) ✗ mup setup

Started TaskList: Setup Docker
[192.168.0.103] - Setup Docker
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/client.js:469:5)
    at emitTwo (events.js:106:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/ssh.js:3647:10)
    at SSH2Stream._transform (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at SSH2Stream.Writable.write (_stream_writable.js:246:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
```
Please help me

**Comment by thearabbit** [comment]
I tried on `Ubuntu Local`
```
$ mup setup
--------
Started TaskList: Setup Docker
[192.168.0.121] - Setup Docker
[192.168.0.121] x Setup Docker: FAILED

	-----------------------------------STDERR-----------------------------------
	sudo: no tty present and no askpass program specified
	sudo: no tty present and no askpass program specified
	sudo: no tty present and no askpass program specified
	sudo: no tty present and no askpass program specified
	sudo: no tty present and no askpass program specified
	sudo: no tty present and no askpass program specified
	-----------------------------------STDOUT-----------------------------------

	Major
	Minor
```

**Comment by thearabbit** [comment]
And then I modifier `sudo visudo`
```
# Members of the admin group may gain root privileges
%admin ALL=(ALL) NOPASSWD:ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
```
But still the same problem

**Comment by zapkto** [comment]
Do sudo visudo and replace 
%sudo   ALL=(ALL:ALL) ALL

By
%sudo   ALL=(ALL:ALL) NOPASSWD:ALL

**Comment by thearabbit** [comment]
Very thanks, I work fine 👍
