### ISSUE TITLE
Deploy Error at Prepare Bundle

### ISSUE THREAD

**Issue by lesliedoghouse** [zodern/meteor-up#845]
Hi all, any idea what cause this error? The log file doesn't exist. How to fix this? Server no problem as I tried Meteor default app and publish without error.

What exactly this error message mean? Please advice, thank you.

```
Started TaskList: Pushing Meteor App
[183.81.164.137] - Pushing Meteor App Bundle to the Server
[183.81.164.137] - Pushing Meteor App Bundle to the Server: SUCCESS
[183.81.164.137] - Prepare Bundle
[183.81.164.137] x Prepare Bundle: FAILED

        -----------------------------------STDERR-----------------------------------
        The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
        -----------------------------------STDOUT-----------------------------------
        npm/node_modules/bcrypt
        > node-pre-gyp install --fallback-to-build

        [bcrypt] Success: "/built_app/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is insta
lled via remote

        npm ERR! Invalid version: "https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz"

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-12-21T02_58_00_669Z-debug.log
        npm ERR! code ELIFECYCLE
        npm ERR! errno 1
        npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
        npm ERR! Exit status 1
        npm ERR!
        npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script.
        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /root/.npm/_logs/2017-12-21T02_58_00_834Z-debug.log
        InfiSensesPOS
        ----------------------------------------------------------------------------
macOS:.deploy lesliechan$ tail /root/.npm/_logs/2017-12-21T02_58_00_834Z-debug.log
```

**Comment by stefanve** [comment]
Try
`meteor npm remove bcrypt`

Then deploy again

**Comment by lesliedoghouse** [comment]
Hi, after remove bcrypt, I get the following error. My **_deployCheckWaitTime_** is **_180_**. Please advice, thanks in advance.

```
x Verifying Deployment: FAILED

        -----------------------------------STDERR-----------------------------------
        js:416:10)
            at Module.load (module.js:343:32)
            at Function.Module._load (module.js:300:12)
            at Module.require (module.js:353:17)
            at require (internal/module.js:12:17)
            at Object.<anonymous> (/built_app/main.js:4:1)
            at Module._compile (module.js:409:26)
            at Object.Module._extensions..js (module.js:416:10)
        => Starting meteor app on port:80
        /built_app/programs/server/boot.js:50
            const { pause } = require("./debug.js");
                  ^


        SyntaxError: Unexpected token {
            at exports.runInThisContext (vm.js:53:16)
            at Module._compile (module.js:373:25)
            at Object.Module._extensions..js (module.js:416:10)
            at Module.load (module.js:343:32)
            at Function.Module._load (module.js:300:12)
            at Module.require (module.js:353:17)
            at require (internal/module.js:12:17)
            at Object.<anonymous> (/built_app/main.js:4:1)
            at Module._compile (module.js:409:26)
            at Object.Module._extensions..js (module.js:416:10)

        => Redeploying previous version of the app
```

**Comment by lesliedoghouse** [comment]
Hi, I tried change **_deployCheckWaitTime_** to **_250_**, the result/error is the same.

**Comment by stefanve** [comment]
Tried with another docker image? See:
https://github.com/zodern/meteor-up/issues/808#issuecomment-346740335

**Comment by lesliedoghouse** [comment]
Thanks so much, my Meteor version is 1.6. I change to abernix/meteord:node-8.9.3-base

It deploy success now.
