### ISSUE TITLE
[Error] Failed to copy file  { Error: No such file     at SFTPStream._transform......

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#846]
I deploy with other `IP`
```js
host: '172.1.2.3', // First ip -> work find
---
// And then I changed to the second ip
host: '172.4.5.6', // Second ip -> don't work
```
Get error
```
Started TaskList: Pushing Meteor App
[172.104.43.168] - Pushing Meteor App Bundle to The Server
Failed to copy file  { Error: No such file
    at SFTPStream._transform (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/sftp.js:384:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at SFTPStream.Writable.write (_stream_writable.js:246:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/Channel.js:140:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/usr/local/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/ssh.js:3163:10) code: 2, lang: '' }
Retrying in 3 seconds
```

**Comment by stefanve** [comment]
And you have sufficient access rights for the second server?

**Comment by thearabbit** [comment]
thanks for your reply.
Now I tried `mup setup` and then `mup deploy`, It work fine.
(I am not clear, bc the second IP, I used to `mup setup` before).
