### ISSUE TITLE
MUP install mongo db

### ISSUE THREAD

**Issue by skynightz93** [zodern/meteor-up#85]
Sorry, it is actually not a issue but question but i dont know where to ask this question. is that this mup installing the mongodb automatically in mup setup like mupx did in docker. Because there is no log about mongodb. and what is MONGO_URL? i want to make sure my mongodb in same server. In this case in docker.

**Comment by MasterJames** [comment]
Mupx docker versions of mup mount a local volume during setup so redeploy it doesn't overwrite your database so I think that will help you. So no need to ponder Mup in my understanding.

**Comment by madushan1000** [comment]
MONGO_URL is `mongodb://localhost:27017`

**Comment by skynightz93** [comment]
There is no workaround to connect to server mongo without allowing public access of mongoDB? I dont think allowing public access to mongoDB is good idea. 

I tried to set this in mup.js

`module.exports = {
    servers: {
        one: {
            host: '...',
            username: 'root',
            pem: './.mykey',
        },
    },

```
meteor: {
    name: 'bongkahDevsign',
    path: '../',
    servers: {
        one: {},
    },
    env: {
        PORT: 3002,
        ROOT_URL: 'http://bongkah.foo.com',
        MONGO_URL: 'mongodb://localhost:27017/test'
    },
    deployCheckWaitTime: 60,
},
```

};`

and here is the error

`x Verifying Deployment: FAILED

```
    -----------------------------------STDERR-----------------------------------
    app/server/server.js:1:9)
        at fileEvaluate (/bundle/bundle/programs/server/packages/modules-runtime.js:158:9)
        at require (/bundle/bundle/programs/server/packages/modules-runtime.js:92:16)
        at /bundle/bundle/programs/server/app/app.js:13:1
        - - - - -
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
        at [object Object].emit (events.js:106:17)
        at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
        at [object Object].emit (events.js:98:17)
        at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
        at Socket.emit (events.js:95:17)
        at net.js:441:14
        at process._tickCallback (node.js:458:13)

    => Redeploying previous version of the app

    -----------------------------------STDOUT-----------------------------------

    To see more logs type 'mup logs --tail=50'

    ----------------------------------------------------------------------------
```

Error:
-----------------------------------STDERR-----------------------------------
app/server/server.js:1:9)
    at fileEvaluate (/bundle/bundle/programs/server/packages/modules-runtime.js:158:9)
    at require (/bundle/bundle/programs/server/packages/modules-runtime.js:92:16)
    at /bundle/bundle/programs/server/app/app.js:13:1
    - - - - -
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)

=> Redeploying previous version of the app

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

---

```
at D:\Gitlab\nizulzaim\meteor-up\node_modules\nodemiral\lib\coreTasks.js:39:16
at D:\Gitlab\nizulzaim\meteor-up\node_modules\nodemiral\lib\session.js:146:9
at Channel.<anonymous> (D:\Gitlab\nizulzaim\meteor-up\node_modules\nodemiral\lib\ssh.js:125:9)
at emitOne (events.js:77:13)
at Channel.emit (events.js:169:7)
at SSH2Stream.<anonymous> (D:\Gitlab\nizulzaim\meteor-up\node_modules\ssh2\lib\Channel.js:124:14)
at SSH2Stream.g (events.js:260:16)
at emitNone (events.js:67:13)
at SSH2Stream.emit (events.js:166:7)
at parsePacket (D:\Gitlab\nizulzaim\meteor-up\node_modules\ssh2-streams\lib\ssh.js:3435:10)
at SSH2Stream._transform (D:\Gitlab\nizulzaim\meteor-up\node_modules\ssh2-streams\lib\ssh.js:551:13)
at SSH2Stream.Transform._read (_stream_transform.js:167:10)
at SSH2Stream._read (D:\Gitlab\nizulzaim\meteor-up\node_modules\ssh2-streams\lib\ssh.js:212:15)
at SSH2Stream.Transform._write (_stream_transform.js:155:12)
at doWrite (_stream_writable.js:292:12)
at writeOrBuffer (_stream_writable.js:278:5)`
```

I also try to MONGO_URL but error still there.

`MONGO_URL: 'mongodb://localhost:27017/`

**Comment by madushan1000** [comment]
Just custom setup your mongodb with authentication and point the app there using `MONGO_URL`. 
The error log is not complete. I can't say anything from it.
