### ISSUE TITLE
Mup version to use with meteor 1.6.0.1

### ISSUE THREAD

**Issue by yannickneemaa** [zodern/meteor-up#868]
Hello,
SInce my last upgrade to meteor 1.6.0.1, I can't seem tu deploy using mup.

If you are able do deploy with 1.6.0.1, could you give me the versions you use for :
- MUP (I currently use 1.2.9)
- Docker version (I use abernix/meteord:node-8.4.0-base)

Thanks !

**Comment by resmith** [comment]
Same issue when using MUP with Meteor 1.6.
I used image: 'abernix/meteord:node-8-base'.

mup setup worked perfectly.
mup deploy fails on the following:

Started TaskList: Start Meteor
[198.58.102.81] - Start Meteor
[198.58.102.81] - Start Meteor: SUCCESS
[198.58.102.81] - Verifying Deployment
[198.58.102.81] x Verifying Deployment: FAILED
	
	-----------------------------------STDERR-----------------------------------
	js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)

**Comment by s7dhansh** [comment]
Use `abernix/meteord:node-8-base`

**Comment by yannickneemaa** [comment]
I finally made it working.
If other people want to check it, here is my configuration :
- Meteor : 1.6.0.1
- MUP : 1.3.5
- `image: 'abernix/meteord:node-8-base'`

+ I deleted my node_modules folder and made a new `npm install`
+ I deleted all the docker images on my server and made a new `mup setup`
