### ISSUE TITLE
Meteor Email fails with connection timeout error when deployed using mup

### ISSUE THREAD

**Issue by vinaynb** [zodern/meteor-up#872]
I am using meteor's email package to send mails. I have set up `MAIL_URL` env variable correctly and it works locally in dev environment. However when deployed on Digital Ocean droplet using mup it fails to send emails with error logs as below

```
Exception while invoking method 'mailBill' Error: Connection timeout
at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:449:15)
at Mail._syncSendMail (packages/meteor.js:213:24)
at smtpSend (packages/email.js:110:13)
at Object.Email.send (packages/email.js:168:5)
at [object Object].mailBill (imports/api/Bills/publish.js:97:19)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
at packages/ddp-server/livedata_server.js:719:19
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
at packages/ddp-server/livedata_server.js:717:40
at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
- - - - -
at SMTPConnection._formatError (/built_app/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)
at SMTPConnection._onError (/built_app/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:531:20)
at [object Object].<anonymous> (/built_app/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:249:18)
at Timer.listOnTimeout (timers.js:92:15)
```
Here is how i am setting my MAIL_URL variable
```
 var smtp = {
                username: 'xxxxx@gmail.com',
                password: 'xxx@x#',
                server: 'smtp.gmail.com',
                port: 465
            };
            process.env.MAIL_URL = 'smtps://' +
                encodeURIComponent(smtp.username) + ':' +
                encodeURIComponent(smtp.password) + '@' +
                encodeURIComponent(smtp.server) + ':' +
                smtp.port;
```

WIll be helpful if anyone has any ideas as to why does this connection timeout occur ?

Meteor version - 1.4.4.1
Mup version 1.3.7
Email package version - 1.2.1
Node - 6.4.0

**Comment by chamithkanchana** [comment]
same issue here :(. Have you fixed that issue?

**Comment by vinaynb** [comment]
In my case issue was with my VPS provider (i.e Digital Ocean). Due to some reason they had blocked traffic on SMTP port 465 and hence emails were failing. Once the block was removed it was all good. Before doubting mup or anything else i would recommend testing if you have the required ports open on your server.

Hope this helps !
