### ISSUE TITLE
running mup setup with the reverse proxy for the first time gives errors when copying the ssl certif

### ISSUE THREAD

**Issue by ziedmahdi** [zodern/meteor-up#885]
MUP Version: 1.3.7

mup.js file
```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: 'sxxxxx',
      username: 'developer',
      pem: '../hola.pem'
    }
  },

  proxy: {
    domains: 'monsite.com',
    ssl: {
      forceSSL: true,
      crt: './certificate/monsite.com.crt',
      key: './certificate/monsite.com.key',
    },
  },

  meteor: {
    // TODO: change app name and path
    name: 'monsite-2',
    path: '../../',
    port: 80,

    servers: {
      one: {},
    },

    buildOptions: {

    },

    env: {
      ROOT_URL: 'https://monsite.com',
      
      MONGO_URL: 'mongodb://xxxx/xxxx',
      PORT: 80,
      NODE_ENV: 'production'
    },

    docker: {
      image: 'abernix/meteord:node-8.4.0-base',
      prepareBundle: true
    },

    deployCheckWaitTime: 200,

    enableUploadProgressBar: true
  }
};
```

Error
<pre>
Started TaskList: Setup Docker
[52.44.37.158] - Setup Docker
[52.44.37.158] - Setup Docker: SUCCESS

Started TaskList: Setup proxy
[52.44.37.158] - Setup Environment
[52.44.37.158] - Setup Environment: SUCCESS
[52.44.37.158] - Pushing the Startup Script
[52.44.37.158] - Pushing the Startup Script: SUCCESS
[52.44.37.158] - Cleaning Up SSL Certificates
[52.44.37.158] - Cleaning Up SSL Certificates: SUCCESS
[52.44.37.158] - Copying SSL Certificate Bundle
Failed to copy file  { Error: No such file
    at SFTPStream._transform (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/sftp.js:384:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at SFTPStream.Writable.write (_stream_writable.js:243:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2/lib/Channel.js:140:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/mup/node_modules/nodemiral/node_modules/ssh2-streams/lib/ssh.js:3163:10) code: 2, lang: '' }
</pre>

As a workaround:

1. comment the proxy part
2. run `mup setup`
3. uncomment the proxy part
4. run `mup setup`again

**Comment by zodern** [comment]
The fix will be in the next update.
