### ISSUE TITLE
throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe

### ISSUE THREAD

**Issue by timothyarmes** [zodern/meteor-up#89]
I'm trying to redeploy my app after upgrading to Meteor 1.3 beta 8. I'm now getting this error:

```
[xx.xx.xx.xx]=> Starting meteor app on port:80
[xx.xx.xx.xx]
[xx.xx.xx.xx]/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
[xx.xx.xx.xx]   throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
[xx.xx.xx.xx]         ^
[xx.xx.xx.xx]Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
[xx.xx.xx.xx]    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
[xx.xx.xx.xx]    at Module._compile (module.js:456:26)
[xx.xx.xx.xx]    at Object.Module._extensions..js (module.js:474:10)
[xx.xx.xx.xx]    at Module.load (module.js:356:32)
[xx.xx.xx.xx]    at Function.Module._load (module.js:312:12)
[xx.xx.xx.xx]    at Module.require (module.js:364:17)
[xx.xx.xx.xx]    at require (module.js:380:17)
[xx.xx.xx.xx]    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
[xx.xx.xx.xx]    at Module._compile (module.js:456:26)
[xx.xx.xx.xx]    at Object.Module._extensions..js (module.js:474:10)
```

I don't know if this problem comes from meteor or mup. Any ideas?

**Comment by madushan1000** [comment]
I think this is a problem with meteord. You can check the meteord issues page.

**Comment by phongyewtong** [comment]
I have the same problem too.

**Comment by zeroasterisk** [comment]
Getting the same problem today:

```

=> Starting meteor app on port:80

/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibe
          ^
Error: `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/bundle/bundle/programs/server/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/bundle/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by switheyw** [comment]
Not all that helpful to mark question closed when one "thinks" the answer lies elsewhere at some other
semi-specified location.
There are lots of other answers out there.  [http://stackoverflow.com/questions/13327088/meteor-bundle-fails-because-fibers-node-is-missing](url)

**Comment by MasterJames** [comment]
True but that one is 404 ? !
