### ISSUE TITLE
problem with mup deploy on window10

### ISSUE THREAD

**Issue by kakao-kong-j** [zodern/meteor-up#900]
** Hi. I have a problem with deploying using A and I have been asked questions.

If i proceed with mup deploy, it will display the following error message and it will not work. I think it seems to be working beyond the project folder. 

My project is in C: \ Users \ tpdle \ My Documents \ GitHub \ TravelBoard, 
but mup goes to C: \ Users \ tpdle \ My Documents \ GitHub \ semver \ bin \ semver. 

If you have a solution, please let me know. **

Mup version (`mup --version`):
1.4.3

Mup config (Use `mup validate --show --scrub` to remove most of the sensitive information)
```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://subdomain.subdomain.subdomain.host.com",
      "MONGO_URL": "mongodb://user:pass@subdomain.host.com:59768/travelboard"
    },
    "deployCheckWaitTime": 60,
    "type": "meteor",
    "docker": {
      "image": "abernix/meteord:base"
    }
  }
}

```

Output of command (use the `--verbose` option. Remember to remove sensitive information)
```bash
$ mup deploy --verbose
Building App Bundle Locally
C:\Users\tpdle\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

Error: ENOENT: no such file or directory, stat 'C:\Users\tpdle\My Documents\GitHub\semver\bin\semver'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.wrapper (C:\tools\fs\files.js:1594:35)
    at Object.files.(anonymous function) [as stat] (C:\tools\fs\files.js:1729:27)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:732:17)
    at C:\tools\isobuild\builder.js:559:11
    at Array.forEach (native)
    at walk (C:\tools\isobuild\builder.js:464:34)
    at C:\tools\isobuild\builder.js:556:11
    at Array.forEach (native)
    at walk (C:\tools\isobuild\builder.js:464:34)
    at Builder.copyDirectory (C:\tools\isobuild\builder.js:594:5)
    at C:\tools\isobuild\bundler.js:2253:17
    at Function._.each._.forEach (C:\Users\tpdle\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at JsImage.write (C:\tools\isobuild\bundler.js:2212:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2481:13)
    at C:\tools\isobuild\bundler.js:2600:30
    at C:\tools\isobuild\bundler.js:2735:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2725:26
    at C:\tools\isobuild\bundler.js:3066:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2899:31)
    at C:\tools\isobuild\bundler.js:2846:32
    at Object.withCache (C:\tools\fs\files.js:1694:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2846:16)
    at buildCommand (C:\tools\cli\commands.js:956:30)
    at Command.func (C:\tools\cli\commands.js:831:12)
    at C:\tools\cli\main.js:1483:23

=> Build Error. Check the logs printed above.

```

Output of `mup status` (Only if using mup 1.4 or newer).
```bash
=> Servers
  - 13.125.206.164: Ubuntu 16.04

=> Docker Status
 - 13.125.206.164: 18.02.0-ce Running

=> Meteor Status
 - 13.125.206.164: Stopped

```

**Comment by zodern** [comment]
It would be helpful to see the `meteor` command mup is running. Please run:
```powershell
$env:DEBUG = "mup*"
mup deploy --verbose
```

**Comment by kakao-kong-j** [comment]
@zodern I ran your suggestion, but I have the same problem.

**Comment by zodern** [comment]
Could you please show the output from the command?

**Comment by kakao-kong-j** [comment]
@zodern 
```
PS C:\Users\tpdle\Documents\GitHub\TravelBoard\.deploy> mup deploy --verbose
  mup:updates checking for updates +0ms
  mup:api Running command default.deploy +0ms
  mup:module:default exec => mup deploy +0ms
  mup:api Running command meteor.deploy +17ms
  mup:module:meteor exec => mup meteor deploy +0ms
  mup:api Running command meteor.push +3ms
  mup:module:meteor exec => mup meteor push +3ms
  mup:api Running command meteor.build +1ms
Building App Bundle Locally
  mup:module:meteor Build Path: C:\Users\tpdle\Documents\GitHub\TravelBoard +0ms
  mup:module:meteor Build Command:  C:\WINDOWS\system32\cmd.exe /c meteor build --directory C:\Users\tpdle\AppData\Local\Temp\mup-meteor-e830570b-1564-4aa5-a7b4-19931a3ee9b7 --architecture os.linux.x86_64 --server-only +0ms
C:\Users\tpdle\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:280
                                                throw(ex);
                                                ^

Error: ENOENT: no such file or directory, stat 'C:\Users\tpdle\Documents\GitHub\semver\bin\semver'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.wrapper (C:\tools\fs\files.js:1594:35)
    at Object.files.(anonymous function) [as stat] (C:\tools\fs\files.js:1729:27)
    at symlinkWithOverwrite (C:\tools\isobuild\builder.js:732:17)
    at C:\tools\isobuild\builder.js:559:11
    at Array.forEach (native)
    at walk (C:\tools\isobuild\builder.js:464:34)
    at C:\tools\isobuild\builder.js:556:11
    at Array.forEach (native)
    at walk (C:\tools\isobuild\builder.js:464:34)
    at Builder.copyDirectory (C:\tools\isobuild\builder.js:594:5)
    at C:\tools\isobuild\bundler.js:2253:17
    at Function._.each._.forEach (C:\Users\tpdle\AppData\Local\.meteor\packages\meteor-tool\1.5.2_2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
    at JsImage.write (C:\tools\isobuild\bundler.js:2212:7)
    at ServerTarget.write (C:\tools\isobuild\bundler.js:2481:13)
    at C:\tools\isobuild\bundler.js:2600:30
    at C:\tools\isobuild\bundler.js:2735:9
    at Array.forEach (native)
    at C:\tools\isobuild\bundler.js:2725:26
    at C:\tools\isobuild\bundler.js:3066:22
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at bundle (C:\tools\isobuild\bundler.js:2899:31)
    at C:\tools\isobuild\bundler.js:2846:32
    at Object.withCache (C:\tools\fs\files.js:1694:12)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2846:16)
    at buildCommand (C:\tools\cli\commands.js:956:30)
    at Command.func (C:\tools\cli\commands.js:831:12)
    at C:\tools\cli\main.js:1483:23

=> Build Error. Check the logs printed above.
```

**Comment by vladbalan** [comment]
@jinhokong How did you manage to fix this?

**Comment by kakao-kong-j** [comment]
@vladbalan 
It was problem because of Meteor

it was made by Meteor 1.5.2.2, but upgraded to Meteor 1.6.1 and solved the problem.
