### ISSUE TITLE
Cannot find module 'resolve-from'

### ISSUE THREAD

**Issue by khurmcandid** [zodern/meteor-up#903]
METEOR@1.6.0.1
Mup version 1.4.3

I installed cfs:gridfs and when I did a mup deploy I get the error resolve-from cannot be found. I updated mup with
```bash
npm i -g mup
mup setup
mup deploy
```

Mup.js
```js
module.exports = {
  servers: {
    one: {
      // TODO: set host address, username, and authentication method
      host: '',
      username: 'root',
      pem: '~/.ssh/id_rsa'
      // password: ''
      // or neither for authenticate from ssh-agent
    }
  },

  meteor: {
    // TODO: change app name and path
    name: '',
    path: '.',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      // TODO: Change to your app's url
      // If you are using ssl, it needs to start with https://
      ROOT_URL: '',
      MONGO_URL: '',
      // MAIL_URL: '',
      MAIL_URL: '',
    },

    docker: {
      // change to 'kadirahq/meteord' if your app is not using Meteor 1.4
      image: 'abernix/meteord:node-8.9.3-base',
      // imagePort: 80, // (default: 80, some images EXPOSE different ports)
    },

    // This is the maximum time in seconds it will wait
    // for your app to start
    
    // Add 30 seconds if the server has 512mb of ram
    // And 30 more if you have binary npm dependencies.
    deployCheckWaitTime: 180,

    // Show progress bar while uploading bundle to server
    // You might need to disable it on CI servers
    enableUploadProgressBar: true
  },

  mongo: {
    port: 27017,
    version: '3.4.1',
    servers: {
      one: {}
    }
  }
};

```

Output of command (use the `--verbose` option. Remember to remove sensitive information)
```bash
Error: Cannot find module 'resolve-from'
            at Function.Module._resolveFilename (module.js:536:15)
            at Function.Module._load (module.js:466:25)
            at Module.require (module.js:579:17)
            at require (internal/module.js:11:18)
            at Object.<anonymous> (/built_app/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/node_modules/mongodb-core/node_modules/require_optional/index.js:4:17)
            at Module._compile (module.js:635:30)
            at Object.Module._extensions..js (module.js:646:10)
            at Module.load (module.js:554:32)
            at tryModuleLoad (module.js:497:12)
            at Function.Module._load (module.js:489:3)
        => Starting meteor app on port:80
        Note: you are using a pure-JavaScript implementation of bcrypt.
        While this implementation will work correctly, it is known to be
        approximately three times slower than the native implementation.
        In order to use the native implementation instead, run

          meteor npm install --save bcrypt

        in the root directory of your application.
        /built_app/programs/server/node_modules/fibers/future.js:280
                                                        throw(ex);

```

Output of `mup status` (Only if using mup 1.4 or newer).
```bash
=> Servers
  - : Ubuntu 16.04

=> Docker Status
 - : 17.04.0-ce Running

=> Meteor Status
 - : running
    Created at 2018-03-08T16:09:08.162401199Z
    Restarted 0 times
    ENV:
     - ROOT_URL=
     - MONGO_URL=
     - MAIL_URL=
     - METEOR_SETTINGS=
     - PORT=80
     - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     - METEORD_DIR=/opt/meteord
     - NODE_VERSION=8.4.0
    Published Ports:
     - 80/tcp => 80
    App running at http://
     - Available in app's docker container: true
     - Available on server: true
     - Available on local computer: true
Error: Timed out while waiting for handshake
    at Timeout._onTimeout (C:\Users\User\AppData\Roaming\npm\node_modules\mup\node_modules\ssh2\lib\client.js:569:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

```

**Comment by khurmcandid** [comment]
Anyone?

**Comment by khurmcandid** [comment]
Sorry guys, haven't had any reply, just seeing if this is because I've written the question out in a complicated way or no one can figure it out?

**Comment by zodern** [comment]
Your app or one of it's dependencies is missing `resolve-from`. Running `meteor npm install --save resolve-from` should fix it.
