### ISSUE TITLE
Verifying Deployment: FAILED, Too much time spent restarting

### ISSUE THREAD

**Issue by andrelillvede** [zodern/meteor-up#908]
Mup version (`mup --version`):
1.4.3

Mup config (Use `mup validate --show --scrub` to remove most of the sensitive information)
```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "username"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "https://subdomain.host.com",
    },
    "docker": {
      "image": "abernix/meteord:node-8.4.0-base",
    },
    "enableUploadProgressBar": true,
    "deployCheckWaitTime": 120,
    "type": "meteor"
  }
}
```

Output of command (use the `--verbose` option. Remember to remove sensitive information)
```bash
[x.x.x.x] - Start Meteor: SUCCESS
[x.x.x.x] - Verifying Deployment
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Container has no IP Address, likely from it restarting.
Too much time spent restarting.
=> Container status:
restarted: 0 times {"Bridge":"","SandboxID":"87813fd3f9a892e2cf669886672ae86bb4e0a45dea7d25a0f5d36974335f0eff","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{"80/tcp":[{"HostIp":"0.0.0.0","HostPort":"3001"}]},"SandboxKey":"/var/run/docker/netns/87813fd3f9a8","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"services":{"IPAMConfig":null,"Links":null,"Aliases":["14090afa0adb"],"NetworkID":"8239e1def5abf3c891166ee979b5c5709f9088599b2f79eea957089599912400","EndpointID":"33074af4c5651621f237ca4558ecc85d7acebead47b624cd6c135906d935e590","Gateway":"172.20.0.1","IPAddress":"172.20.0.5","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:14:00:05","DriverOpts":null}}} {"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":22295,"ExitCode":0,"Error":"","StartedAt":"2018-03-13T09:13:09.476686298Z","FinishedAt":"0001-01-01T00:00:00Z"}
=> Logs:
=> Starting meteor app on port:80

To see more logs type 'mup logs --tail=200'

 
=> Redeploying previous version of the app
 
[46.101.227.244] x Verifying Deployment: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      Too much time spent restarting.
	=> Starting meteor app on port:80
	 
	=> Redeploying previous version of the app
	 
	
	      ------------------------------------STDOUT------------------------------------
	      Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	=> Container status:
	restarted: 0 times {"Bridge":"","SandboxID":"87813fd3f9a892e2cf669886672ae86bb4e0a45dea7d25a0f5d36974335f0eff","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{"80/tcp":[{"HostIp":"0.0.0.0","HostPort":"3001"}]},"SandboxKey":"/var/run/docker/netns/87813fd3f9a8","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"services":{"IPAMConfig":null,"Links":null,"Aliases":["14090afa0adb"],"NetworkID":"8239e1def5abf3c891166ee979b5c5709f9088599b2f79eea957089599912400","EndpointID":"33074af4c5651621f237ca4558ecc85d7acebead47b624cd6c135906d935e590","Gateway":"172.20.0.1","IPAddress":"172.20.0.5","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:14:00:05","DriverOpts":null}}} {"Status":"running","Running":true,"Paused":false,"Restarting":false,"OOMKilled":false,"Dead":false,"Pid":22295,"ExitCode":0,"Error":"","StartedAt":"2018-03-13T09:13:09.476686298Z","FinishedAt":"0001-01-01T00:00:00Z"}
	=> Logs:
	
	To see more logs type 'mup logs --tail=200'
	
	
	      ------------------------------------------------------------------------------

```

Output of `mup status` (Only if using mup 1.4 or newer).
```bash
=> Servers
  - 46.101.227.244: Ubuntu 16.04

=> Docker Status
 - 46.101.227.244: 17.12.1-ce Running

=> Meteor Status
 - x.x.x.x: running 
    Created at 2018-03-13T09:20:33.500412468Z
    Restarted 0 times
    ENV: 
     - ROOT_URL=https://xxxx
     - MONGO_URL=mongodb://mongodb:27017/xxxx
     - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
     - PORT=80
     - NODE_ENV=production
     - METEOR_SETTINGS={"public":{}}
     - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     - METEORD_DIR=/opt/meteord
     - NODE_VERSION=8.4.0
    Published Ports:
     - 80/tcp => 3001
    App running at http://x.x.x.x:80
     - Available in app's docker container: true
     - Available on server: true
     - Available on local computer: false
```

Seems like the issue is the ip check in src/plugins/meteor/assets/meteor-deploy-check.sh

```
if [ "$noIPCount" "==" "$MAX_NO_IP_COUNT" ]; then
      echo "Too much time spent restarting." 1>&2
      revert_app
      exit 1
    fi
```

If I delete the container and images on the server before doing mup deploy so there is nothing to revert to when we hit MAX_NO_IP_COUNT I still get Verifying Deployment: FAILED but the application is deployed.
 
/André

**Comment by andrelillvede** [comment]
Any updates on this?

**Comment by layik** [comment]
Seems I have a similar issue, too on an old deployment. I have not tried the `mup deploy` on a new VPS.

**Comment by zodern** [comment]
@layik could you please share the output from `Verifying Deployment`?

**Comment by layik** [comment]
Dear @zodern apologies for this late reply. Here is the error output

```
Started TaskList: Pushing Meteor App
[x.co.uk] - Pushing Meteor App Bundle to the Server
[x.co.uk] - Pushing Meteor App Bundle to the Server: SUCCESS
[x.co.uk] - Prepare Bundle
[x.co.uk] - Prepare Bundle: SUCCESS

Started TaskList: Configuring App
[x.co.uk] - Pushing the Startup Script
[x.co.uk] - Pushing the Startup Script: SUCCESS
[x.co.uk] - Sending Environment Variables
[x.co.uk] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[x.co.uk] - Start Meteor
[x.co.uk] - Start Meteor: SUCCESS
[x.co.uk] - Verifying Deployment
[x.co.uk] x Verifying Deployment: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      Too much time spent restarting.
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	=> Starting meteor app on port:80
	/built_app/programs/server/boot.js:50
	    const { pause } = require("./debug.js");
	          ^
	
	SyntaxError: Unexpected token {
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Object.Module._extensions..js (module.js:416:10)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/built_app/main.js:4:1)
	    at Module._compile (module.js:409:26)
	    at Object.Module._extensions..js (module.js:416:10)
	 
	=> Redeploying previous version of the app
	 
	
	      ------------------------------------STDOUT------------------------------------
	      Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	=> Container status:
	restarted: 9 times {"Bridge":"","SandboxID":"4997b62599351d10be0162646177cdb80e3ce4b4ddf4952164745bbe78a08e6a","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/4997b6259935","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"5796f83f65bf929b61832a2bc3cf7fe293d88a790d3cc4d4bc9474603bd640f1","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":1,"Error":"","StartedAt":"2018-03-24T10:49:18.116576454Z","FinishedAt":"2018-03-24T10:49:18.418304456Z"}
	=> Logs:
	
	To see more logs type 'mup logs --tail=200'
	
	
	      ------------------------------------------------------------------------------
	      
```

**Comment by zodern** [comment]
@layik it looks like the docker image you are using has an old version of node. You can find a docker image that is compatible with the meteor version you are using [here](http://meteor-up.com/docs#meteor-support).

**Comment by andrelillvede** [comment]
@zodern do you have any input on the original issue?

**Comment by akkerd** [comment]
@andrelillvede the solution that @zodern gave worked for me. It seems to be the same problem with the docker version in your configuration file.  As you are using Meteor 1.4, change your docker version to: 
`"docker": {
      "image": "abernix/meteord:base",
    },`
or to automatically detects the needed node version use:
`"docker": {
      "image": "zodern/meteor:root",
    },`
Then run:
`mup reconfig`
`mup deploy`

**Comment by layik** [comment]
@AkkerD and @zodern thank you, [that](https://github.com/zodern/meteor-up/issues/908#issuecomment-381065908) worked for me.

note to self: I must contribute to MUP!

**Comment by andrelillvede** [comment]
@AkkerD @zodern Nope, not using Meteor 1.4 I'm on Meteor 1.6.1.1 (and I can't find any evidence that mup thinks otherwise?). 

I'm using the docker image stated in the docs and also tried with 'zodern/meteor:root' but still getting `Verifying Deployment: FAILED"` and mup not deploying the newly build image.

My webapp container is part of a docker network I specified on the host and in the docker section of the mup config I have '--network=services' in the args field.

Can it be that the checks in meteor-deploy-check.sh cannot handle that?

**Comment by zodern** [comment]
> My webapp container is part of a docker network I specified on the host and in the docker section of the mup config I have '--network=services' in the args field.

What options did you use when creating the network?

The cause is the docker network, but this is a regression in mup since it used to support that.

**Comment by andrelillvede** [comment]
Well, I got it running by having
```
  docker: {
      image: 'abernix/meteord:node-8.9.4-base',
      args: [
        '--network=services',
      ],
      networks: ['services'],
    },
```
in my config file instead of
```
docker: {
      image: 'abernix/meteord:node-8.9.4-base',
      args: [
        '--network=services',
      ],
    },
```
¯\_(ツ)_/¯
