### ISSUE TITLE
Error when restarting: `removeImage is not defined`

### ISSUE THREAD

**Issue by SimonSimCity** [zodern/meteor-up#911]
Mup version (`mup --version`): 1.4.3

Mup config (Use `mup validate --show --scrub` to remove most of the sensitive information)
```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "my-user",
      "pem": "~/.ssh/pem"
    }
  },
  "hooks": {
    "pre.deploy": {
      "localCommand": "cd ../.. && meteor npm prune --production && meteor npm install --production"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../../",
    "volumes": {
      "/datadrive/temp": "/temp"
    },
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://subdomain.host.com",
      "MONGO_URL": "..",
      "MONGO_OPLOG_URL": "..."
    },
    "docker": {
      "image": "abernix/meteord:node-8-base"
    },
    "deployCheckWaitTime": 60,
    "enableUploadProgressBar": false,
    "type": "meteor"
  }
}
✓ Config is valid
```

Output of command (use the `--verbose` option. Remember to remove sensitive information)
```bash
Started TaskList: Restart Meteor
[13.94.243.130] - Stop Meteor
Error response from daemon: No such container: stripes
Error response from daemon: No such container: stripes-frontend
Error response from daemon: No such container: stripes-nginx-letsencrypt
Error response from daemon: No such container: stripes-nginx-proxy
Error response from daemon: endpoint stripes not found
Error response from daemon: endpoint stripes-frontend not found
Error response from daemon: endpoint stripes-nginx-letsencrypt not found
Error response from daemon: endpoint stripes-nginx-proxy not found
[13.94.243.130] - Stop Meteor: SUCCESS
[13.94.243.130] - Start Meteor
undefined:25
  throw err;
  ^

ReferenceError: ejs:8
    6| IMAGE=mup-<%= appName.toLowerCase() %>
    7| 
 >> 8| <% if (removeImage) { %>
    9| echo "Removing images"
    10| # Run when the docker image doesn't support prepare-bundle.sh.
    11| # This command is only run during a deploy.

removeImage is not defined
    at eval (eval at exports.compile (/Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:30:186)
    at eval (eval at exports.compile (/Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:30:1062)
    at /Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/node_modules/ejs/lib/ejs.js:250:15
    at /Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/node_modules/nodemiral/lib/session.js:181:55
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

Output of `mup status` (Only if using mup 1.4 or newer).
```bash
TypeError: Cannot read property 'trim' of undefined
    at /Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/lib/plugins/default/command-handlers.js:45:38
    at Array.forEach (<anonymous>)
    at Object._callee$ (/Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/lib/plugins/default/command-handlers.js:30:21)
    at tryCatch (/Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/lib/plugins/default/command-handlers.js:108:191)
    at /Users/my-user/.nvm/versions/node/v8.9.3/lib/node_modules/mup/lib/plugins/default/command-handlers.js:108:361
    at <anonymous>
```

I can however confirm that calling `mup start` can start the meteor application and `mup stop --verbose && mup start --verbose` also works compared to `mup restart`.

I am currently able to reproduce it at any time.

**Comment by Floriferous** [comment]
Encountering the same issue, is there a workaround for the moment?

Does `mup stop && mup start` essentially do the same thing when run one after the other?

**Comment by zodern** [comment]
> Does mup stop && mup start essentially do the same thing when run one after the other?

Yes, except the app will be stopped on all of the servers at the same time, instead of one at a time.

**Comment by kodie** [comment]
Experiencing the same issue with `mup@v1.4.3` and `meteor@1.4.3.2`.

`mup stop && mup start` works fine.

**Comment by zodern** [comment]
This will be fixed in the next update.
