### ISSUE TITLE
Vulcan Js and Mup

### ISSUE THREAD

**Issue by anderskitson** [zodern/meteor-up#922]
I am using Vulcan Js, my mup.js and settings.json file is located in the root directory under ./deploy I can't get passed the first part of mup setup.

Mup version : 1.4.3

mup.js config
```
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "root",
      "password": "password"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local"
    },
    "docker": {
      "image": "abernix/meteord:base",
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    }
  }
}
```

mup setup error
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 165.227.41.198:22
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

Output of `mup status` 
```bash
Error: Timed out while waiting for handshake
    at Timeout._onTimeout (C:\Users\Anders\AppData\Roaming\nvm\v8.11.1\node_modules\mup\node_modules\ssh2\lib\client.js:569:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by zodern** [comment]
Are you able to ssh into the server?

**Comment by anderskitson** [comment]
Yes I am

**Comment by anderskitson** [comment]
It is fixed now it had something to do with the fact when I ssh in I was using ubuntu bash on windows and when I ran mup setup in powershell it didn't have the matching rsa key, so I ran bash in powershell ssh in and then ran mup setup again and it worked.
