### ISSUE TITLE
How to config `mup.js` whit Mongo Atlas?

### ISSUE THREAD

**Issue by thearabbit** [zodern/meteor-up#930]
Mup version: 1.4.2

Mup config
```js
module.exports = {
    servers: {
        one: {
            // TODO: set host address, username, and authentication method
            host: "1.2.3.4", // DigitalOcean
            username: "root",
            // pem: './path/to/pem'
            password: "123456"
            // or neither for authenticate from ssh-agent
        }
    },

    meteor: {
        // TODO: change app name and path
        name: "testing",
        path: "../meteor-app",

        servers: {
            one: {}
        },

        buildOptions: {
            serverOnly: true
        },

        env: {
            // TODO: Change to your app's url
            // If you are using ssl, it needs to start with https://
            ROOT_URL: "http://1.2.3.4",
            MONGO_URL: "mongodb://theara:<PASSWORD>@rabbit-shard-00-00-1kplv.mongodb.net:27017,rabbit-shard-00-01-1kplv.mongodb.net:27017,rabbit-shard-00-02-1kplv.mongodb.net:27017/dbName?ssl=true&replicaSet=rabbit-shard-0&authSource=admin",
            PORT: 9999
        },

        // This is the maximum time in seconds it will wait
        // for your app to start
        // Add 30 seconds if the server has 512mb of ram
        // And 30 more if you have binary npm dependencies.
        deployCheckWaitTime: 60,
        docker: {
            image: "abernix/meteord:base",
            args: [
                "-v /etc/timezone:/etc/timezone",
                "-v /etc/localtime:/etc/localtime"
            ]
        },

        // Show progress bar while uploading bundle to server
        // You might need to disable it on CI servers
        enableUploadProgressBar: true
    },
};
```
### And then replace the Password

Output of command
```bash
Started TaskList: Start Meteor
[206.189.45.127] - Start Meteor
[206.189.45.127] - Start Meteor: SUCCESS
[206.189.45.127] - Verifying Deployment
[206.189.45.127] x Verifying Deployment: FAILED

	      ------------------------------------STDERR------------------------------------
	      s:784:19)
	    at new Mongo.Collection (packages/mongo/collection.js:103:40)
	    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
	    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
	    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
	    at fileEvaluate (packages/modules-runtime.js:181:9)
	    - - - - -
	    at [object Object]._onTimeout (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:653:33)
	    at Timer.listOnTimeout (timers.js:92:15)
	=> Starting meteor app on port:80

	/built_app/programs/server/node_modules/fibers/future.js:313
							throw(ex);
							^
	MongoError: no valid replicaset members found
	    at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:449:15)
	    at new MongoConnection (packages/mongo/mongo_driver.js:219:27)
	    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
	    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
	    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
	    at new Mongo.Collection (packages/mongo/collection.js:103:40)
	    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
	    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
	    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
	    at fileEvaluate (packages/modules-runtime.js:181:9)
	    - - - - -
	    at [object Object]._onTimeout (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:653:33)
	    at Timer.listOnTimeout (timers.js:92:15)
	=> Starting meteor app on port:80

	/built_app/programs/server/node_modules/fibers/future.js:313
							throw(ex);
							^
	MongoError: no valid replicaset members found
	    at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:449:15)
	    at new MongoConnection (packages/mongo/mongo_driver.js:219:27)
	    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
	    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
	    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
	    at new Mongo.Collection (packages/mongo/collection.js:103:40)
	    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
	    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
	    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
	    at fileEvaluate (packages/modules-runtime.js:181:9)
	    - - - - -
	    at [object Object]._onTimeout (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:653:33)
	    at Timer.listOnTimeout (timers.js:92:15)
	=> Starting meteor app on port:80

	/built_app/programs/server/node_modules/fibers/future.js:313
							throw(ex);
							^
	MongoError: no valid replicaset members found
	    at Object.Future.wait (/built_app/programs/server/node_modules/fibers/future.js:449:15)
	    at new MongoConnection (packages/mongo/mongo_driver.js:219:27)
	    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:16)
	    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:10)
	    at Object.defaultRemoteCollectionDriver (packages/underscore.js:784:19)
	    at new Mongo.Collection (packages/mongo/collection.js:103:40)
	    at AccountsServer.AccountsCommon (packages/accounts-base/accounts_common.js:23:18)
	    at new AccountsServer (packages/accounts-base/accounts_server.js:18:5)
	    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
	    at fileEvaluate (packages/modules-runtime.js:181:9)
	    - - - - -
	    at [object Object]._onTimeout (/built_app/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/replset.js:653:33)
	    at Timer.listOnTimeout (timers.js:92:15)

	      ------------------------------------STDOUT------------------------------------
	      Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	Container has no IP Address, likely from it restarting.
	=> Container status:
	restarted: 7 times {"Bridge":"","SandboxID":"549484effe7a3f501fd740a873b50a53052ccc4b3ba949c2c5b4752eae200de6","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":null,"SandboxKey":"/var/run/docker/netns/549484effe7a","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"76f067df3d778dff39d5468beec020426c458b45405405dee61d69fb5255b43f","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":""}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":1,"Error":"","StartedAt":"2018-04-14T05:37:31.06981389Z","FinishedAt":"2018-04-14T05:37:34.862582971Z"}
	=> Logs:

	To see more logs type 'mup logs --tail=200'


	      ------------------------------------------------------------------------------
```

**Comment by cunneen** [comment]
Your config looks OK to me. In the 'security' tab of your Atlas web console, under 'IP whitelist', have you enabled access to  your app server machine's IP address ?

**Comment by thearabbit** [comment]
Thanks for your reply.
Yes I have

![image](https://user-images.githubusercontent.com/4495160/38845466-c0814152-4221-11e8-8537-bd35cbd7b688.png)

**Comment by cunneen** [comment]
(In Atlas) Temporarily try allowing all IP's. If your meteor server can connect, then that is the issue.

**Comment by thearabbit** [comment]
Excuse me, I don't understand what you mean?
You would like to see full IP?

![image](https://user-images.githubusercontent.com/4495160/38845851-a0858122-4223-11e8-974d-e6ba2332008d.png)

**Comment by cunneen** [comment]
No. I mean add `0.0.0.0/0` to allow all IP addresses.

**Comment by thearabbit** [comment]
OK, I try again.
![image](https://user-images.githubusercontent.com/4495160/38846586-5a2316f0-4227-11e8-904b-30d39c818317.png)

Now it work fine. Very thanks
-----
Excuse me have one problem with run `meteor` local to this
```
// root path
MONGO_URL=mongodb://theara:<PASSWORD>@rabbit-shard-00-00-1kplv.mongodb.net:27017,rabbit-shard-00-01-1kplv.mongodb.net:27017,rabbit-shard-00-02-1kplv.mongodb.net:27017/dbName?ssl=true&replicaSet=rabbit-shard-0&authSource=admin meteor
```
Get error
```
zsh: parse error near `&'
```
Could help me again?

**Comment by thearabbit** [comment]
Now it is OK
[forum](https://forums.meteor.com/t/ho-to-run-local-meteor-with-mongo-atlas-url/43254)

**Comment by AhmedMohamedG** [comment]
Hi,

Can you please update this answer I want to deploy to EC2 server and Atlas
