### ISSUE TITLE
Cannot find module './lib'

### ISSUE THREAD

**Issue by valisjan** [zodern/meteor-up#95]
After following to install dev version I get this error on mup deploy command:

`Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/jose/intranet/meteor-up/index.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
`
I cloned mupx in the same directory where de app is, executed npm install and npm link (with sudo). I made .deploy directory on the app root and mup deploy. The mup.js file semms to be ok.
Any ideas?
Thank you.

**Comment by madushan1000** [comment]
You have to run `npm run prepublish` before you can use mup. This was missing in the readme. I'll update it.
