### ISSUE TITLE
Running into this error each time I try to deploy my app

### ISSUE THREAD

**Issue by ayhid** [zodern/meteor-up#962]
Lately i am running into this error when I try to deploy my app does any one have an idea how to solve this please ?

Mup version (`mup --version`): 1.4.5

Mup config

```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    },
    "two": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    },
    "three": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    },
    "four": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    },
    "five": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://subdomain.subdomain.subdomain.host.com",
      "MONGO_URL": "mongodb://user:pass@subdomain.host.com"
    },
    "docker": {
      "image": "abernix/meteord:node-8.11.2-base",
      "stopAppDuringPrepareBundle": true
    },
    "enableUploadProgressBar": true,
    "deployCheckWaitTime": 60,
    "type": "meteor"
  }
}
```

Output of command `mup deploy`

```bash
Building App Bundle Locally
   Preparing project                         [ProgressDisplayFull keepalive                                                                           app/client/lib/semantic-ui/semantic.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
Node#moveTo was deprecated. Use Container#append.

Started TaskList: Pushing Meteor App
[1.2.3.4] - Pushing Meteor App Bundle to the Server
[1.2.3.4] - Pushing Meteor App Bundle to the Server: SUCCESS
[1.2.3.4] - Prepare Bundle
node-8.11.2-base: Pulling from abernix/meteord
5dfbbcdbbb10: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
4d4ee6f756a2: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
57f5e65087c6: Already exists
de4c8cd95f13: Already exists
34ff09f37fe5: Already exists
7cb4acd52089: Already exists
a3ed95caeb02: Already exists
493542de6e4e: Already exists
a3ed95caeb02: Already exists
Digest: sha256:c249becef99af39e9ac045259eb7d3ffa51cdfb9304874d5bc23a5eaff11af7e
Status: Image is up to date for abernix/meteord:node-8.11.2-base
Finished Extracting
Creating Dockerfile
Finished creating Dockerfile
Building image
Sending build context to Docker daemon  120.3MB
Step 1/6 : FROM abernix/meteord:node-8.11.2-base
# Executing 1 build trigger
 ---> Using cache
 ---> b6c12fb3ea5d
Step 2/6 : RUN mkdir /built_app || true
 ---> Using cache
 ---> ef8e45676e3a
Step 3/6 : ENV ROOT_URL=http://myrooturl.com
 ---> Using cache
 ---> 0007d594af07
Step 4/6 : ENV MONGO_URL=mongodb://mymongourl
 ---> Using cache
 ---> 5dbf524704a7
Step 5/6 : COPY ./ /built_app
 ---> Using cache
 ---> 4ee8e223c07a
Step 6/6 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Running in 9661c7b72f25

> fibers@2.0.0 install /built_app/programs/server/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@ install /built_app/programs/server
> node npm-rebuild.js


> contextify@0.1.15 install /built_app/programs/server/npm/node_modules/contextify
> node-gyp rebuild

make: Entering directory '/built_app/programs/server/npm/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function 'static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)':
../src/contextify.cc:131:68: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated (declared at /root/.node-gyp/8.11.2/include/node/v8.h:3851): Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
../src/contextify.cc:150:16: error: 'class v8::ObjectTemplate' has no member named 'SetAccessCheckCallbacks'
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function 'static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)':
../src/contextify.cc:182:80: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/8.11.2/include/node/v8.h:3403): Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
../src/contextify.cc: In static member function 'static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)':
../src/contextify.cc:209:67: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/8.11.2/include/node/v8.h:3403): Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
../src/contextify.cc:210:71: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/8.11.2/include/node/v8.h:3403): Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
contextify.target.mk:95: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/built_app/programs/server/npm/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-1060-aws
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /built_app/programs/server/npm/node_modules/contextify
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-12T22_26_55_206Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-dev-bundle@ install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-12T22_26_55_244Z-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
[1.2.3.4] x Prepare Bundle: FAILED

	      ------------------------------------STDERR------------------------------------
	      The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1

	      ------------------------------------STDOUT------------------------------------
	      New(ctx->sandbox)->GetRealNamedProperty(property);
	                                                                                ^
	../src/contextify.cc: In static member function 'static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)':
	../src/contextify.cc:209:67: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/8.11.2/include/node/v8.h:3403): Use maybe version [-Wdeprecated-declarations]
	         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
	                                                                   ^
	../src/contextify.cc:210:71: warning: 'v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)' is deprecated (declared at /root/.node-gyp/8.11.2/include/node/v8.h:3403): Use maybe version [-Wdeprecated-declarations]
	             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
	                                                                       ^
	contextify.target.mk:95: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
	make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
	make: Leaving directory '/built_app/programs/server/npm/node_modules/contextify/build'
	gyp ERR! build error
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
	gyp ERR! stack     at emitTwo (events.js:126:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
	gyp ERR! System Linux 4.4.0-1060-aws
	gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
	gyp ERR! cwd /built_app/programs/server/npm/node_modules/contextify
	gyp ERR! node -v v8.11.2
	gyp ERR! node-gyp -v v3.6.2
	gyp ERR! not ok
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the contextify@0.1.15 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2018-06-12T22_26_55_206Z-debug.log
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! meteor-dev-bundle@ install: `node npm-rebuild.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the meteor-dev-bundle@ install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2018-06-12T22_26_55_244Z-debug.log
```

**Comment by zodern** [comment]
@ayhid did you find a solution?

**Comment by ayhid** [comment]
Yes I don't remember what I've done to get it fixed but it is. closing this issue, Thanks
