### ISSUE TITLE
Problem Verifying Deployment

### ISSUE THREAD

**Issue by danbugs** [zodern/meteor-up#986]
Mup version (`mup --version`): 1.4.5

Mup config (`mup validate --show --scrub`):

```
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "env": {
      "ROOT_URL": "http://subdomain.host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app"
    },
    "docker": {
      "image": "zodern/meteor:root",
      "stopAppDuringPrepareBundle": true,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "oplog": true,
    "port": 27017,
    "servers": {
      "one": {}
    }
  }
}
```

Output of command (`mup deploy`):

```
Started TaskList: Configuring App
[35.155.145.145] - Pushing the Startup Script
[35.155.145.145] - Pushing the Startup Script: SUCCESS
[35.155.145.145] - Sending Environment Variables
[35.155.145.145] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[35.155.145.145] - Start Meteor
[35.155.145.145] - Start Meteor: SUCCESS
[35.155.145.145] - Verifying Deployment
[35.155.145.145] x Verifying Deployment: FAILED
	
	      ------------------------------------STDERR------------------------------------
	       Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.3 port 80: Connection refused
	Container spent too much time restarting.
	=> Extracting bundle
	=> Setting node version
	
	/home/app/scripts/node-version.js:59
	  var majorVersion = nodeVersion.split('.')[0];
	                                 ^
	TypeError: Cannot call method 'split' of null
	    at Object.<anonymous> (/home/app/scripts/node-version.js:59:34)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:945:3
	Found /bundle/bundle.tar.gz
	mode of 'bundle.tar.gz' retained as 0777 (rwxrwxrwx)
	=> Extracting bundle
	=> Setting node version
	
	/home/app/scripts/node-version.js:59
	  var majorVersion = nodeVersion.split('.')[0];
	                                 ^
	TypeError: Cannot call method 'split' of null
	    at Object.<anonymous> (/home/app/scripts/node-version.js:59:34)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:945:3
	Found /bundle/bundle.tar.gz
	mode of 'bundle.tar.gz' retained as 0777 (rwxrwxrwx)
	=> Extracting bundle
	=> Setting node version
	
	/home/app/scripts/node-version.js:59
	  var majorVersion = nodeVersion.split('.')[0];
	                                 ^
	TypeError: Cannot call method 'split' of null
	    at Object.<anonymous> (/home/app/scripts/node-version.js:59:34)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:945:3
	Found /bundle/bundle.tar.gz
	mode of 'bundle.tar.gz' retained as 0777 (rwxrwxrwx)
	=> Extracting bundle
	=> Setting node version
	
	/home/app/scripts/node-version.js:59
	  var majorVersion = nodeVersion.split('.')[0];
	                                 ^
	TypeError: Cannot call method 'split' of null
	    at Object.<anonymous> (/home/app/scripts/node-version.js:59:34)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:945:3
	Found /bundle/bundle.tar.gz
	mode of 'bundle.tar.gz' retained as 0777 (rwxrwxrwx)
	=> Extracting bundle
	=> Setting node version
	
	/home/app/scripts/node-version.js:59
	  var majorVersion = nodeVersion.split('.')[0];
	                                 ^
	TypeError: Cannot call method 'split' of null
	    at Object.<anonymous> (/home/app/scripts/node-version.js:59:34)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:945:3
	Found /bundle/bundle.tar.gz
	mode of 'bundle.tar.gz' retained as 0777 (rwxrwxrwx)
	=> Extracting bundle
	=> Setting node version
	
	/home/app/scripts/node-version.js:59
	  var majorVersion = nodeVersion.split('.')[0];
	                                 ^
	TypeError: Cannot call method 'split' of null
	    at Object.<anonymous> (/home/app/scripts/node-version.js:59:34)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Function.Module.runMain (module.js:497:10)
	    at startup (node.js:119:16)
	    at node.js:945:3
	 
	=> Redeploying previous version of the app
	 
	
	      ------------------------------------STDOUT------------------------------------
	      Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	=> Container status:
	restarted: 8 times {"Bridge":"","SandboxID":"23f8e1b9b01d3bedc16cc2025f9a0945a6946cd674792db0cc92cc32258b54d5","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/23f8e1b9b01d","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"275e5bb4aebfb491f6b6946ddea53235781e9653ee4ecfbe843842ecfddf323e","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":8,"Error":"","StartedAt":"2018-08-01T02:57:24.438557517Z","FinishedAt":"2018-08-01T02:57:25.608770052Z"}
	=> Logs:
	
To see more logs type 'mup logs --tail=200'
```

Any help is appreciated! 

Thanks in advance!

chiarld.

**Comment by danbugs** [comment]
Did some stuff. Now the error is this:
```
Started TaskList: Configuring App
[54.214.101.98] - Pushing the Startup Script
[54.214.101.98] - Pushing the Startup Script: SUCCESS
[54.214.101.98] - Sending Environment Variables
[54.214.101.98] - Sending Environment Variables: SUCCESS

Started TaskList: Start Meteor
[54.214.101.98] - Start Meteor
[54.214.101.98] - Start Meteor: SUCCESS
[54.214.101.98] - Verifying Deployment
[54.214.101.98] x Verifying Deployment: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      5)
	    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:791:1)
	    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:631:1)
	    at setupUsersCollection (accounts_server.js:1413:9)
	    at new AccountsServer (accounts_server.js:49:5)
	    at Package (globals_server.js:5:12)
	    at /bundle/bundle/programs/server/packages/accounts-base.js:1813:4
	    at /bundle/bundle/programs/server/packages/accounts-base.js:1824:3
	    at /bundle/bundle/programs/server/boot.js:242:10
	    at Array.forEach (native)
	    - - - - -
	    at Object.toError (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
	    at __executeInsertCommand (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1926:27)
	    at Db._executeInsertCommand (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:2028:5)
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1348:12
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1442:20
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:16
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
	    at Server.Base._callHandler (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
	    at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
	Found /bundle/bundle.tar.gz
	mode of 'bundle.tar.gz' retained as 0777 (rwxrwxrwx)
	=> Extracting bundle
	=> Setting node version
	NODE_VERSION=0.10.48
	v0.10.48 is already installed.
	Now using node v0.10.48 (npm v3.10.10)
	Now using node v0.10.48 (npm v3.10.10)
	=> Installing npm dependencies
	npm WARN meteor-dev-bundle@0.0.0 No description
	npm WARN meteor-dev-bundle@0.0.0 No repository field.
	npm WARN meteor-dev-bundle@0.0.0 No license field.
	=> Starting meteor app on port 80
	
	/bundle/bundle/programs/server/node_modules/fibers/future.js:278
							throw(ex);
							      ^
	MongoError: driver is incompatible with this server version
	    at Object.Future.wait (/bundle/bundle/programs/server/node_modules/fibers/future.js:398:15)
	    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:791:1)
	    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:631:1)
	    at setupUsersCollection (accounts_server.js:1413:9)
	    at new AccountsServer (accounts_server.js:49:5)
	    at Package (globals_server.js:5:12)
	    at /bundle/bundle/programs/server/packages/accounts-base.js:1813:4
	    at /bundle/bundle/programs/server/packages/accounts-base.js:1824:3
	    at /bundle/bundle/programs/server/boot.js:242:10
	    at Array.forEach (native)
	    - - - - -
	    at Object.toError (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
	    at __executeInsertCommand (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1926:27)
	    at Db._executeInsertCommand (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:2028:5)
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1348:12
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1442:20
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1196:16
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
	    at Server.Base._callHandler (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
	    at /bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
	    at [object Object].MongoReply.parseBody (/bundle/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
	
	      ------------------------------------STDOUT------------------------------------
	      Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	Container has no IP Address, likely from the app crashing.
	=> Container status:
	restarted: 7 times {"Bridge":"","SandboxID":"f6d43d3e2aef517bba995ebb9e93e237a49cb014343e1bc9cd71891d34245b30","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/f6d43d3e2aef","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"e4eea6686df1ab9b26e9497cdb932525d962fb71fbeffe30109e72b48408e971","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}} {"Status":"restarting","Running":true,"Paused":false,"Restarting":true,"OOMKilled":false,"Dead":false,"Pid":0,"ExitCode":8,"Error":"","StartedAt":"2018-08-01T04:17:38.85605397Z","FinishedAt":"2018-08-01T04:17:44.776277227Z"}
	=> Logs:
	
	To see more logs type 'mup logs --tail=200'
	
	
	      ------------------------------------------------------------------------------

```

**Comment by zodern** [comment]
What version of Meteor are you using?

**Comment by danbugs** [comment]
Hey @zodern , 

I was actually just about to update this issue saying I fixed it. I believe the problem was an incompatibility between my Meteor version (1.2) and MongoDB (3.4.1). I updated Meteor to 1.4 and all ran smoothly! 

Thanks a lot!
