### ISSUE TITLE
Pushing Meteor App: FAILED (throw er; // Unhandled 'error' event)

### ISSUE THREAD

**Issue by danbugs** [zodern/meteor-up#987]
Hello! 

How's it going?

I've deployed my app but now I've done some changes to the source code and wanted to run `mup reconfig` to update in the web. Now; however, it fails to push the meteor app.

**Mup version**
` 1.4.5`

**Mup config**
```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "http://subdomain.host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app"
    },
    "docker": {
      "image": "abernix/meteord:base",
      "stopAppDuringPrepareBundle": true,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "port": 27017,
    "servers": {
      "one": {}
    }
  }
}
```

**Output of command (`mup deploy --verbose`)**
```bash
Building App Bundle Locally

Started TaskList: Pushing Meteor App
[54.214.101.98] - Pushing Meteor App Bundle to the Server
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.214.101.98:22
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```
Any help is appreciated!

Thanks a lot!

chiarld.

**Comment by danbugs** [comment]
Oh, and my meteor version is `1.4`

**Comment by danbugs** [comment]
Just tested, now the same error occurs with `mup setup`

```bash

Started TaskList: Setup Docker
[54.214.101.98] - Setup Docker
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 54.214.101.98:22
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

**Comment by danbugs** [comment]
Figured it out! 

My security group was missing an SSH rule for port 22! 

Closing the thread!
