### ISSUE TITLE
mup deploy: The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1

### ISSUE THREAD

**Issue by OptimisticLock** [zodern/meteor-up#989]
Mup version (`mup --version`): 1.4.5

Mup config

```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "ubuntu",
      "pem": "~/.ssh/pem"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {},
    "env": {
      "ROOT_URL": "http://host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local"
    },
    "docker": {
      "image": "abernix/meteord:node-8.4.0-base",
      "stopAppDuringPrepareBundle": true,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    }
  }
}
✓ Config is valid


```

Output of command
```bash

Not building app. Using build from previous deploy at
/var/folders/zh/mxbfkhs117q3ymf4tt_5b4vw0000gn/T/mup-meteor-dd6d9ed8-20e4-4aae-88a6-e6b00e882fd9
[34m[1m
Started TaskList: Pushing Meteor App[22m[39m
[36m[35m[52.15.75.146] [39m- Pushing Meteor App Bundle to the Server[39m
[36m[35m[52.15.75.146] [39m[32m- Pushing Meteor App Bundle to the Server: SUCCESS[39m[39m
[36m[35m[52.15.75.146] [39m- Prepare Bundle[39m
[31m[1m[35m[52.15.75.146] [39m[31mx Prepare Bundle: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	
	      ------------------------------------STDOUT------------------------------------
	      here
	../src/fibers.cc:54:3: error: no matching function for call to 'v8::Persistent<v8::Object>::SetWeak(void*&, <unresolved overloaded function type>)'
	   handle.SetWeak(val, WeakCallbackShim<F>);
	   ^
	[0m[91m../src/fibers.cc:54:3: note: candidates are:
	[0m[91mIn file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
	                 from ../src/coroutine.h:1,
	                 from ../src/fibers.cc:1:
	/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note: template<class P> void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = P; T = v8::Object]
	   V8_INLINE void SetWeak(P* parameter,
	                  ^
	[0m[91m/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note:   template argument deduction/substitution failed:
	[0m[91m../src/fibers.cc:54:3: note:   candidate expects 3 arguments, 2 provided
	   handle.SetWeak(val, WeakCallbackShim<F>);
	   ^
	[0m[91mIn file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
	                 from ../src/coroutine.h:1,
	                 from ../src/fibers.cc:1:
	/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note: void v8::PersistentBase<T>::SetWeak() [with T = v8::Object]
	   V8_INLINE void SetWeak();
	                  ^
	[0m[91m/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note:   candidate expects 0 arguments, 2 provided
	[0m[91m../src/fibers.cc: In function 'v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)':
	../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
	  }
	  ^
```

**Comment by poojabansal** [comment]
I am facing the same issue. @OptimisticLock were you able to resolve it?

**Comment by zodern** [comment]
What does `mup deploy --verbose` show?

**Comment by poojabansal** [comment]
@zodern  here is the output: 

```mup deploy --verbose
Building App Bundle Locally
                                              
Started TaskList: Pushing Meteor App
[52.88.204.190] - Pushing Meteor App Bundle to the Server
[52.88.204.190] - Pushing Meteor App Bundle to the Server: SUCCESS
[52.88.204.190] - Prepare Bundle
node-8.4.0-base: Pulling from abernix/meteord
Digest: sha256:04f44cf999da383d11de77027ced8b70818222c9890a405ce10803af3ee5a642
Status: Image is up to date for abernix/meteord:node-8.4.0-base
Finished Extracting
Creating Dockerfile
Finished creating Dockerfile
Building image
Sending build context to Docker daemon  37.35MB
Step 1/6 : FROM abernix/meteord:node-8.4.0-base
# Executing 1 build trigger
 ---> Using cache
 ---> ea65e57bd001
Step 2/6 : RUN mkdir /built_app || true
 ---> Using cache
 ---> 2a21fd573c45
Step 3/6 : ENV ROOT_URL=http://abcd.xyz.com
 ---> Using cache
 ---> 6f9db5757535
Step 4/6 : ENV MONGO_URL=mongodb://mongodb:27017/abcdefg
 ---> Using cache
 ---> caf0c7557b26
Step 5/6 : COPY ./ /built_app
 ---> 2452c811ba23
Step 6/6 : RUN cd  /built_app/programs/server &&     npm install --unsafe-perm
 ---> Running in ee240878c02c
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
WARN notice [SECURITY] semver has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=semver&version=4.1.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> fibers@1.0.5 install /built_app/programs/server/node_modules/fibers
> node ./build.js

(node:37) [DEP0006] DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
make: Entering directory '/built_app/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:48:34: error: 'WeakCallbackData' in namespace 'v8' does not name a template type
  void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                  ^
../src/fibers.cc:48:50: error: expected ',' or '...' before '<' token
  void WeakCallbackShim(const v8::WeakCallbackData<T, P>& data) {
                                                  ^
../src/fibers.cc: In function 'void uni::WeakCallbackShim(int)':
../src/fibers.cc:49:5: error: 'data' was not declared in this scope
   F(data.GetParameter());
     ^
../src/fibers.cc: In function 'v8::Handle<v8::String> uni::NewLatin1String(v8::Isolate*, const char*)':
../src/fibers.cc:101:64: warning: 'static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:2624): Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
../src/fibers.cc: In function 'v8::Handle<v8::String> uni::NewLatin1Symbol(v8::Isolate*, const char*)':
../src/fibers.cc:105:64: warning: 'static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:2624): Use maybe version [-Wdeprecated-declarations]
   return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                ^
../src/fibers.cc: In function 'v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)':
../src/fibers.cc:132:54: error: no matching function for call to 'v8::Signature::New(v8::Isolate*&, v8::Handle<v8::FunctionTemplate>&, int&, v8::Handle<v8::FunctionTemplate>*&)'
   return Signature::New(isolate, receiver, argc, argv);
                                                      ^
../src/fibers.cc:132:54: note: candidate is:
In file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/8.4.0/include/node/v8.h:5826:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Local<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/root/.node-gyp/8.4.0/include/node/v8.h:5826:27: note:   candidate expects 2 arguments, 4 provided
../src/fibers.cc: In function 'void uni::SetResourceConstraints(v8::Isolate*, v8::ResourceConstraints*)':
../src/fibers.cc:140:3: error: 'SetResourceConstraints' is not a member of 'v8'
   v8::SetResourceConstraints(isolate, constraints);
   ^
../src/fibers.cc:140:3: note: suggested alternative:
../src/fibers.cc:139:7: note:   'uni::SetResourceConstraints'
  void SetResourceConstraints(Isolate* isolate, ResourceConstraints* constraints) {
       ^
../src/fibers.cc: In static member function 'static uni::FunctionType Fiber::New(const Arguments&)':
../src/fibers.cc:397:99: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3787): Use maybe version [-Wdeprecated-declarations]
     return uni::Return(uni::Deref(Isolate::GetCurrent(), tmpl)->GetFunction()->NewInstance(1, argv), args);
                                                                                                   ^
../src/fibers.cc: In static member function 'static void Fiber::RunFiber(void**)':
../src/fibers.cc:588:14: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:8157): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
../src/fibers.cc: In static member function 'static void Fiber::SetPoolSize(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&)':
../src/fibers.cc:707:43: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:9578): Use maybe version [-Wdeprecated-declarations]
    Coroutine::pool_size = value->ToNumber()->Value();
                                           ^
../src/fibers.cc: In static member function 'static void Fiber::Init(v8::Handle<v8::Object>)':
../src/fibers.cc:761:72: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3120): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "current"), GetCurrent);
                                                                        ^
../src/fibers.cc:762:87: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3120): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "poolSize"), GetPoolSize, SetPoolSize);
                                                                                       ^
../src/fibers.cc:763:84: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::String>, v8::AccessorGetterCallback, v8::AccessorSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /root/.node-gyp/8.4.0/include/node/v8.h:3120): Use maybe version [-Wdeprecated-declarations]
    fn->SetAccessor(uni::NewLatin1Symbol(isolate, "fibersCreated"), GetFibersCreated);
                                                                                    ^
../src/fibers.cc: In instantiation of 'void uni::MakeWeak(v8::Isolate*, v8::Persistent<T>&, P*) [with void (* F)(void*) = Fiber::WeakCallback; T = v8::Object; P = void]':
../src/fibers.cc:315:60:   required from here
../src/fibers.cc:54:3: error: no matching function for call to 'v8::Persistent<v8::Object>::SetWeak(void*&, <unresolved overloaded function type>)'
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^
../src/fibers.cc:54:3: note: candidates are:
In file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note: template<class P> void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = P; T = v8::Object]
   V8_INLINE void SetWeak(P* parameter,
                  ^
/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note:   template argument deduction/substitution failed:
../src/fibers.cc:54:3: note:   candidate expects 3 arguments, 2 provided
   handle.SetWeak(val, WeakCallbackShim<F>);
   ^
In file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note: void v8::PersistentBase<T>::SetWeak() [with T = v8::Object]
   V8_INLINE void SetWeak();
                  ^
/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note:   candidate expects 0 arguments, 2 provided
../src/fibers.cc: In function 'v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)':
../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
fibers.target.mk:102: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/built_app/programs/server/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-29-generic
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /built_app/programs/server/node_modules/fibers
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed
npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-29T21_21_20_234Z-debug.log
The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
[52.88.204.190] x Prepare Bundle: FAILED
	
	      ------------------------------------STDERR------------------------------------
	      The command '/bin/sh -c cd  /built_app/programs/server &&     npm install --unsafe-perm' returned a non-zero code: 1
	
	      ------------------------------------STDOUT------------------------------------
	      v8::Object>::SetWeak(void*&, <unresolved overloaded function type>)'
	   handle.SetWeak(val, WeakCallbackShim<F>);
	   ^
	../src/fibers.cc:54:3: note: candidates are:
	In file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
	                 from ../src/coroutine.h:1,
	                 from ../src/fibers.cc:1:
	/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note: template<class P> void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = P; T = v8::Object]
	   V8_INLINE void SetWeak(P* parameter,
	                  ^
	/root/.node-gyp/8.4.0/include/node/v8.h:544:18: note:   template argument deduction/substitution failed:
	../src/fibers.cc:54:3: note:   candidate expects 3 arguments, 2 provided
	   handle.SetWeak(val, WeakCallbackShim<F>);
	   ^
	In file included from /root/.node-gyp/8.4.0/include/node/node.h:63:0,
	                 from ../src/coroutine.h:1,
	                 from ../src/fibers.cc:1:
	/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note: void v8::PersistentBase<T>::SetWeak() [with T = v8::Object]
	   V8_INLINE void SetWeak();
	                  ^
	/root/.node-gyp/8.4.0/include/node/v8.h:555:18: note:   candidate expects 0 arguments, 2 provided
	../src/fibers.cc: In function 'v8::Handle<v8::Signature> uni::NewSignature(v8::Isolate*, v8::Handle<v8::FunctionTemplate>, int, v8::Handle<v8::FunctionTemplate>*)':
	../src/fibers.cc:133:2: warning: control reaches end of non-void function [-Wreturn-type]
	  }
	  ^
	fibers.target.mk:102: recipe for target 'Release/obj.target/fibers/src/fibers.o' failed
	make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
	make: Leaving directory '/built_app/programs/server/node_modules/fibers/build'
	gyp ERR! build error 
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
	gyp ERR! stack     at emitTwo (events.js:125:13)
	gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
	gyp ERR! System Linux 3.13.0-29-generic
	gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
	gyp ERR! cwd /built_app/programs/server/node_modules/fibers
	gyp ERR! node -v v8.4.0
	gyp ERR! node-gyp -v v3.6.2
	gyp ERR! not ok 
	Build failed
	npm WARN meteor-dev-bundle@0.0.0 No description
	npm WARN meteor-dev-bundle@0.0.0 No repository field.
	npm WARN meteor-dev-bundle@0.0.0 No license field.
	
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! fibers@1.0.5 install: `node ./build.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the fibers@1.0.5 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2018-08-29T21_21_20_234Z-debug.log
	
	      ------------------------------------------------------------------------------
	      
```

**Comment by poojabansal** [comment]
@zodern I've been able to resolve the issue at my end. It was a mismatch between meteor version and docker image.
