### ISSUE TITLE
Configure spiderable with mup

### ISSUE THREAD

**Issue by Silverutm** [zodern/meteor-up#996]
I have added webapp and spiderable
When running the command
curl -A GoogleBot https://mydomain.com

It displays little if nothing info, only the headers, spiderable is supossed to solve problems with web crawlers, but in keeps showing no info

`<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" class="__meteor-css__" href="/....2.css?meteor_css_resource=true">
<meta name="fragment" content="!">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>My title</title>

<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link rel="shortcut icon" type="image/x-icon" href="...logo.ico" />
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

</head>
<body>
<script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.7.0.4%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%2C%22TEST_METADAT.......%7D"))</script>
<script type="text/javascript" src="/13f926cf....6ad23227.js?meteor_js_resource=true"></script>
</body>
</html>`

Mup version
1.4.5

Mup config
```js
{
  "servers": {
    "one": {
      "host": "1.2.3.4",
      "username": "username",
      "password": "password"
    }
  },
  "app": {
    "name": "my-app",
    "path": "../",
    "servers": {
      "one": {}
    },
    "buildOptions": {
      "serverOnly": true
    },
    "env": {
      "ROOT_URL": "https://subdomain.host.com",
      "MONGO_URL": "mongodb://mongodb:27017/my-app",
      "MONGO_OPLOG_URL": "mongodb://mongodb/local",
      "MAIL_URL": "smtps://......"
    },
    "docker": {
      "image": "zodern/meteor:root",
      "stopAppDuringPrepareBundle": true,
      "args": [
        "--link=mongodb:mongodb"
      ]
    },
    "enableUploadProgressBar": true,
    "type": "meteor"
  },
  "mongo": {
    "version": "3.4.1",
    "servers": {
      "one": {}
    }
  }
}
✓ Config is valid
```

mup logs
```
spiderable: phantomjs failed at https://domain.com/: { Error: Command failed: /usr/bin/env bash -c exec phantomjs  --load-images=no --ssl-protocol=TLSv1 /dev/stdin <<'END'
[1.2.3.4]var url = "https://www.domain.com/";// 'url' is assigned to in a statement before this.
[1.2.3.4]var page = require('webpage').create();
[1.2.3.4]
[1.2.3.4]var isReady = function () {
[1.2.3.4]  return page.evaluate(function () {
[1.2.3.4]    if (typeof Meteor === 'undefined'
[1.2.3.4]        || Meteor.status === undefined
[1.2.3.4]        || !Meteor.status().connected) {
[1.2.3.4]      return false;
[1.2.3.4]    }
[1.2.3.4]    if (typeof Package === 'undefined'
[1.2.3.4]        || Package.spiderable === undefined
[1.2.3.4]        || Package.spiderable.Spiderable === undefined) {
[1.2.3.4]      return false;
[1.2.3.4]    }
[1.2.3.4]    return Package.spiderable.Spiderable.isReady();
[1.2.3.4]  });
[1.2.3.4]};
[1.2.3.4]
[1.2.3.4]var dumpPageContent = function () {
[1.2.3.4]  var out = page.content;
[1.2.3.4]  out = out.replace(/<script[^>]+>(.|\n|\r)*?<\/script\s*>/ig, '');
[1.2.3.4]  out = out.replace('<meta name="fragment" content="!">', '');
[1.2.3.4]  console.log(out);
[1.2.3.4]};
[1.2.3.4]
[1.2.3.4]page.open(url, function(status) {
[1.2.3.4]  if (status === 'fail')
[1.2.3.4]    phantom.exit();
[1.2.3.4]});
[1.2.3.4]
[1.2.3.4]setInterval(function() {
[1.2.3.4]  if (isReady()) {
[1.2.3.4]    dumpPageContent();
[1.2.3.4]    phantom.exit();
[1.2.3.4]  }
[1.2.3.4]}, 100);
[1.2.3.4]END
[1.2.3.4]
[1.2.3.4]
[1.2.3.4]    at ChildProcess.exithandler (child_process.js:275:12)
[1.2.3.4]    at emitTwo (events.js:126:13)
[1]    at ChildProcess.emit (events.js:214:7)
[1.2.3.4]    at maybeClose (internal/child_process.js:925:16)
[1.2.3.4]    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[1.2.3.4]  killed: true,
[1.2.3.4]  code: null,
[1.2.3.4]  signal: 'SIGTERM',
[1.2.3.4]  cmd: '/usr/bin/env bash -c exec phantomjs  --load-images=no --ssl-protocol=TLSv1 /dev/stdin <<\'END\'\nvar url = "https://www.domain.com/";// \'url\' is assigned to in a statement before this.\nvar page = require(\'webpage\').create();\n\nvar isReady = function () {\n  return page.evaluate(function () {\n    if (typeof Meteor === \'undefined\'\n        || Meteor.status === undefined\n        || !Meteor.status().connected) {\n      return false;\n    }\n    if (typeof Package === \'undefined\'\n        || Package.spiderable === undefined\n        || Package.spiderable.Spiderable === undefined) {\n      return false;\n    }\n    return Package.spiderable.Spiderable.isReady();\n  });\n};\n\nvar dumpPageContent = function () {\n  var out = page.content;\n  out = out.replace(/<script[^>]+>(.|\\n|\\r)*?<\\/script\\s*>/ig, \'\');\n  out = out.replace(\'<meta name="fragment" content="!">\', \'\');\n  console.log(out);\n};\n\npage.open(url, function(status) {\n  if (status === \'fail\')\n    phantom.exit();\n});\n\nsetInterval(function() {\n  if (isReady()) {\n    dumpPageContent();\n    phantom.exit();\n  }\n}, 100);\nEND\n' } 
[1.2.3.4]stderr:  
[1.2.3.4]stdout: 
```

**Comment by Silverutm** [comment]
ostrio:spiderable-middleware solved the problem
